import type { Confederation } from './api';

/** Maps country/nation names (as from Transfermarkt) to FIFA confederation. */
const COUNTRY_TO_CONFEDERATION: Record<string, Confederation> = {
  // UEFA - Europe
  England: 'UEFA',
  Germany: 'UEFA',
  Spain: 'UEFA',
  Italy: 'UEFA',
  France: 'UEFA',
  Netherlands: 'UEFA',
  Portugal: 'UEFA',
  Belgium: 'UEFA',
  Turkey: 'UEFA',
  Russia: 'UEFA',
  Israel: 'UEFA',
  Scotland: 'UEFA',
  Greece: 'UEFA',
  Austria: 'UEFA',
  Switzerland: 'UEFA',
  Poland: 'UEFA',
  Ukraine: 'UEFA',
  'Czech Republic': 'UEFA',
  Czechia: 'UEFA',
  Denmark: 'UEFA',
  Sweden: 'UEFA',
  Norway: 'UEFA',
  Romania: 'UEFA',
  Bulgaria: 'UEFA',
  Croatia: 'UEFA',
  Serbia: 'UEFA',
  Hungary: 'UEFA',
  Slovakia: 'UEFA',
  Slovenia: 'UEFA',
  Cyprus: 'UEFA',
  Finland: 'UEFA',
  Iceland: 'UEFA',
  'Bosnia-Herzegovina': 'UEFA',
  'Bosnia and Herzegovina': 'UEFA',
  'North Macedonia': 'UEFA',
  Macedonia: 'UEFA',
  Albania: 'UEFA',
  Montenegro: 'UEFA',
  Luxembourg: 'UEFA',
  Malta: 'UEFA',
  Ireland: 'UEFA',
  'Republic of Ireland': 'UEFA',
  Wales: 'UEFA',
  'Northern Ireland': 'UEFA',
  Belarus: 'UEFA',
  Georgia: 'UEFA',
  Armenia: 'UEFA',
  Azerbaijan: 'UEFA',
  Kazakhstan: 'UEFA',
  Moldova: 'UEFA',
  Lithuania: 'UEFA',
  Estonia: 'UEFA',
  Latvia: 'UEFA',
  Kosovo: 'UEFA',
  Andorra: 'UEFA',
  'Faroe Islands': 'UEFA',
  Liechtenstein: 'UEFA',
  'San Marino': 'UEFA',
  Gibraltar: 'UEFA',
  Türkiye: 'UEFA',
  // AFC - Asia
  'Saudi Arabia': 'AFC',
  'United Arab Emirates': 'AFC',
  UAE: 'AFC',
  Qatar: 'AFC',
  China: 'AFC',
  Japan: 'AFC',
  'South Korea': 'AFC',
  'Korea, South': 'AFC',
  Iran: 'AFC',
  India: 'AFC',
  Australia: 'AFC',
  Thailand: 'AFC',
  Malaysia: 'AFC',
  Vietnam: 'AFC',
  Indonesia: 'AFC',
  Uzbekistan: 'AFC',
  Iraq: 'AFC',
  Kuwait: 'AFC',
  Oman: 'AFC',
  Bahrain: 'AFC',
  Jordan: 'AFC',
  Syria: 'AFC',
  Lebanon: 'AFC',
  Philippines: 'AFC',
  Singapore: 'AFC',
  'Hong Kong': 'AFC',
  'Chinese Taipei': 'AFC',
  Taiwan: 'AFC',
  Bangladesh: 'AFC',
  Nepal: 'AFC',
  'Sri Lanka': 'AFC',
  Palestine: 'AFC',
  Yemen: 'AFC',
  Tajikistan: 'AFC',
  Turkmenistan: 'AFC',
  Kyrgyzstan: 'AFC',
  Myanmar: 'AFC',
  Maldives: 'AFC',
  Afghanistan: 'AFC',
  // CONMEBOL - South America
  Brazil: 'CONMEBOL',
  Argentina: 'CONMEBOL',
  Colombia: 'CONMEBOL',
  Chile: 'CONMEBOL',
  Peru: 'CONMEBOL',
  Ecuador: 'CONMEBOL',
  Uruguay: 'CONMEBOL',
  Paraguay: 'CONMEBOL',
  Bolivia: 'CONMEBOL',
  Venezuela: 'CONMEBOL',
  // CONCACAF - North/Central America
  Mexico: 'CONCACAF',
  'United States': 'CONCACAF',
  USA: 'CONCACAF',
  Canada: 'CONCACAF',
  'Costa Rica': 'CONCACAF',
  Honduras: 'CONCACAF',
  Panama: 'CONCACAF',
  Jamaica: 'CONCACAF',
  'Trinidad and Tobago': 'CONCACAF',
  'Trinidad & Tobago': 'CONCACAF',
  Guatemala: 'CONCACAF',
  'El Salvador': 'CONCACAF',
  Nicaragua: 'CONCACAF',
  Cuba: 'CONCACAF',
  'Dominican Republic': 'CONCACAF',
  Haiti: 'CONCACAF',
  Curaçao: 'CONCACAF',
  Curacao: 'CONCACAF',
  Suriname: 'CONCACAF',
  // CAF - Africa
  Egypt: 'CAF',
  Morocco: 'CAF',
  Tunisia: 'CAF',
  'South Africa': 'CAF',
  Nigeria: 'CAF',
  Algeria: 'CAF',
  Ghana: 'CAF',
  Senegal: 'CAF',
  'Ivory Coast': 'CAF',
  "Côte d'Ivoire": 'CAF',
  "Cote d'Ivoire": 'CAF',
  Cameroon: 'CAF',
  Kenya: 'CAF',
  Zimbabwe: 'CAF',
  Zambia: 'CAF',
  Angola: 'CAF',
  'DR Congo': 'CAF',
  'Congo DR': 'CAF',
  Mali: 'CAF',
  Tanzania: 'CAF',
  Ethiopia: 'CAF',
  Libya: 'CAF',
  Sudan: 'CAF',
  Uganda: 'CAF',
  Togo: 'CAF',
  Benin: 'CAF',
  'Burkina Faso': 'CAF',
  Niger: 'CAF',
  Guinea: 'CAF',
  Madagascar: 'CAF',
  Mauritius: 'CAF',
  Botswana: 'CAF',
  Namibia: 'CAF',
  Mozambique: 'CAF',
  Rwanda: 'CAF',
  // OFC - Oceania
  'New Zealand': 'OFC',
  Fiji: 'OFC',
  'Papua New Guinea': 'OFC',
  'Solomon Islands': 'OFC',
};

export function getConfederation(countryName: string | null | undefined): Confederation | null {
  const normalized = countryName?.trim();
  if (!normalized) return null;
  const direct = COUNTRY_TO_CONFEDERATION[normalized];
  if (direct) return direct;
  const first = normalized.split(/[,\s&\/]+/)[0]?.trim();
  if (first) {
    const byFirst = COUNTRY_TO_CONFEDERATION[first];
    if (byFirst) return byFirst;
    const entry = Object.entries(COUNTRY_TO_CONFEDERATION).find(
      ([key]) => key.toLowerCase() === normalized.toLowerCase() || key.toLowerCase() === (first?.toLowerCase() ?? '')
    );
    if (entry) return entry[1];
  }
  return null;
}
