'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'en' | 'he';

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    agent: 'Agent',
    dashboard: 'Dashboard',
    players: 'Players',
    contacts: 'Contacts',
    requests: 'Requests',
    tasks: 'Tasks',
    shortlist: 'Shortlist',
    releases: 'Releases',
    add_player: 'Add Player',
    activity_this_week: 'Activity this week',
    event_types_this_week: 'Event types this week',
    staff_tasks: 'Staff & tasks',
    top_agents_this_week: 'Top agents this week',
    events: 'events',
    no_agent_activity: 'No agent activity this week',
    recent_activity: 'Recent activity',
    no_recent_activity: 'No recent activity. Add a player to get started.',
    loading_feed: 'Loading feed...',
    pending: 'pending',
    no_staff_data: 'No staff data',
    no_events_this_week: 'No events this week',
    market_value_change: 'Market value change',
    club_change: 'Club change',
    contract_expiring: 'Contract expiring',
    note_added: 'Note added',
    player_added: 'Player added',
    free_agent: 'Free agent',
    mandate_expired: 'Mandate expired',
    mandate_uploaded: 'Mandate uploaded',
    shortlist_added: 'Shortlist added',
    shortlist_removed: 'Shortlist removed',
    request_added: 'Request added',
    request_deleted: 'Request deleted',
    player_offered: 'Player offered',
    new_release_from_club: 'New release from club',
    player_deleted: 'Player removed',
    note_deleted: 'Note removed',
    mandate_switched_on: 'Mandate enabled',
    mandate_switched_off: 'Mandate disabled',
    unassigned: 'Unassigned',
    just_now: 'Just now',
    minutes_ago: 'm ago',
    hours_ago: 'h ago',
    by: 'by',
    loading: 'Loading...',
    sign_out: 'Sign out',
    nav_dashboard: 'Dashboard',
    nav_tasks: 'Tasks',
    nav_players: 'Players',
    nav_add_player: 'Add Player',
    nav_shortlist: 'Shortlist',
    nav_contacts: 'Contacts',
    nav_releases: 'Releases',
    nav_returnee: 'Returnees',
    nav_requests: 'Requests',
    tasks_title: 'Tasks',
    tasks_filter_pending: 'Pending',
    tasks_filter_done: 'Done',
    tasks_filter_all: 'All',
    tasks_loading: 'Loading tasks...',
    tasks_empty: 'No tasks yet',
    tasks_empty_hint: 'Add your first task to get started',
    tasks_add: 'Add Task',
    tasks_new_task: 'New Task',
    tasks_what_needs_done: 'What needs to be done?',
    tasks_assign_to: 'Assign to',
    tasks_priority: 'Priority',
    tasks_priority_low: 'Low',
    tasks_priority_medium: 'Medium',
    tasks_priority_high: 'High',
    tasks_due_date: 'Due date',
    tasks_notes_hint: 'Add notes (optional)',
    tasks_create: 'Create Task',
    tasks_edit: 'Edit',
    tasks_delete: 'Delete',
    tasks_delete_confirm: 'Delete this task?',
    tasks_save: 'Save',
    tasks_cancel: 'Cancel',
    tasks_due_today: 'Today',
    tasks_due_tomorrow: 'Tomorrow',
    tasks_overdue: 'Overdue',
    tasks_no_date: 'No date',
    tasks_completed: 'completed',
    tasks_all_agents: 'All agents',
    tasks_my_tasks: 'My tasks',
    tasks_overdue_count: 'Overdue',
    tasks_agents: 'agents',
    tasks_due_today_count: 'Due today',
    tasks_completed_count: 'completed',
    tasks_section_overdue: 'Overdue',
    tasks_section_today: 'Today',
    tasks_section_tomorrow: 'Tomorrow',
    tasks_section_this_week: 'This week',
    tasks_section_later: 'Later',
    tasks_section_no_date: 'No due date',
    tasks_section_completed: 'Completed',
    tasks_progress: 'progress',
    players_title: 'Our Roster',
    players_add: 'Add Player',
    players_loading: 'Loading players...',
    players_empty: 'No players yet',
    players_empty_hint: 'Add your first player to build your roster',
    players_total: 'Total',
    players_value: 'Value',
    players_club: 'Club',
    players_age: 'yrs',
    shortlist_title: 'Shortlist',
    shortlist_loading: 'Loading shortlist...',
    shortlist_empty: 'Your shortlist is empty',
    shortlist_empty_hint: 'Browse releases or add from Transfermarkt',
    shortlist_browse_releases: 'Browse Releases',
    shortlist_browse_returnees: 'Browse Returnees',
    shortlist_add_from_tm: 'Add from Transfermarkt',
    shortlist_remove: 'Remove',
    shortlist_add: 'Add to Shortlist',
    shortlist_adding: 'Adding...',
    shortlist_added_by: 'Added by',
    shortlist_added_today: 'Added today',
    shortlist_added_yesterday: 'Added yesterday',
    shortlist_added_days_ago: 'Added {n} days ago',
    shortlist_added_week_ago: 'Added 1 week ago',
    shortlist_added_weeks_ago: 'Added {n} weeks ago',
    shortlist_added_months_ago: 'Added {n} months ago',
    shortlist_player_in_roster: 'Player is already in roster',
    contacts_title: 'Contacts',
    contacts_all: 'All',
    contacts_clubs: 'Clubs',
    contacts_agencies: 'Agencies',
    contacts_loading: 'Loading contacts...',
    contacts_empty: 'No contacts yet',
    contacts_contact: 'Contact',
    transfer_windows_title: 'Open Transfer Windows',
    transfer_windows_days_left: '{n} days left',
    transfer_windows_open: 'Open',
    transfer_windows_empty: 'No open transfer windows at the moment.',
    transfer_windows_closing_soon: '{n} closing soon',
    transfer_windows_group_priority: 'Priority Markets',
    transfer_windows_group_uefa: 'Europe (UEFA)',
    transfer_windows_group_conmebol: 'South America (CONMEBOL)',
    transfer_windows_group_concacaf: 'North & Central America (CONCACAF)',
    transfer_windows_group_afc: 'Asia (AFC)',
    transfer_windows_group_caf: 'Africa (CAF)',
    transfer_windows_group_ofc: 'Oceania (OFC)',
    releases_title: 'Latest Releases',
    releases_loading: 'Loading releases...',
    releases_empty: 'No releases in this range',
    releases_try_filter: 'Try a different value filter',
    releases_all: 'All',
    releases_add: 'Add',
    releases_free_agent: 'Free agent',
    releases_progress: 'Page {page} • {total} players',
    releases_progress_ranges: 'Range {range}/{totalRanges} • {total} players',
    releases_position: 'Position',
    releases_age: 'Age',
    releases_age_all: 'All ages',
    releases_age_u23: 'Under 23',
    releases_age_23_30: '23-30',
    releases_age_30plus: '30+',
    releases_search: 'Search by name...',
    releases_stats_total: 'Total',
    releases_stats_showing: 'Showing',
    releases_value_filter: 'Value range',
    releases_reload: 'Reload',
    releases_roster_teammates: '{count} roster teammate(s)',
    releases_roster_teammates_tap: 'Roster teammates',
    releases_no_roster_teammates: 'No roster players played with this player',
    releases_roster_teammates_loading: 'Loading teammates…',
    releases_games_together: '{n} games together',
    releases_bookmark: 'Bookmark',
    releases_saved: 'Saved',
    releases_view_shortlist: 'View in shortlist',
    releases_stat_shortlisted: 'Shortlisted',
    returnee_title: 'Returnees',
    returnee_subtitle: 'Players returning from loan across European leagues',
    returnee_no_found: 'No returnees found',
    returnee_loading: 'Loading ({loaded}/{total} leagues)…',
    returnee_stat_leagues: 'Leagues',
    returnee_all_count: 'All {count}',
    returnee_badge_loan_return: 'Loan return',
    returnee_badge_returned_on: 'Returned {date}',
    returnee_clear_filters: 'Clear filters',
    returnee_current_club: 'Current club',
    returnee_returned: 'Returned',
    returnee_market_value: 'Market value',
    requests_title: 'Club Requests',
    requests_subtitle: 'Player requests from clubs by position',
    requests_loading: 'Loading requests...',
    requests_empty: 'No club requests',
    requests_contact: 'Contact',
    requests_add: 'Add request',
    requests_delete: 'Delete',
    requests_delete_confirm: 'Delete request for {club} ({position})?',
    requests_stat_total: 'Total',
    requests_stat_positions: 'Positions',
    requests_country_club_one: '1 club',
    requests_country_clubs: '{count} clubs',
    requests_notes_label: 'Notes',
    requests_phone: 'Phone',
    requests_salary: 'Salary',
    requests_fee: 'Fee',
    requests_fee_free_loan: 'Free/Free loan',
    requests_age_range: 'Age',
    requests_foot: 'Foot',
    requests_add_title: 'Add Request',
    requests_search_club: 'Search club…',
    requests_search_for_club: 'Search for club',
    requests_change_club: 'Change',
    requests_label_position: 'Position',
    requests_label_requirements: 'Requirements',
    requests_label_notes: 'Notes',
    requests_age_doesnt_matter: "Doesn't matter",
    requests_min: 'Min',
    requests_max: 'Max',
    requests_label_salary: 'Salary range',
    requests_label_fee: 'Transfer fee',
    requests_label_foot: 'Dominant foot',
    requests_foot_left: 'Left',
    requests_foot_right: 'Right',
    requests_foot_any: "Doesn't matter",
    requests_notes_placeholder: 'Additional notes…',
    requests_save: 'Save Request',
    requests_next: 'Next',
    requests_step_club: 'Club',
    requests_step_position: 'Position',
    requests_step_requirements: 'Requirements',
    requests_step_notes: 'Notes',
    requests_matching_players_one: '{count} matching player',
    requests_matching_players: '{count} matching players',
    requests_no_match: 'No roster players match this request',
    requests_find_players_online: 'Find players using AI Scout',
    requests_online_players_loading: 'AI Scout searching…',
    requests_online_players_empty: 'No matching players found online',
    requests_online_match_score: 'Match: {pct}%',
    add_player_title: 'Add Player',
    add_to_shortlist_title: 'Add to Shortlist',
    add_player_back: 'Back to',
    add_player_paste_url: 'Paste Transfermarkt URL',
    add_player_load: 'Load',
    add_player_loading: 'Loading...',
    add_player_search: 'Or search by name',
    add_player_search_btn: 'Search',
    add_player_searching: 'Searching...',
    add_player_confirm: 'Confirm & Add',
    add_player_to_roster: 'Add to Roster',
    add_player_saving: 'Saving...',
    add_player_placeholder_url: 'https://www.transfermarkt.com/...',
    add_player_placeholder_search: 'Player name...',
    add_player_auto_search_hint: 'Results appear as you type',
    add_player_no_results: 'No players found. Try a different name.',
    add_player_from_shortlist_hint: 'Add this shortlisted player to your roster',
    add_player_shortlist_hint: 'Add this player to your shortlist for later',
    add_player_roster_hint: 'Add a new player to your roster',
    add_player_contact_section: 'Contact (optional)',
    player_info_back: 'Back to Players',
    player_info_back_players: 'Back to Players',
    player_info_back_requests: 'Back to Requests',
    player_info_back_releases: 'Back to Releases',
    player_info_back_contract_finisher: 'Back to Contract Finisher',
    player_info_notes: 'Notes',
    player_info_no_notes: 'No notes yet',
    player_info_add_note: 'Add note',
    player_info_edit_note: 'Edit note',
    player_info_delete_note: 'Delete note',
    player_info_delete_note_confirm: 'Are you sure you want to delete this note?',
    player_info_note_placeholder: 'Add a new note…',
    player_info_note_save: 'Save',
    player_info_note_cancel: 'Cancel',
    player_info_agent: 'Agent',
    player_info_age: 'Age',
    player_info_height: 'Height',
    player_info_contract: 'Contract',
    player_info_not_found: 'Player not found',
    player_info_overview: 'Overview',
    player_info_stats: 'Key stats',
    player_info_club: 'Current club',
    player_info_contact: 'Contact',
    player_info_mandate: 'Mandate',
    player_info_documents: 'Documents',
    player_info_value_history: 'Value history',
    player_info_foot: 'Preferred foot',
    player_info_on_loan: 'On loan from',
    player_info_salary: 'Salary range',
    player_info_transfer_fee: 'Transfer fee',
    player_info_agency: 'Agency',
    player_info_view_on_tm: 'View on Transfermarkt',
    player_info_refresh: 'Refresh data',
    player_info_mandate_active: 'Active',
    player_info_mandate_inactive: 'Inactive',
    player_info_doc_expired: 'Expired',
    player_info_nationality: 'Nationality',
    player_info_foot_left: 'Left',
    player_info_foot_right: 'Right',
    player_info_foot_both: 'Both',
    player_info_added_by: 'Added by',
    player_info_agent_phone: 'Agent phone',
    player_info_player_phone: 'Player phone',
    note_written_by: 'Written by',
    login_title: 'MGSR Team',
    login_subtitle: 'Login to your account',
    login_email: 'Email',
    login_password: 'Password',
    login_sign_in: 'Sign in',
    login_signing_in: 'Signing in...',
    login_hint: 'Use the same credentials as your Android app',
    common_or: 'or',
    common_years: 'yrs',
    search_no_results: 'No results found',
    search_placeholder: 'Search by name, position or club...',
    contact_type_club: 'Club',
    contact_type_agency: 'Agency',
    contact_role_other: 'Other',
    contact_role_coach: 'Coach',
    contact_role_asst_coach: 'Asst Coach',
    contact_role_sport_dir: 'Sport Dir',
    contact_role_board: 'Board',
    contact_role_ceo: 'CEO',
    contact_role_president: 'President',
    contact_role_scout: 'Scout / Analyst',
    contact_role_agent: 'Agent',
    contact_role_intermediary: 'Intermediary',
    contact_role_agency_dir: 'Agency Dir',
    no_club: 'No club',
    nav_contract_finisher: 'Contract Finisher',
    contract_finisher_title: 'Contract Finisher',
    contract_finisher_subtitle_summer: 'Contracts expiring towards Summer window',
    contract_finisher_subtitle_winter: 'Contracts expiring towards Winter window',
    contract_finisher_loading: 'Loading…',
    contract_finisher_loading_more: 'Loading more…',
    contract_finisher_retry: 'Retry',
    contract_finisher_badge: 'Release date',
    contract_finisher_no_found: 'No contract finishers found in this range',
    contract_finisher_no_match_filters: 'No players match your filters',
    contract_finisher_clear_filters: 'Clear filters',
    contract_finisher_apply_filters: 'Apply Filters',
    contract_finisher_filter_age_all: 'All',
    contract_finisher_filter_age_18_21: '18-21',
    contract_finisher_filter_age_22_25: '22-25',
    contract_finisher_filter_age_26_29: '26-29',
    contract_finisher_filter_age_30_plus: '30+',
    contract_finisher_filter_value_all: 'All',
    contract_finisher_filter_value_150k_500k: '€150K–500K',
    contract_finisher_filter_value_500k_1m: '€500K–1M',
    contract_finisher_filter_value_1m_2m: '€1M–2M',
    contract_finisher_filter_value_2m_3m: '€2M–3M',
    contract_finisher_filter_label_value: 'Value',
    contract_finisher_filter_label_position: 'Position',
    contract_finisher_filter_label_age: 'Age',
    contract_finisher_filter_label_region: 'Region',
    contract_finisher_stats_total: 'Total',
    contract_finisher_stats_shortlisted: 'Shortlisted',
    contract_finisher_stats_visible: 'Visible',
    contract_finisher_filters: 'Filters',
    roster_analytics_title: 'Roster Analytics',
    roster_analytics_position: 'By Position',
    roster_analytics_age: 'By Age',
    roster_analytics_value: 'By Market Value',
    roster_analytics_contracts: 'Contracts Expiring',
    roster_analytics_mandates: 'Mandate Status',
    roster_analytics_with_mandate: 'With mandate',
    roster_analytics_without_mandate: 'Without mandate',
    roster_analytics_age_u21: 'U21',
    roster_analytics_age_22_25: '22-25',
    roster_analytics_age_26_29: '26-29',
    roster_analytics_age_30_plus: '30+',
    roster_analytics_value_unknown: 'Unknown',
    roster_analytics_value_0_500k: '0-500K',
    roster_analytics_value_500k_1m: '500K-1M',
    roster_analytics_value_1m_5m: '1M-5M',
    roster_analytics_value_5m_plus: '5M+',
    players_filter_free_agents: 'Free Agents',
    players_filter_contract_expiring: 'Contract Expiring',
    players_filter_with_mandate: 'With Mandate',
    players_filter_my_players_only: 'My Players Only',
    players_filter_loan_players_only: 'Loan Players Only',
    players_filter_with_notes: 'With Notes',
    players_filter_foot_left: 'Left foot',
    players_filter_foot_right: 'Right foot',
    players_filter_position_gk: 'GK',
    players_filter_position_def: 'DEF',
    players_filter_position_mid: 'MID',
    players_filter_position_fwd: 'FWD',
    players_filter_clear: 'Clear filters',
  },
  he: {
    greeting_morning: 'בוקר טוב',
    greeting_afternoon: 'צהריים טובים',
    greeting_evening: 'ערב טוב',
    agent: 'סוכן',
    dashboard: 'לוח בקרה',
    players: 'שחקנים',
    contacts: 'אנשי קשר',
    requests: 'בקשות',
    tasks: 'משימות',
    shortlist: 'רשימת מעקב',
    releases: 'שחרורים',
    add_player: 'הוסף שחקן',
    activity_this_week: 'פעילות השבוע',
    event_types_this_week: 'סוגי אירועים השבוע',
    staff_tasks: 'צוות ומשימות',
    top_agents_this_week: 'סוכנים מובילים השבוע',
    events: 'אירועים',
    no_agent_activity: 'אין פעילות סוכנים השבוע',
    recent_activity: 'פעילות אחרונה',
    no_recent_activity: 'אין פעילות. הוסף שחקן כדי להתחיל.',
    loading_feed: 'טוען...',
    pending: 'ממתין',
    no_staff_data: 'אין נתוני צוות',
    no_events_this_week: 'אין אירועים השבוע',
    market_value_change: 'שינוי שווי שוק',
    club_change: 'חילוף מועדון',
    contract_expiring: 'חוזה מסתיים',
    note_added: 'הערה נוספה',
    player_added: 'שחקן נוסף',
    free_agent: 'שחקן חופשי',
    mandate_expired: 'מנדט פג תוקף',
    mandate_uploaded: 'מנדט הועלה',
    shortlist_added: 'נוסף לרשימת מעקב',
    shortlist_removed: 'הוסר מרשימת מעקב',
    request_added: 'בקשה נוספה',
    request_deleted: 'בקשה נמחקה',
    player_offered: 'שחקן הוצע',
    new_release_from_club: 'שחרור חדש ממועדון',
    player_deleted: 'שחקן הוסר',
    note_deleted: 'הערה נמחקה',
    mandate_switched_on: 'מנדט הופעל',
    mandate_switched_off: 'מנדט בוטל',
    unassigned: 'ללא שיוך',
    just_now: 'עכשיו',
    minutes_ago: 'דק׳',
    hours_ago: 'ש׳',
    by: 'על ידי',
    loading: 'טוען...',
    sign_out: 'התנתק',
    nav_dashboard: 'לוח בקרה',
    nav_tasks: 'משימות',
    nav_players: 'שחקנים',
    nav_add_player: 'הוסף שחקן',
    nav_shortlist: 'רשימת מעקב',
    nav_contacts: 'אנשי קשר',
    nav_releases: 'שחרורים',
    nav_returnee: 'חזרו מהשאלה',
    nav_requests: 'בקשות',
    tasks_title: 'משימות',
    tasks_filter_pending: 'ממתין',
    tasks_filter_done: 'הושלם',
    tasks_filter_all: 'הכל',
    tasks_loading: 'טוען משימות...',
    tasks_empty: 'אין משימות עדיין',
    tasks_empty_hint: 'הוסף את המשימה הראשונה שלך',
    tasks_add: 'הוסף משימה',
    tasks_new_task: 'משימה חדשה',
    tasks_what_needs_done: 'מה צריך לעשות?',
    tasks_assign_to: 'הקצה ל',
    tasks_priority: 'עדיפות',
    tasks_priority_low: 'נמוכה',
    tasks_priority_medium: 'בינונית',
    tasks_priority_high: 'גבוהה',
    tasks_due_date: 'תאריך יעד',
    tasks_notes_hint: 'הוסף הערות (אופציונלי)',
    tasks_create: 'צור משימה',
    tasks_edit: 'ערוך',
    tasks_delete: 'מחק',
    tasks_delete_confirm: 'למחוק את המשימה?',
    tasks_save: 'שמור',
    tasks_cancel: 'ביטול',
    tasks_due_today: 'היום',
    tasks_due_tomorrow: 'מחר',
    tasks_overdue: 'באיחור',
    tasks_no_date: 'ללא תאריך',
    tasks_completed: 'הושלם',
    tasks_all_agents: 'כל הסוכנים',
    tasks_my_tasks: 'המשימות שלי',
    tasks_overdue_count: 'באיחור',
    tasks_agents: 'סוכנים',
    tasks_due_today_count: 'להיום',
    tasks_completed_count: 'הושלמו',
    tasks_section_overdue: 'באיחור',
    tasks_section_today: 'היום',
    tasks_section_tomorrow: 'מחר',
    tasks_section_this_week: 'השבוע',
    tasks_section_later: 'מאוחר יותר',
    tasks_section_no_date: 'ללא תאריך',
    tasks_section_completed: 'הושלמו',
    tasks_progress: 'התקדמות',
    players_title: 'הסגל שלנו',
    players_add: 'הוסף שחקן',
    players_loading: 'טוען שחקנים...',
    players_empty: 'אין שחקנים עדיין',
    players_empty_hint: 'הוסף את השחקן הראשון לבניית הסגל',
    players_total: 'סה״כ',
    players_value: 'שווי',
    players_club: 'מועדון',
    players_age: 'שנים',
    shortlist_title: 'רשימת מעקב',
    shortlist_loading: 'טוען רשימת מעקב...',
    shortlist_empty: 'רשימת המעקב ריקה',
    shortlist_empty_hint: 'עיין בשחרורים או הוסף מ-Transfermarkt',
    shortlist_browse_releases: 'עיין בשחרורים',
    shortlist_browse_returnees: 'עיין בחזר מהשאלה',
    shortlist_add_from_tm: 'הוסף מ-Transfermarkt',
    shortlist_remove: 'הסר',
    shortlist_add: 'הוסף לרשימת מעקב',
    shortlist_adding: 'מוסיף...',
    shortlist_added_by: 'נוסף על ידי',
    shortlist_added_today: 'נוסף היום',
    shortlist_added_yesterday: 'נוסף אתמול',
    shortlist_added_days_ago: 'נוסף לפני {n} ימים',
    shortlist_added_week_ago: 'נוסף לפני שבוע',
    shortlist_added_weeks_ago: 'נוסף לפני {n} שבועות',
    shortlist_added_months_ago: 'נוסף לפני {n} חודשים',
    shortlist_player_in_roster: 'השחקן כבר בסגל',
    contacts_title: 'אנשי קשר',
    contacts_all: 'הכל',
    contacts_clubs: 'מועדונים',
    contacts_agencies: 'סוכנויות',
    contacts_loading: 'טוען אנשי קשר...',
    contacts_empty: 'אין אנשי קשר עדיין',
    contacts_contact: 'איש קשר',
    transfer_windows_title: 'חלונות העברה פתוחים',
    transfer_windows_days_left: '{n} ימים נותרו',
    transfer_windows_open: 'פתוח',
    transfer_windows_empty: 'אין חלונות העברה פתוחים כרגע.',
    transfer_windows_closing_soon: '{n} נסגרים בקרוב',
    transfer_windows_group_priority: 'שווקים עיקריים',
    transfer_windows_group_uefa: 'אירופה (UEFA)',
    transfer_windows_group_conmebol: 'דרום אמריקה (CONMEBOL)',
    transfer_windows_group_concacaf: 'צפון ומרכז אמריקה (CONCACAF)',
    transfer_windows_group_afc: 'אסיה (AFC)',
    transfer_windows_group_caf: 'אפריקה (CAF)',
    transfer_windows_group_ofc: 'אוקיאניה (OFC)',
    releases_title: 'שחרורים אחרונים',
    releases_loading: 'טוען שחרורים...',
    releases_empty: 'אין שחרורים בטווח זה',
    releases_try_filter: 'נסה טווח שווי אחר',
    releases_all: 'הכל',
    releases_add: 'הוסף',
    releases_free_agent: 'שחקן חופשי',
    releases_progress: 'עמוד {page} • {total} שחקנים',
    releases_progress_ranges: 'טווח {range}/{totalRanges} • {total} שחקנים',
    releases_position: 'עמדה',
    releases_age: 'גיל',
    releases_age_all: 'כל הגילאים',
    releases_age_u23: 'מתחת ל-23',
    releases_age_23_30: '23-30',
    releases_age_30plus: '30+',
    releases_search: 'חפש לפי שם...',
    releases_stats_total: 'סה״כ',
    releases_stats_showing: 'מוצג',
    releases_value_filter: 'טווח שווי',
    releases_reload: 'טען מחדש',
    releases_roster_teammates: '{count} שחקן מהמאגר שיחק איתו',
    releases_roster_teammates_tap: 'שחקנים מהמאגר ששיחקו איתו',
    releases_no_roster_teammates: 'אין שחקנים מהמאגר ששיחקו עם שחקן זה',
    releases_roster_teammates_loading: 'טוען שחקנים…',
    releases_games_together: '{n} משחקים ביחד',
    releases_bookmark: 'שמור',
    releases_saved: 'נשמר',
    releases_view_shortlist: 'צפה ברשימה',
    releases_stat_shortlisted: 'נשמרו',
    returnee_title: 'חזרו מהשאלה',
    returnee_subtitle: 'שחקנים שחוזרים מהשאלה בליגות אירופאיות',
    returnee_no_found: 'לא נמצאו שחקנים שחזרו',
    returnee_loading: 'טוען ({loaded}/{total} ליגות)…',
    returnee_stat_leagues: 'ליגות',
    returnee_all_count: 'הכל {count}',
    returnee_badge_loan_return: 'חזר מהשאלה',
    returnee_badge_returned_on: 'חזר ב-{date}',
    returnee_clear_filters: 'נקה סינון',
    returnee_current_club: 'מועדון נוכחי',
    returnee_returned: 'חזר',
    returnee_market_value: 'שווי שוק',
    requests_title: 'בקשות מועדונים',
    requests_subtitle: 'בקשות שחקנים ממועדונים לפי עמדה',
    requests_loading: 'טוען בקשות...',
    requests_empty: 'אין בקשות מועדונים',
    requests_contact: 'איש קשר',
    requests_add: 'הוסף בקשה',
    requests_delete: 'מחק',
    requests_delete_confirm: 'למחוק בקשה עבור {club} ({position})?',
    requests_stat_total: 'סה״כ',
    requests_stat_positions: 'עמדות',
    requests_country_club_one: 'מועדון 1',
    requests_country_clubs: '{count} מועדונים',
    requests_notes_label: 'הערות',
    requests_phone: 'טלפון',
    requests_salary: 'שכר',
    requests_fee: 'דמי העברה',
    requests_fee_free_loan: 'חופשי / השאלה בחינם',
    requests_age_range: 'גיל',
    requests_foot: 'רגל',
    requests_add_title: 'הוסף בקשה',
    requests_search_club: 'חפש מועדון…',
    requests_search_for_club: 'חפש מועדון',
    requests_change_club: 'שנה',
    requests_label_position: 'עמדה',
    requests_label_requirements: 'דרישות',
    requests_label_notes: 'הערות',
    requests_age_doesnt_matter: 'לא משנה',
    requests_min: 'מינ',
    requests_max: 'מקס',
    requests_label_salary: 'טווח משכורת',
    requests_label_fee: 'דמי העברה',
    requests_label_foot: 'רגל דומיננטית',
    requests_foot_left: 'שמאל',
    requests_foot_right: 'ימין',
    requests_foot_any: 'לא משנה',
    requests_notes_placeholder: 'הערות נוספות…',
    requests_save: 'שמור בקשה',
    requests_next: 'הבא',
    requests_step_club: 'מועדון',
    requests_step_position: 'עמדה',
    requests_step_requirements: 'דרישות',
    requests_step_notes: 'הערות',
    requests_matching_players_one: '{count} שחקן תואם',
    requests_matching_players: '{count} שחקנים תואמים במאגר',
    requests_no_match: 'אין שחקנים במאגר התואמים לבקשה זו',
    requests_find_players_online: 'מצא שחקנים באמצעות AI Scout',
    requests_online_players_loading: 'AI Scout מחפש…',
    requests_online_players_empty: 'לא נמצאו שחקנים תואמים ברשת',
    requests_online_match_score: 'התאמה: {pct}%',
    add_player_title: 'הוסף שחקן',
    add_to_shortlist_title: 'הוסף לרשימת מעקב',
    add_player_back: 'חזרה ל',
    add_player_paste_url: 'הדבק קישור Transfermarkt',
    add_player_load: 'טען',
    add_player_loading: 'טוען...',
    add_player_search: 'או חפש לפי שם',
    add_player_search_btn: 'חפש',
    add_player_searching: 'מחפש...',
    add_player_confirm: 'אישור והוספה',
    add_player_to_roster: 'הוסף לסגל',
    add_player_saving: 'שומר...',
    add_player_placeholder_url: 'https://www.transfermarkt.com/...',
    add_player_placeholder_search: 'שם שחקן...',
    add_player_auto_search_hint: 'תוצאות מופיעות בזמן הקלדה',
    add_player_no_results: 'לא נמצאו שחקנים. נסה שם אחר.',
    add_player_from_shortlist_hint: 'הוסף שחקן זה מרשימת המעקב לסגל שלך',
    add_player_shortlist_hint: 'הוסף שחקן זה לרשימת המעקב להמשך',
    add_player_roster_hint: 'הוסף שחקן חדש לסגל שלך',
    add_player_contact_section: 'איש קשר (אופציונלי)',
    player_info_back: 'חזרה לשחקנים',
    player_info_back_players: 'חזרה לשחקנים',
    player_info_back_requests: 'חזרה לבקשות',
    player_info_back_releases: 'חזרה לשחרורים',
    player_info_back_contract_finisher: 'חזרה למסיימי חוזה',
    player_info_notes: 'הערות',
    player_info_no_notes: 'אין הערות עדיין',
    player_info_add_note: 'הוסף הערה',
    player_info_edit_note: 'ערוך הערה',
    player_info_delete_note: 'מחק הערה',
    player_info_delete_note_confirm: 'האם אתה בטוח שברצונך למחוק את ההערה?',
    player_info_note_placeholder: 'הוסף הערה חדשה…',
    player_info_note_save: 'שמור',
    player_info_note_cancel: 'ביטול',
    player_info_agent: 'סוכן',
    player_info_age: 'גיל',
    player_info_height: 'גובה',
    player_info_contract: 'חוזה',
    player_info_not_found: 'שחקן לא נמצא',
    player_info_overview: 'סקירה',
    player_info_stats: 'סטטיסטיקות',
    player_info_club: 'מועדון נוכחי',
    player_info_contact: 'איש קשר',
    player_info_mandate: 'מנדט',
    player_info_documents: 'מסמכים',
    player_info_value_history: 'היסטוריית שווי',
    player_info_foot: 'רגל מועדפת',
    player_info_on_loan: 'בהשאלה מ',
    player_info_salary: 'טווח משכורת',
    player_info_transfer_fee: 'דמי העברה',
    player_info_agency: 'סוכנות',
    player_info_view_on_tm: 'צפה ב-Transfermarkt',
    player_info_refresh: 'רענן נתונים',
    player_info_mandate_active: 'פעיל',
    player_info_mandate_inactive: 'לא פעיל',
    player_info_doc_expired: 'פג תוקף',
    player_info_nationality: 'לאום',
    player_info_foot_left: 'שמאל',
    player_info_foot_right: 'ימין',
    player_info_foot_both: 'שתיהן',
    player_info_added_by: 'נוסף על ידי',
    player_info_agent_phone: 'טלפון סוכן',
    player_info_player_phone: 'טלפון שחקן',
    note_written_by: 'נכתב על ידי',
    login_title: 'MGSR Team',
    login_subtitle: 'התחבר לחשבון שלך',
    login_email: 'אימייל',
    login_password: 'סיסמה',
    login_sign_in: 'התחבר',
    login_signing_in: 'מתחבר...',
    login_hint: 'השתמש באותם פרטי התחברות כמו באפליקציית האנדרואיד',
    common_or: 'או',
    common_years: 'שנים',
    search_no_results: 'לא נמצאו תוצאות',
    search_placeholder: 'חפש לפי שם, עמדה או מועדון...',
    contact_type_club: 'מועדון',
    contact_type_agency: 'סוכנות',
    contact_role_other: 'אחר',
    contact_role_coach: 'מאמן',
    contact_role_asst_coach: 'מאמן משנה',
    contact_role_sport_dir: 'מנהל ספורט',
    contact_role_board: 'דירקטוריון',
    contact_role_ceo: 'מנכ"ל',
    contact_role_president: 'נשיא',
    contact_role_scout: 'סקאוט / אנליסט',
    contact_role_agent: 'סוכן',
    contact_role_intermediary: 'מתווך',
    contact_role_agency_dir: 'מנהל סוכנות',
    no_club: 'ללא מועדון',
    nav_contract_finisher: 'מסיימי חוזה',
    contract_finisher_title: 'מסיימי חוזה',
    contract_finisher_subtitle_summer: 'חוזים שמסתיימים לקראת חלון קיץ',
    contract_finisher_subtitle_winter: 'חוזים שמסתיימים לקראת חלון חורף',
    contract_finisher_loading: 'טוען…',
    contract_finisher_loading_more: 'טוען עוד…',
    contract_finisher_retry: 'נסה שוב',
    contract_finisher_badge: 'תאריך סיום חוזה',
    contract_finisher_no_found: 'לא נמצאו מסיימי חוזה בטווח זה',
    contract_finisher_no_match_filters: 'אין שחקנים התואמים את הסינון',
    contract_finisher_clear_filters: 'נקה סינון',
    contract_finisher_apply_filters: 'החל סינון',
    contract_finisher_filter_age_all: 'הכל',
    contract_finisher_filter_age_18_21: '18-21',
    contract_finisher_filter_age_22_25: '22-25',
    contract_finisher_filter_age_26_29: '26-29',
    contract_finisher_filter_age_30_plus: '30+',
    contract_finisher_filter_value_all: 'הכל',
    contract_finisher_filter_value_150k_500k: '€150K–500K',
    contract_finisher_filter_value_500k_1m: '€500K–1M',
    contract_finisher_filter_value_1m_2m: '€1M–2M',
    contract_finisher_filter_value_2m_3m: '€2M–3M',
    contract_finisher_filter_label_value: 'שווי',
    contract_finisher_filter_label_position: 'עמדה',
    contract_finisher_filter_label_age: 'גיל',
    contract_finisher_filter_label_region: 'אזור',
    contract_finisher_stats_total: 'סה״כ',
    contract_finisher_stats_shortlisted: 'ברשימה',
    contract_finisher_stats_visible: 'מוצג',
    contract_finisher_filters: 'סינון',
    roster_analytics_title: 'ניתוח סגל',
    roster_analytics_position: 'לפי עמדה',
    roster_analytics_age: 'לפי גיל',
    roster_analytics_value: 'לפי שווי שוק',
    roster_analytics_contracts: 'חוזים מסתיימים',
    roster_analytics_mandates: 'סטטוס מנדט',
    roster_analytics_with_mandate: 'עם מנדט',
    roster_analytics_without_mandate: 'ללא מנדט',
    roster_analytics_age_u21: 'מתחת ל-21',
    roster_analytics_age_22_25: '22-25',
    roster_analytics_age_26_29: '26-29',
    roster_analytics_age_30_plus: '30+',
    roster_analytics_value_unknown: 'לא ידוע',
    roster_analytics_value_0_500k: '0-500K',
    roster_analytics_value_500k_1m: '500K-1M',
    roster_analytics_value_1m_5m: '1M-5M',
    roster_analytics_value_5m_plus: '5M+',
    players_filter_free_agents: 'שחקנים חופשיים',
    players_filter_contract_expiring: 'חוזה מסתיים',
    players_filter_with_mandate: 'עם מנדט',
    players_filter_my_players_only: 'השחקנים שלי בלבד',
    players_filter_loan_players_only: 'שחקנים בהשאלה בלבד',
    players_filter_with_notes: 'עם הערות',
    players_filter_foot_left: 'רגל שמאל',
    players_filter_foot_right: 'רגל ימין',
    players_filter_position_gk: 'שוערים',
    players_filter_position_def: 'הגנה',
    players_filter_position_mid: 'קישור',
    players_filter_position_fwd: 'התקפה',
    players_filter_clear: 'נקה מסננים',
  },
};

const TYPE_KEYS: Record<string, string> = {
  MARKET_VALUE_CHANGE: 'market_value_change',
  CLUB_CHANGE: 'club_change',
  CONTRACT_EXPIRING: 'contract_expiring',
  NOTE_ADDED: 'note_added',
  NOTE_DELETED: 'note_deleted',
  PLAYER_ADDED: 'player_added',
  PLAYER_DELETED: 'player_deleted',
  BECAME_FREE_AGENT: 'free_agent',
  NEW_RELEASE_FROM_CLUB: 'new_release_from_club',
  MANDATE_EXPIRED: 'mandate_expired',
  MANDATE_UPLOADED: 'mandate_uploaded',
  MANDATE_SWITCHED_ON: 'mandate_switched_on',
  MANDATE_SWITCHED_OFF: 'mandate_switched_off',
  SHORTLIST_ADDED: 'shortlist_added',
  SHORTLIST_REMOVED: 'shortlist_removed',
  REQUEST_ADDED: 'request_added',
  REQUEST_DELETED: 'request_deleted',
  PLAYER_OFFERED_TO_CLUB: 'player_offered',
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem('mgsr-lang') as Lang | null;
    if (stored === 'he' || stored === 'en') setLangState(stored);
    setMounted(true);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (mounted) localStorage.setItem('mgsr-lang', l);
  };

  const value: LanguageContextValue = {
    lang,
    setLang,
    t: (k) => TRANSLATIONS[lang][k] ?? k,
    isRtl: lang === 'he',
  };

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export function translateType(type: string, t: (k: string) => string): string {
  const key = TYPE_KEYS[type];
  return key ? t(key) : type;
}
