'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'en' | 'he';

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    agent: 'Agent',
    dashboard: 'Dashboard',
    players: 'Players',
    contacts: 'Contacts',
    requests: 'Requests',
    tasks: 'Tasks',
    shortlist: 'Shortlist',
    releases: 'Releases',
    add_player: 'Add Player',
    activity_this_week: 'Activity this week',
    event_types_this_week: 'Event types this week',
    staff_tasks: 'Staff & tasks',
    top_agents_this_week: 'Top agents this week',
    leading_agencies_title: 'Leading Agencies',
    leading_agencies_in_contact: 'In contact',
    leading_agencies_players: 'players',
    leading_agencies_empty: 'No agencies with players yet. Add agency contacts and link players to their agencies.',
    events: 'events',
    no_agent_activity: 'No agent activity this week',
    recent_activity: 'Recent activity',
    no_recent_activity: 'No recent activity. Add a player to get started.',
    loading_feed: 'Loading feed...',
    pending: 'pending',
    no_staff_data: 'No staff data',
    no_events_this_week: 'No events this week',
    market_value_change: 'Market value change',
    club_change: 'Club change',
    contract_expiring: 'Contract expiring',
    note_added: 'Note added',
    player_added: 'Player added',
    free_agent: 'Free agent',
    mandate_expired: 'Mandate expired',
    mandate_uploaded: 'Mandate uploaded',
    shortlist_added: 'Shortlist added',
    shortlist_removed: 'Shortlist removed',
    request_added: 'Request added',
    request_deleted: 'Request deleted',
    player_offered: 'Player offered',
    new_release_from_club: 'New release from club',
    player_deleted: 'Player removed',
    note_deleted: 'Note removed',
    mandate_switched_on: 'Mandate enabled',
    mandate_switched_off: 'Mandate disabled',
    unassigned: 'Unassigned',
    just_now: 'Just now',
    minutes_ago: 'm ago',
    hours_ago: 'h ago',
    by: 'by',
    loading: 'Loading...',
    sign_out: 'Sign out',
    nav_dashboard: 'Dashboard',
    nav_tasks: 'Tasks',
    nav_players: 'Players',
    nav_add_player: 'Add Player',
    nav_shortlist: 'Shortlist',
    nav_ai_scout: 'AI Scout',
    nav_find_next: 'Find Next',
    nav_contacts: 'Contacts',
    nav_releases: 'Releases',
    nav_returnee: 'Returnees',
    nav_requests: 'Club Requirements',
    tasks_title: 'Tasks',
    tasks_filter_pending: 'Pending',
    tasks_filter_done: 'Done',
    tasks_filter_all: 'All',
    tasks_loading: 'Loading tasks...',
    tasks_empty: 'No tasks yet',
    tasks_empty_hint: 'Add your first task to get started',
    tasks_add: 'Add Task',
    tasks_new_task: 'New Task',
    tasks_what_needs_done: 'What needs to be done?',
    tasks_assign_to: 'Assign to',
    tasks_priority: 'Priority',
    tasks_priority_low: 'Low',
    tasks_priority_medium: 'Medium',
    tasks_priority_high: 'High',
    tasks_due_date: 'Due date',
    tasks_notes_hint: 'Add notes (optional)',
    tasks_create: 'Create Task',
    tasks_edit: 'Edit',
    tasks_delete: 'Delete',
    tasks_delete_confirm: 'Delete this task?',
    tasks_save: 'Save',
    tasks_cancel: 'Cancel',
    tasks_due_today: 'Today',
    tasks_due_tomorrow: 'Tomorrow',
    tasks_overdue: 'Overdue',
    tasks_no_date: 'No date',
    tasks_completed: 'completed',
    tasks_all_agents: 'All agents',
    tasks_my_tasks: 'My tasks',
    tasks_overdue_count: 'Overdue',
    tasks_agents: 'agents',
    tasks_due_today_count: 'Due today',
    tasks_completed_count: 'completed',
    tasks_section_overdue: 'Overdue',
    tasks_section_today: 'Today',
    tasks_section_tomorrow: 'Tomorrow',
    tasks_section_this_week: 'This week',
    tasks_section_later: 'Later',
    tasks_section_no_date: 'No due date',
    tasks_section_completed: 'Completed',
    tasks_progress: 'progress',
    player_tasks_section: 'Player-related tasks',
    player_tasks_add: 'Add task',
    player_tasks_empty: 'No tasks for this player yet',
    player_tasks_choose_template: 'Choose template (recommended)',
    player_tasks_created_by: 'Created by',
    players_title: 'Our Roster',
    players_add: 'Add Player',
    players_loading: 'Loading players...',
    players_empty: 'No players yet',
    players_empty_hint: 'Add your first player to build your roster',
    players_total: 'Total',
    players_value: 'Value',
    players_club: 'Club',
    players_age: 'yrs',
    players_age_display: '{age} yrs',
    shortlist_title: 'Shortlist',
    shortlist_loading: 'Loading shortlist...',
    shortlist_empty: 'Your shortlist is empty',
    shortlist_empty_hint: 'Browse releases or add from Transfermarkt',
    shortlist_browse_releases: 'Browse Releases',
    shortlist_browse_returnees: 'Browse Returnees',
    shortlist_add_from_tm: 'Add from Transfermarkt',
    shortlist_remove: 'Remove',
    shortlist_add: 'Add to Shortlist',
    shortlist_adding: 'Adding...',
    shortlist_added_by: 'Added by',
    shortlist_added_today: 'Added today',
    shortlist_added_yesterday: 'Added yesterday',
    shortlist_added_days_ago: 'Added {n} days ago',
    shortlist_added_week_ago: 'Added 1 week ago',
    shortlist_added_weeks_ago: 'Added {n} weeks ago',
    shortlist_added_months_ago: 'Added {n} months ago',
    shortlist_player_in_roster: 'Player is already in roster',
    contacts_title: 'Contacts',
    contacts_all: 'All',
    contacts_clubs: 'Clubs',
    contacts_agencies: 'Agencies',
    contacts_loading: 'Loading contacts...',
    contacts_empty: 'No contacts yet',
    contacts_contact: 'Contact',
    transfer_windows_title: 'Open Transfer Windows',
    transfer_windows_days_left: '{n} days left',
    transfer_windows_today: 'Today',
    transfer_windows_open: 'Open',
    transfer_windows_empty: 'No open transfer windows at the moment.',
    transfer_windows_closing_soon: '{n} closing soon',
    transfer_windows_group_priority: 'Priority Markets',
    transfer_windows_group_uefa: 'Europe (UEFA)',
    transfer_windows_group_conmebol: 'South America (CONMEBOL)',
    transfer_windows_group_concacaf: 'North & Central America (CONCACAF)',
    transfer_windows_group_afc: 'Asia (AFC)',
    transfer_windows_group_caf: 'Africa (CAF)',
    transfer_windows_group_ofc: 'Oceania (OFC)',
    releases_title: 'Latest Releases',
    releases_loading: 'Loading releases...',
    releases_empty: 'No releases in this range',
    releases_try_filter: 'Try a different value filter',
    releases_all: 'All',
    releases_add: 'Add',
    releases_free_agent: 'Free agent',
    releases_progress: 'Page {page} • {total} players',
    releases_progress_ranges: 'Range {range}/{totalRanges} • {total} players',
    releases_position: 'Position',
    releases_age: 'Age',
    releases_age_all: 'All ages',
    releases_age_u23: 'Under 23',
    releases_age_23_30: '23-30',
    releases_age_30plus: '30+',
    releases_search: 'Search by name...',
    releases_stats_total: 'Total',
    releases_stats_showing: 'Showing',
    releases_sort: 'Sort by',
    releases_sort_value: 'Market value',
    releases_sort_date: 'Release date',
    releases_sort_age: 'Age',
    releases_value_filter: 'Value range',
    releases_reload: 'Reload',
    releases_roster_teammates: '{count} roster teammate(s)',
    releases_roster_teammates_tap: 'Roster teammates',
    releases_no_roster_teammates: 'No roster players played with this player',
    releases_roster_teammates_loading: 'Loading teammates…',
    releases_games_together: '{n} games together',
    releases_bookmark: 'Bookmark',
    releases_saved: 'Saved',
    releases_view_shortlist: 'View in shortlist',
    releases_stat_shortlisted: 'Shortlisted',
    returnee_title: 'Returnees',
    returnee_subtitle: 'Players returning from loan across European leagues',
    returnee_no_found: 'No returnees found',
    returnee_loading: 'Loading ({loaded}/{total} leagues)…',
    returnee_stat_leagues: 'Leagues',
    returnee_all_count: 'All {count}',
    returnee_badge_loan_return: 'Loan return',
    returnee_badge_returned_on: 'Returned {date}',
    returnee_clear_filters: 'Clear filters',
    returnee_current_club: 'Current club',
    returnee_returned: 'Returned',
    returnee_market_value: 'Market value',
    requests_title: 'Club Requests',
    requests_subtitle: 'Player requests from clubs by position',
    ai_scout_title: 'Find your next signing',
    ai_scout_subtitle: 'Describe the player you need in plain language. AI searches thousands of profiles to find the best matches.',
    ai_scout_placeholder: 'e.g. find me 20 strikers up to 26 years old that are very fast and with at least 5 goals last season',
    ai_scout_search: 'Search',
    ai_scout_searching: 'Searching…',
    ai_scout_searching_hint: 'Typically 10–20 seconds',
    ai_scout_local_testing: 'Add GEMINI_API_KEY to .env.local for AI analysis. Without it, mock results are shown.',
    ai_scout_examples: 'Example queries:',
    ai_scout_results_count: '{count} results',
    ai_scout_results_of: '{count} of {total} results',
    ai_scout_no_results: 'No results. Try a different query.',
    ai_scout_interpretation: 'How AI understood your request:',
    requests_loading: 'Loading requests...',
    requests_empty: 'No club requests',
    requests_contact: 'Contact',
    requests_add: 'Add request',
    requests_delete: 'Delete',
    requests_delete_confirm: 'Delete request for {club} ({position})?',
    requests_stat_total: 'Total',
    requests_stat_positions: 'Positions',
    requests_country_club_one: '1 club',
    requests_country_clubs: '{count} clubs',
    requests_notes_label: 'Notes',
    requests_phone: 'Phone',
    requests_salary: 'Salary',
    requests_fee: 'Fee',
    requests_fee_free_loan: 'Free/Free loan',
    requests_age_range: 'Age',
    requests_foot: 'Foot',
    requests_add_title: 'Add Request',
    requests_search_club: 'Search club…',
    requests_search_for_club: 'Search for club',
    requests_change_club: 'Change',
    requests_label_position: 'Position',
    requests_label_requirements: 'Requirements',
    requests_label_notes: 'Notes',
    requests_age_doesnt_matter: "Doesn't matter",
    requests_min: 'Min',
    requests_max: 'Max',
    requests_label_salary: 'Salary range',
    requests_label_fee: 'Transfer fee',
    requests_label_foot: 'Dominant foot',
    requests_foot_left: 'Left',
    requests_foot_right: 'Right',
    requests_foot_any: "Doesn't matter",
    requests_notes_placeholder: 'Additional notes…',
    requests_save: 'Save Request',
    requests_next: 'Next',
    requests_step_club: 'Club',
    requests_step_position: 'Position',
    requests_step_requirements: 'Requirements',
    requests_step_notes: 'Notes',
    requests_matching_players_one: '{count} matching player',
    requests_matching_players: '{count} matching players',
    requests_no_match: 'No roster players match this request',
    requests_find_players_online: 'Find players using AI Scout',
    requests_online_players_loading: 'AI Scout searching…',
    requests_online_players_empty: 'No matching players found online',
    requests_online_match_score: 'Match: {pct}%',
    add_player_title: 'Add Player',
    add_to_shortlist_title: 'Add to Shortlist',
    add_player_back: 'Back to',
    add_player_paste_url: 'Paste Transfermarkt URL',
    add_player_load: 'Load',
    add_player_loading: 'Loading...',
    add_player_search: 'Or search by name',
    add_player_search_btn: 'Search',
    add_player_searching: 'Searching...',
    add_player_confirm: 'Confirm & Add',
    add_player_to_roster: 'Add to Roster',
    add_player_saving: 'Saving...',
    add_player_placeholder_url: 'https://www.transfermarkt.com/...',
    add_player_placeholder_search: 'Player name...',
    add_player_auto_search_hint: 'Results appear as you type',
    add_player_no_results: 'No players found. Try a different name.',
    add_player_from_shortlist_hint: 'Add this shortlisted player to your roster',
    add_player_shortlist_hint: 'Add this player to your shortlist for later',
    add_player_roster_hint: 'Add a new player to your roster',
    add_player_contact_section: 'Contact (optional)',
    player_info_back: 'Back to Players',
    player_info_back_players: 'Back to Players',
    player_info_back_requests: 'Back to Requests',
    player_info_back_releases: 'Back to Releases',
    player_info_back_contract_finisher: 'Back to Contract Finisher',
    player_info_back_shadow_teams: 'Back to Shadow Teams',
    player_info_back_tasks: 'Back to Tasks',
    player_info_notes: 'Notes',
    player_info_no_notes: 'No notes yet',
    player_info_add_note: 'Add note',
    player_info_edit_note: 'Edit note',
    player_info_delete_note: 'Delete note',
    player_info_delete_note_confirm: 'Are you sure you want to delete this note?',
    player_info_note_placeholder: 'Add a new note…',
    player_info_note_save: 'Save',
    player_info_note_cancel: 'Cancel',
    player_info_agent: 'Agent',
    player_info_age: 'Age',
    player_info_height: 'Height',
    player_info_contract: 'Contract',
    player_info_not_found: 'Player not found',
    player_info_overview: 'Overview',
    player_info_stats: 'Key stats',
    player_info_club: 'Current club',
    player_info_contact: 'Contact',
    player_info_mandate: 'Mandate',
    player_info_documents: 'Documents',
    player_info_add_document: 'Add document',
    player_info_no_documents: 'No documents yet',
    player_info_uploading: 'Uploading document…',
    player_info_documents_empty_subtitle: 'Upload passports, mandates, medical docs, or other files.',
    player_info_delete_doc_confirm: 'Are you sure you want to delete',
    player_info_cd_open_link: 'Open link',
    player_info_cd_delete_document: 'Delete document',
    player_info_generate_mandate: 'Generate mandate',
    player_info_share: 'Share',
    mandate_no_passport: 'No passport details. Upload a passport document first.',
    mandate_step_agent: 'Select agent',
    mandate_no_agents_fifa: 'No agents with FIFA license found',
    mandate_fifa_license: 'FIFA License',
    mandate_step_validity: 'Validity & leagues',
    mandate_expiry_date: 'Expiry date',
    mandate_valid_leagues: 'Valid leagues',
    mandate_search_country: 'Search country...',
    mandate_add_country_league: 'Add country / league',
    mandate_entire_country: 'Entire country (all clubs)',
    mandate_sheet_search_clubs: 'Search clubs in %s…',
    mandate_selected_clubs: '%d club(s) selected',
    mandate_sheet_add_button: 'Add to mandate',
    mandate_change_country: 'Change',
    mandate_selected: 'Selected',
    mandate_step_review: 'Review',
    mandate_review_player: 'Player',
    mandate_review_agent: 'Agent',
    mandate_review_fifa_id: 'FIFA License ID',
    mandate_back: 'Back',
    mandate_next: 'Next',
    mandate_generating: 'Generating...',
    mandate_generate_pdf: 'Generate PDF',
    upload_failed: 'Upload failed. Please try again.',
    passport_already_exists: 'This player already has passport details. Delete the existing passport document first.',
    player_info_value_history: 'Value history',
    player_info_foot: 'Preferred foot',
    player_info_on_loan: 'On loan from',
    player_info_salary: 'Salary range',
    player_info_transfer_fee: 'Transfer fee',
    player_info_agency: 'Agency',
    player_info_view_on_tm: 'View on Transfermarkt',
    player_info_refresh: 'Refresh data',
    similar_players_title: 'Similar Players',
    similar_players_find: 'Find Similar Players',
    similar_players_searching: 'Searching for similar players…',
    similar_players_match: 'Match',
    similar_players_style: 'Style',
    similar_players_nationality: 'Nationality',
    similar_players_league: 'League',
    similar_players_height: 'Height',
    similar_players_foot: 'Foot',
    similar_players_contract: 'Contract',
    similar_players_view_profile: 'View on Transfermarkt',
    similar_players_load_more: 'Load more similar players',
    similar_players_retry: 'Try again',
    similar_players_empty: 'No similar players found',
    similar_players_per90: 'Per 90 minutes',
    similar_players_growth: 'growth',
    similar_players_club: 'Club',
    similar_players_sources_hint: 'Analysis combines Transfermarkt, FBref stats & FM data',
    player_info_mandate_active: 'Active',
    player_info_mandate_inactive: 'Inactive',
    player_info_mandate_expires: 'Mandate expires: %s',
    player_info_doc_expired: 'Expired',
    player_info_nationality: 'Nationality',
    player_info_foot_left: 'Left',
    player_info_foot_right: 'Right',
    player_info_foot_both: 'Both',
    player_info_added_by: 'Added by',
    player_info_agent_phone: 'Agent phone',
    player_info_player_phone: 'Player phone',
    note_written_by: 'Written by',
    login_title: 'MGSR Team',
    login_subtitle: 'Login to your account',
    login_email: 'Email',
    login_password: 'Password',
    login_sign_in: 'Sign in',
    login_signing_in: 'Signing in...',
    login_hint: 'Use the same credentials as your Android app',
    common_or: 'or',
    common_years: 'yrs',
    search_no_results: 'No results found',
    search_placeholder: 'Search by name, position or club...',
    contact_type_club: 'Club',
    contact_type_agency: 'Agency',
    contact_role_other: 'Other',
    contact_role_coach: 'Coach',
    contact_role_asst_coach: 'Asst Coach',
    contact_role_sport_dir: 'Sport Dir',
    contact_role_board: 'Board',
    contact_role_ceo: 'CEO',
    contact_role_president: 'President',
    contact_role_scout: 'Scout / Analyst',
    contact_role_agent: 'Agent',
    contact_role_intermediary: 'Intermediary',
    contact_role_agency_dir: 'Agency Dir',
    no_club: 'No club',
    nav_shadow_teams: 'Shadow Teams',
    nav_contract_finisher: 'Contract Finisher',
    contract_finisher_title: 'Contract Finisher',
    contract_finisher_subtitle_summer: 'Contracts expiring towards Summer window',
    contract_finisher_subtitle_winter: 'Contracts expiring towards Winter window',
    contract_finisher_loading: 'Loading…',
    contract_finisher_loading_more: 'Loading more…',
    contract_finisher_retry: 'Retry',
    contract_finisher_badge: 'Release date',
    contract_finisher_no_found: 'No contract finishers found in this range',
    contract_finisher_no_match_filters: 'No players match your filters',
    contract_finisher_clear_filters: 'Clear filters',
    contract_finisher_apply_filters: 'Apply Filters',
    contract_finisher_filter_age_all: 'All',
    contract_finisher_filter_age_18_21: '18-21',
    contract_finisher_filter_age_22_25: '22-25',
    contract_finisher_filter_age_26_29: '26-29',
    contract_finisher_filter_age_30_plus: '30+',
    contract_finisher_filter_value_all: 'All',
    contract_finisher_filter_value_150k_500k: '€150K–500K',
    contract_finisher_filter_value_500k_1m: '€500K–1M',
    contract_finisher_filter_value_1m_2m: '€1M–2M',
    contract_finisher_filter_value_2m_3m: '€2M–3M',
    contract_finisher_filter_label_value: 'Value',
    contract_finisher_filter_label_position: 'Position',
    contract_finisher_filter_label_age: 'Age',
    contract_finisher_filter_label_region: 'Region',
    contract_finisher_stats_total: 'Total',
    contract_finisher_stats_shortlisted: 'Shortlisted',
    contract_finisher_stats_visible: 'Visible',
    contract_finisher_filters: 'Filters',
    roster_analytics_title: 'Roster Analytics',
    roster_analytics_position: 'By Position',
    roster_analytics_age: 'By Age',
    roster_analytics_value: 'By Market Value',
    roster_analytics_contracts: 'Contracts Expiring',
    roster_analytics_mandates: 'Mandate Status',
    roster_analytics_with_mandate: 'With mandate',
    roster_analytics_without_mandate: 'Without mandate',
    roster_analytics_age_u21: 'U21',
    roster_analytics_age_22_25: '22-25',
    roster_analytics_age_26_29: '26-29',
    roster_analytics_age_30_plus: '30+',
    roster_analytics_value_unknown: 'Unknown',
    roster_analytics_value_0_500k: '0-500K',
    roster_analytics_value_500k_1m: '500K-1M',
    roster_analytics_value_1m_5m: '1M-5M',
    roster_analytics_value_5m_plus: '5M+',
    players_filter_free_agents: 'Free Agents',
    players_filter_contract_expiring: 'Contract Expiring',
    players_filter_with_mandate: 'With Mandate',
    players_filter_my_players_only: 'My Players Only',
    players_filter_loan_players_only: 'Loan Players Only',
    players_filter_without_registered_agent: 'Without Registered Agent',
    players_filter_with_notes: 'With Notes',
    players_filter_foot_left: 'Left foot',
    players_filter_foot_right: 'Right foot',
    players_filter_position_gk: 'GK',
    players_filter_position_def: 'DEF',
    players_filter_position_mid: 'MID',
    players_filter_position_fwd: 'FWD',
    players_filter_clear: 'Clear filters',
    shadow_teams_title: 'Shadow Teams',
    shadow_teams_subtitle: 'Your preferred players for the next transfer window',
    shadow_teams_formation: 'Formation',
    shadow_teams_hint: "Switch tabs to see each agent's team • Your tab: add, edit, remove • Others: view profile only",
    shadow_teams_bench: 'Bench',
    shadow_teams_select_player: 'Select player',
    shadow_teams_search_player: 'Search player',
    shadow_teams_no_players: 'No players found for this position',
    shadow_teams_cancel: 'Cancel',
    shadow_teams_view_player: 'View profile',
    shadow_teams_change_player: 'Change player',
    shadow_teams_remove_player: 'Remove',
    shadow_teams_you: 'You',
    // Player Highlights
    highlights_title: 'Highlights',
    highlights_loading: 'Loading highlights...',
    highlights_empty: 'No highlight videos found for this player',
    highlights_recent_matches: 'Recent Match Highlights',
    highlights_compilations: 'Player Highlights',
    highlights_powered_by: 'Powered by YouTube & Scorebat',
    highlights_updated: 'Updated',
    highlights_views: 'views',
    // FM Intelligence Panel
    fm_tab_intelligence: 'FM Intelligence',
    fm_tab_position_fit: 'Position Fit',
    fm_loading: 'Loading FM Intelligence...',
    fm_current_ability: 'Current Ability',
    fm_pa_label: 'Potential Ability',
    fm_potential: 'potential',
    fm_at_peak: 'At peak',
    fm_best_fit: 'Best fit:',
    fm_ability_dimensions: 'Ability Dimensions',
    fm_top_attributes: 'Top Attributes',
    fm_weaknesses: 'Weaknesses',
    fm_no_weaknesses: 'No major weaknesses',
    fm_position_rankings: 'Position Rankings',
    fm_fit: 'fit',
    fm_footer: 'Data from Football Manager via FMInside',
    fm_left_foot: 'Left foot',
    fm_right_foot: 'Right foot',
    // FM Tiers
    fm_tier_world_class: 'World Class',
    fm_tier_elite: 'Elite',
    fm_tier_top_league: 'Top League',
    fm_tier_solid_pro: 'Solid Pro',
    fm_tier_lower_league: 'Lower League',
    fm_tier_prospect: 'Prospect',
    // FM Dimensions
    fm_dim_technical: 'Technical',
    fm_dim_mental: 'Mental',
    fm_dim_physical: 'Physical',
    fm_dim_set_pieces: 'Set Pieces',
    fm_dim_attacking: 'Attacking',
    fm_dim_defending: 'Defending',
    fm_dim_creative: 'Creative',
    fm_dim_aerial: 'Aerial',
    fm_dim_pace_power: 'Pace & Power',
    fm_dim_work_ethic: 'Work Ethic',
    // FM Positions
    fm_pos_ST: 'Striker',
    fm_pos_LW: 'Left Wing',
    fm_pos_RW: 'Right Wing',
    fm_pos_AM: 'Att. Mid',
    fm_pos_LM: 'Left Mid',
    fm_pos_RM: 'Right Mid',
    fm_pos_CM: 'Central Mid',
    fm_pos_DM: 'Def. Mid',
    fm_pos_LB: 'Left Back',
    fm_pos_RB: 'Right Back',
    fm_pos_CB: 'Center Back',
    fm_pos_GK: 'Goalkeeper',
    // FM Legend
    fm_legend_perfect: 'Perfect (85%+)',
    fm_legend_great: 'Great (72-84%)',
    fm_legend_decent: 'Decent (58-71%)',
    fm_legend_possible: 'Possible (40-57%)',
    fm_legend_poor: 'Poor',
    // FM Attributes
    fm_attr_crossing: 'Crossing',
    fm_attr_dribbling: 'Dribbling',
    fm_attr_finishing: 'Finishing',
    fm_attr_first_touch: 'First Touch',
    fm_attr_heading: 'Heading',
    fm_attr_long_shots: 'Long Shots',
    fm_attr_marking: 'Marking',
    fm_attr_passing: 'Passing',
    fm_attr_tackling: 'Tackling',
    fm_attr_technique: 'Technique',
    fm_attr_aggression: 'Aggression',
    fm_attr_anticipation: 'Anticipation',
    fm_attr_bravery: 'Bravery',
    fm_attr_composure: 'Composure',
    fm_attr_concentration: 'Concentration',
    fm_attr_decisions: 'Decisions',
    fm_attr_determination: 'Determination',
    fm_attr_flair: 'Flair',
    fm_attr_leadership: 'Leadership',
    fm_attr_off_the_ball: 'Off the Ball',
    fm_attr_positioning: 'Positioning',
    fm_attr_teamwork: 'Teamwork',
    fm_attr_vision: 'Vision',
    fm_attr_work_rate: 'Work Rate',
    fm_attr_acceleration: 'Acceleration',
    fm_attr_agility: 'Agility',
    fm_attr_balance: 'Balance',
    fm_attr_jumping_reach: 'Jumping',
    fm_attr_natural_fitness: 'Nat. Fitness',
    fm_attr_pace: 'Pace',
    fm_attr_stamina: 'Stamina',
    fm_attr_strength: 'Strength',
    fm_attr_corners: 'Corners',
    fm_attr_free_kick_taking: 'Free Kicks',
    fm_attr_long_throws: 'Long Throws',
    fm_attr_penalty_taking: 'Penalties',
  },
  he: {
    greeting_morning: 'בוקר טוב',
    greeting_afternoon: 'צהריים טובים',
    greeting_evening: 'ערב טוב',
    agent: 'סוכן',
    dashboard: 'לוח בקרה',
    players: 'שחקנים',
    contacts: 'אנשי קשר',
    requests: 'בקשות',
    tasks: 'משימות',
    shortlist: 'רשימת מעקב',
    releases: 'שחרורים',
    add_player: 'הוסף שחקן',
    activity_this_week: 'פעילות השבוע',
    event_types_this_week: 'סוגי אירועים השבוע',
    staff_tasks: 'צוות ומשימות',
    top_agents_this_week: 'סוכנים מובילים השבוע',
    leading_agencies_title: 'סוכנויות מובילות',
    leading_agencies_in_contact: 'בקשר',
    leading_agencies_players: 'שחקנים',
    leading_agencies_empty: 'אין עדיין סוכנויות עם שחקנים. הוסף אנשי קשר מסוכנויות וקשר שחקנים לסוכנויות שלהם.',
    events: 'אירועים',
    no_agent_activity: 'אין פעילות סוכנים השבוע',
    recent_activity: 'פעילות אחרונה',
    no_recent_activity: 'אין פעילות. הוסף שחקן כדי להתחיל.',
    loading_feed: 'טוען...',
    pending: 'ממתין',
    no_staff_data: 'אין נתוני צוות',
    no_events_this_week: 'אין אירועים השבוע',
    market_value_change: 'שינוי שווי שוק',
    club_change: 'חילוף מועדון',
    contract_expiring: 'חוזה מסתיים',
    note_added: 'הערה נוספה',
    player_added: 'שחקן נוסף',
    free_agent: 'שחקן חופשי',
    mandate_expired: 'מנדט פג תוקף',
    mandate_uploaded: 'מנדט הועלה',
    shortlist_added: 'נוסף לרשימת מעקב',
    shortlist_removed: 'הוסר מרשימת מעקב',
    request_added: 'בקשה נוספה',
    request_deleted: 'בקשה נמחקה',
    player_offered: 'שחקן הוצע',
    new_release_from_club: 'שחרור חדש ממועדון',
    player_deleted: 'שחקן הוסר',
    note_deleted: 'הערה נמחקה',
    mandate_switched_on: 'מנדט הופעל',
    mandate_switched_off: 'מנדט בוטל',
    unassigned: 'ללא שיוך',
    just_now: 'עכשיו',
    minutes_ago: 'דק׳',
    hours_ago: 'ש׳',
    by: 'על ידי',
    loading: 'טוען...',
    sign_out: 'התנתק',
    nav_dashboard: 'לוח בקרה',
    nav_tasks: 'משימות',
    nav_players: 'שחקנים',
    nav_add_player: 'הוסף שחקן',
    nav_shortlist: 'רשימת מעקב',
    nav_ai_scout: 'AI סקאוט',
    nav_find_next: 'מצא את הבא',
    nav_contacts: 'אנשי קשר',
    nav_releases: 'שחרורים',
    nav_returnee: 'חזרו מהשאלה',
    nav_requests: 'דרישות מועדונים',
    tasks_title: 'משימות',
    tasks_filter_pending: 'ממתין',
    tasks_filter_done: 'הושלם',
    tasks_filter_all: 'הכל',
    tasks_loading: 'טוען משימות...',
    tasks_empty: 'אין משימות עדיין',
    tasks_empty_hint: 'הוסף את המשימה הראשונה שלך',
    tasks_add: 'הוסף משימה',
    tasks_new_task: 'משימה חדשה',
    tasks_what_needs_done: 'מה צריך לעשות?',
    tasks_assign_to: 'הקצה ל',
    tasks_priority: 'עדיפות',
    tasks_priority_low: 'נמוכה',
    tasks_priority_medium: 'בינונית',
    tasks_priority_high: 'גבוהה',
    tasks_due_date: 'תאריך יעד',
    tasks_notes_hint: 'הוסף הערות (אופציונלי)',
    tasks_create: 'צור משימה',
    tasks_edit: 'ערוך',
    tasks_delete: 'מחק',
    tasks_delete_confirm: 'למחוק את המשימה?',
    tasks_save: 'שמור',
    tasks_cancel: 'ביטול',
    tasks_due_today: 'היום',
    tasks_due_tomorrow: 'מחר',
    tasks_overdue: 'באיחור',
    tasks_no_date: 'ללא תאריך',
    tasks_completed: 'הושלם',
    tasks_all_agents: 'כל הסוכנים',
    tasks_my_tasks: 'המשימות שלי',
    tasks_overdue_count: 'באיחור',
    tasks_agents: 'סוכנים',
    tasks_due_today_count: 'להיום',
    tasks_completed_count: 'הושלמו',
    tasks_section_overdue: 'באיחור',
    tasks_section_today: 'היום',
    tasks_section_tomorrow: 'מחר',
    tasks_section_this_week: 'השבוע',
    tasks_section_later: 'מאוחר יותר',
    tasks_section_no_date: 'ללא תאריך',
    tasks_section_completed: 'הושלמו',
    tasks_progress: 'התקדמות',
    player_tasks_section: 'משימות קשורות לשחקן',
    player_tasks_add: 'הוסף משימה',
    player_tasks_empty: 'אין עדיין משימות לשחקן זה',
    player_tasks_choose_template: 'בחר טמפלט (מומלץ)',
    player_tasks_created_by: 'נוצר ע״י',
    players_title: 'הסגל שלנו',
    players_add: 'הוסף שחקן',
    players_loading: 'טוען שחקנים...',
    players_empty: 'אין שחקנים עדיין',
    players_empty_hint: 'הוסף את השחקן הראשון לבניית הסגל',
    players_total: 'סה״כ',
    players_value: 'שווי',
    players_club: 'מועדון',
    players_age: 'שנים',
    players_age_display: 'בן {age}',
    shortlist_title: 'רשימת מעקב',
    shortlist_loading: 'טוען רשימת מעקב...',
    shortlist_empty: 'רשימת המעקב ריקה',
    shortlist_empty_hint: 'עיין בשחרורים או הוסף מ-Transfermarkt',
    shortlist_browse_releases: 'עיין בשחרורים',
    shortlist_browse_returnees: 'עיין בחזר מהשאלה',
    shortlist_add_from_tm: 'הוסף מ-Transfermarkt',
    shortlist_remove: 'הסר',
    shortlist_add: 'הוסף לרשימת מעקב',
    shortlist_adding: 'מוסיף...',
    shortlist_added_by: 'נוסף על ידי',
    shortlist_added_today: 'נוסף היום',
    shortlist_added_yesterday: 'נוסף אתמול',
    shortlist_added_days_ago: 'נוסף לפני {n} ימים',
    shortlist_added_week_ago: 'נוסף לפני שבוע',
    shortlist_added_weeks_ago: 'נוסף לפני {n} שבועות',
    shortlist_added_months_ago: 'נוסף לפני {n} חודשים',
    shortlist_player_in_roster: 'השחקן כבר בסגל',
    contacts_title: 'אנשי קשר',
    contacts_all: 'הכל',
    contacts_clubs: 'מועדונים',
    contacts_agencies: 'סוכנויות',
    contacts_loading: 'טוען אנשי קשר...',
    contacts_empty: 'אין אנשי קשר עדיין',
    contacts_contact: 'איש קשר',
    transfer_windows_title: 'חלונות העברה פתוחים',
    transfer_windows_days_left: '{n} ימים נותרו',
    transfer_windows_today: 'היום',
    transfer_windows_open: 'פתוח',
    transfer_windows_empty: 'אין חלונות העברה פתוחים כרגע.',
    transfer_windows_closing_soon: '{n} נסגרים בקרוב',
    transfer_windows_group_priority: 'שווקים עיקריים',
    transfer_windows_group_uefa: 'אירופה (UEFA)',
    transfer_windows_group_conmebol: 'דרום אמריקה (CONMEBOL)',
    transfer_windows_group_concacaf: 'צפון ומרכז אמריקה (CONCACAF)',
    transfer_windows_group_afc: 'אסיה (AFC)',
    transfer_windows_group_caf: 'אפריקה (CAF)',
    transfer_windows_group_ofc: 'אוקיאניה (OFC)',
    releases_title: 'שחרורים אחרונים',
    releases_loading: 'טוען שחרורים...',
    releases_empty: 'אין שחרורים בטווח זה',
    releases_try_filter: 'נסה טווח שווי אחר',
    releases_all: 'הכל',
    releases_add: 'הוסף',
    releases_free_agent: 'שחקן חופשי',
    releases_progress: 'עמוד {page} • {total} שחקנים',
    releases_progress_ranges: 'טווח {range}/{totalRanges} • {total} שחקנים',
    releases_position: 'עמדה',
    releases_age: 'גיל',
    releases_age_all: 'כל הגילאים',
    releases_age_u23: 'מתחת ל-23',
    releases_age_23_30: '23-30',
    releases_age_30plus: '30+',
    releases_search: 'חפש לפי שם...',
    releases_stats_total: 'סה״כ',
    releases_stats_showing: 'מוצג',
    releases_sort: 'מיון לפי',
    releases_sort_value: 'שווי שוק',
    releases_sort_date: 'תאריך שחרור',
    releases_sort_age: 'גיל',
    releases_value_filter: 'טווח שווי',
    releases_reload: 'טען מחדש',
    releases_roster_teammates: '{count} שחקן מהמאגר שיחק איתו',
    releases_roster_teammates_tap: 'שחקנים מהמאגר ששיחקו איתו',
    releases_no_roster_teammates: 'אין שחקנים מהמאגר ששיחקו עם שחקן זה',
    releases_roster_teammates_loading: 'טוען שחקנים…',
    releases_games_together: '{n} משחקים ביחד',
    releases_bookmark: 'שמור',
    releases_saved: 'נשמר',
    releases_view_shortlist: 'צפה ברשימה',
    releases_stat_shortlisted: 'נשמרו',
    returnee_title: 'חזרו מהשאלה',
    returnee_subtitle: 'שחקנים שחוזרים מהשאלה בליגות אירופאיות',
    returnee_no_found: 'לא נמצאו שחקנים שחזרו',
    returnee_loading: 'טוען ({loaded}/{total} ליגות)…',
    returnee_stat_leagues: 'ליגות',
    returnee_all_count: 'הכל {count}',
    returnee_badge_loan_return: 'חזר מהשאלה',
    returnee_badge_returned_on: 'חזר ב-{date}',
    returnee_clear_filters: 'נקה סינון',
    returnee_current_club: 'מועדון נוכחי',
    returnee_returned: 'חזר',
    returnee_market_value: 'שווי שוק',
    requests_title: 'בקשות מועדונים',
    requests_subtitle: 'בקשות שחקנים ממועדונים לפי עמדה',
    ai_scout_title: 'מצא את ההחתמה הבאה שלך',
    ai_scout_subtitle: 'תאר את השחקן שאתה צריך בשפה חופשית. ה-AI מחפש באלפי פרופילים כדי למצוא את ההתאמות הטובות ביותר.',
    ai_scout_placeholder: 'למשל: מצא לי 20 חלוצים עד גיל 26 שהם מהירים מאוד עם לפחות 5 שערים בעונה שעברה',
    ai_scout_search: 'חפש',
    ai_scout_searching: 'מחפש…',
    ai_scout_searching_hint: 'בדרך כלל 10–20 שניות',
    ai_scout_local_testing: 'הוסף GEMINI_API_KEY ל-.env.local לניתוח AI. בלעדיו מוצגות תוצאות מדומות.',
    ai_scout_examples: 'דוגמאות לחיפוש:',
    ai_scout_results_count: '{count} תוצאות',
    ai_scout_results_of: '{count} מתוך {total} תוצאות',
    ai_scout_no_results: 'אין תוצאות. נסה חיפוש אחר.',
    ai_scout_interpretation: 'איך ה-AI הבין את הבקשה:',
    requests_loading: 'טוען בקשות...',
    requests_empty: 'אין בקשות מועדונים',
    requests_contact: 'איש קשר',
    requests_add: 'הוסף בקשה',
    requests_delete: 'מחק',
    requests_delete_confirm: 'למחוק בקשה עבור {club} ({position})?',
    requests_stat_total: 'סה״כ',
    requests_stat_positions: 'עמדות',
    requests_country_club_one: 'מועדון 1',
    requests_country_clubs: '{count} מועדונים',
    requests_notes_label: 'הערות',
    requests_phone: 'טלפון',
    requests_salary: 'שכר',
    requests_fee: 'דמי העברה',
    requests_fee_free_loan: 'חופשי / השאלה בחינם',
    requests_age_range: 'גיל',
    requests_foot: 'רגל',
    requests_add_title: 'הוסף בקשה',
    requests_search_club: 'חפש מועדון…',
    requests_search_for_club: 'חפש מועדון',
    requests_change_club: 'שנה',
    requests_label_position: 'עמדה',
    requests_label_requirements: 'דרישות',
    requests_label_notes: 'הערות',
    requests_age_doesnt_matter: 'לא משנה',
    requests_min: 'מינ',
    requests_max: 'מקס',
    requests_label_salary: 'טווח משכורת',
    requests_label_fee: 'דמי העברה',
    requests_label_foot: 'רגל דומיננטית',
    requests_foot_left: 'שמאל',
    requests_foot_right: 'ימין',
    requests_foot_any: 'לא משנה',
    requests_notes_placeholder: 'הערות נוספות…',
    requests_save: 'שמור בקשה',
    requests_next: 'הבא',
    requests_step_club: 'מועדון',
    requests_step_position: 'עמדה',
    requests_step_requirements: 'דרישות',
    requests_step_notes: 'הערות',
    requests_matching_players_one: '{count} שחקן תואם',
    requests_matching_players: '{count} שחקנים תואמים במאגר',
    requests_no_match: 'אין שחקנים במאגר התואמים לבקשה זו',
    requests_find_players_online: 'מצא שחקנים באמצעות AI Scout',
    requests_online_players_loading: 'AI Scout מחפש…',
    requests_online_players_empty: 'לא נמצאו שחקנים תואמים ברשת',
    requests_online_match_score: 'התאמה: {pct}%',
    add_player_title: 'הוסף שחקן',
    add_to_shortlist_title: 'הוסף לרשימת מעקב',
    add_player_back: 'חזרה ל',
    add_player_paste_url: 'הדבק קישור Transfermarkt',
    add_player_load: 'טען',
    add_player_loading: 'טוען...',
    add_player_search: 'או חפש לפי שם',
    add_player_search_btn: 'חפש',
    add_player_searching: 'מחפש...',
    add_player_confirm: 'אישור והוספה',
    add_player_to_roster: 'הוסף לסגל',
    add_player_saving: 'שומר...',
    add_player_placeholder_url: 'https://www.transfermarkt.com/...',
    add_player_placeholder_search: 'שם שחקן...',
    add_player_auto_search_hint: 'תוצאות מופיעות בזמן הקלדה',
    add_player_no_results: 'לא נמצאו שחקנים. נסה שם אחר.',
    add_player_from_shortlist_hint: 'הוסף שחקן זה מרשימת המעקב לסגל שלך',
    add_player_shortlist_hint: 'הוסף שחקן זה לרשימת המעקב להמשך',
    add_player_roster_hint: 'הוסף שחקן חדש לסגל שלך',
    add_player_contact_section: 'איש קשר (אופציונלי)',
    player_info_back: 'חזרה לשחקנים',
    player_info_back_players: 'חזרה לשחקנים',
    player_info_back_requests: 'חזרה לבקשות',
    player_info_back_releases: 'חזרה לשחרורים',
    player_info_back_contract_finisher: 'חזרה למסיימי חוזה',
    player_info_back_shadow_teams: 'חזרה לקבוצת צללים',
    player_info_back_tasks: 'חזרה למשימות',
    player_info_notes: 'הערות',
    player_info_no_notes: 'אין הערות עדיין',
    player_info_add_note: 'הוסף הערה',
    player_info_edit_note: 'ערוך הערה',
    player_info_delete_note: 'מחק הערה',
    player_info_delete_note_confirm: 'האם אתה בטוח שברצונך למחוק את ההערה?',
    player_info_note_placeholder: 'הוסף הערה חדשה…',
    player_info_note_save: 'שמור',
    player_info_note_cancel: 'ביטול',
    player_info_agent: 'סוכן',
    player_info_age: 'גיל',
    player_info_height: 'גובה',
    player_info_contract: 'חוזה',
    player_info_not_found: 'שחקן לא נמצא',
    player_info_overview: 'סקירה',
    player_info_stats: 'סטטיסטיקות',
    player_info_club: 'מועדון נוכחי',
    player_info_contact: 'איש קשר',
    player_info_mandate: 'מנדט',
    player_info_documents: 'מסמכים',
    player_info_add_document: 'הוסף מסמך',
    player_info_no_documents: 'אין מסמכים עדיין',
    player_info_uploading: 'מעלה מסמך…',
    player_info_documents_empty_subtitle: 'העלה דרכונים, מנדטים, מסמכים רפואיים או קבצים אחרים.',
    player_info_delete_doc_confirm: 'האם אתה בטוח שברצונך למחוק',
    player_info_cd_open_link: 'פתח קישור',
    player_info_cd_delete_document: 'מחק מסמך',
    player_info_generate_mandate: 'יצירת מנדט',
    player_info_share: 'שתף',
    mandate_no_passport: 'אין פרטי דרכון. העלה מסמך דרכון תחילה.',
    mandate_step_agent: 'בחר סוכן',
    mandate_no_agents_fifa: 'לא נמצאו סוכנים עם רישיון פיפ״א',
    mandate_fifa_license: 'רישיון פיפ״א',
    mandate_step_validity: 'תוקף וליגות',
    mandate_expiry_date: 'תאריך תפוגה',
    mandate_valid_leagues: 'ליגות תקפות',
    mandate_search_country: 'חפש מדינה...',
    mandate_add_country_league: 'הוסף מדינה / ליגה',
    mandate_entire_country: 'כל המדינה (כל המועדונים)',
    mandate_sheet_search_clubs: 'חפש מועדונים ב-%s…',
    mandate_selected_clubs: '%d מועדון(ים) נבחרו',
    mandate_sheet_add_button: 'הוסף למנדט',
    mandate_change_country: 'שנה',
    mandate_selected: 'נבחרו',
    mandate_step_review: 'סיכום',
    mandate_review_player: 'שחקן',
    mandate_review_agent: 'סוכן',
    mandate_review_fifa_id: 'מספר רישיון פיפ״א',
    mandate_back: 'חזרה',
    mandate_next: 'הבא',
    mandate_generating: 'מייצר...',
    mandate_generate_pdf: 'יצירת PDF',
    upload_failed: 'ההעלאה נכשלה. נסה שוב.',
    passport_already_exists: 'לשחקן זה כבר יש פרטי דרכון. מחק תחילה את מסמך הדרכון הקיים.',
    player_info_value_history: 'היסטוריית שווי',
    player_info_foot: 'רגל מועדפת',
    player_info_on_loan: 'בהשאלה מ',
    player_info_salary: 'טווח משכורת',
    player_info_transfer_fee: 'דמי העברה',
    player_info_agency: 'סוכנות',
    player_info_view_on_tm: 'צפה ב-Transfermarkt',
    player_info_refresh: 'רענן נתונים',
    similar_players_title: 'שחקנים דומים',
    similar_players_find: 'מצא שחקנים דומים',
    similar_players_searching: 'מחפש שחקנים דומים…',
    similar_players_match: 'התאמה',
    similar_players_style: 'סגנון',
    similar_players_nationality: 'לאום',
    similar_players_league: 'ליגה',
    similar_players_height: 'גובה',
    similar_players_foot: 'רגל',
    similar_players_contract: 'חוזה',
    similar_players_view_profile: 'צפה ב-Transfermarkt',
    similar_players_load_more: 'טען עוד שחקנים דומים',
    similar_players_retry: 'נסה שוב',
    similar_players_empty: 'לא נמצאו שחקנים דומים',
    similar_players_per90: 'ל-90 דקות',
    similar_players_growth: 'צמיחה',
    similar_players_club: 'מועדון',
    similar_players_sources_hint: 'הניתוח משלב נתוני Transfermarkt, סטטיסטיקות FBref ונתוני FM',
    player_info_mandate_active: 'פעיל',
    player_info_mandate_inactive: 'לא פעיל',
    player_info_mandate_expires: 'תוקף מנדט: %s',
    player_info_doc_expired: 'פג תוקף',
    player_info_nationality: 'לאום',
    player_info_foot_left: 'שמאל',
    player_info_foot_right: 'ימין',
    player_info_foot_both: 'שתיהן',
    player_info_added_by: 'נוסף על ידי',
    player_info_agent_phone: 'טלפון סוכן',
    player_info_player_phone: 'טלפון שחקן',
    note_written_by: 'נכתב על ידי',
    login_title: 'MGSR Team',
    login_subtitle: 'התחבר לחשבון שלך',
    login_email: 'אימייל',
    login_password: 'סיסמה',
    login_sign_in: 'התחבר',
    login_signing_in: 'מתחבר...',
    login_hint: 'השתמש באותם פרטי התחברות כמו באפליקציית האנדרואיד',
    common_or: 'או',
    common_years: 'שנים',
    search_no_results: 'לא נמצאו תוצאות',
    search_placeholder: 'חפש לפי שם, עמדה או מועדון...',
    contact_type_club: 'מועדון',
    contact_type_agency: 'סוכנות',
    contact_role_other: 'אחר',
    contact_role_coach: 'מאמן',
    contact_role_asst_coach: 'מאמן משנה',
    contact_role_sport_dir: 'מנהל ספורט',
    contact_role_board: 'דירקטוריון',
    contact_role_ceo: 'מנכ"ל',
    contact_role_president: 'נשיא',
    contact_role_scout: 'סקאוט / אנליסט',
    contact_role_agent: 'סוכן',
    contact_role_intermediary: 'מתווך',
    contact_role_agency_dir: 'מנהל סוכנות',
    no_club: 'ללא מועדון',
    nav_shadow_teams: 'קבוצת צללים',
    nav_contract_finisher: 'מסיימי חוזה',
    contract_finisher_title: 'מסיימי חוזה',
    contract_finisher_subtitle_summer: 'חוזים שמסתיימים לקראת חלון קיץ',
    contract_finisher_subtitle_winter: 'חוזים שמסתיימים לקראת חלון חורף',
    contract_finisher_loading: 'טוען…',
    contract_finisher_loading_more: 'טוען עוד…',
    contract_finisher_retry: 'נסה שוב',
    contract_finisher_badge: 'תאריך סיום חוזה',
    contract_finisher_no_found: 'לא נמצאו מסיימי חוזה בטווח זה',
    contract_finisher_no_match_filters: 'אין שחקנים התואמים את הסינון',
    contract_finisher_clear_filters: 'נקה סינון',
    contract_finisher_apply_filters: 'החל סינון',
    contract_finisher_filter_age_all: 'הכל',
    contract_finisher_filter_age_18_21: '18-21',
    contract_finisher_filter_age_22_25: '22-25',
    contract_finisher_filter_age_26_29: '26-29',
    contract_finisher_filter_age_30_plus: '30+',
    contract_finisher_filter_value_all: 'הכל',
    contract_finisher_filter_value_150k_500k: '€150K–500K',
    contract_finisher_filter_value_500k_1m: '€500K–1M',
    contract_finisher_filter_value_1m_2m: '€1M–2M',
    contract_finisher_filter_value_2m_3m: '€2M–3M',
    contract_finisher_filter_label_value: 'שווי',
    contract_finisher_filter_label_position: 'עמדה',
    contract_finisher_filter_label_age: 'גיל',
    contract_finisher_filter_label_region: 'אזור',
    contract_finisher_stats_total: 'סה״כ',
    contract_finisher_stats_shortlisted: 'ברשימה',
    contract_finisher_stats_visible: 'מוצג',
    contract_finisher_filters: 'סינון',
    roster_analytics_title: 'ניתוח סגל',
    roster_analytics_position: 'לפי עמדה',
    roster_analytics_age: 'לפי גיל',
    roster_analytics_value: 'לפי שווי שוק',
    roster_analytics_contracts: 'חוזים מסתיימים',
    roster_analytics_mandates: 'סטטוס מנדט',
    roster_analytics_with_mandate: 'עם מנדט',
    roster_analytics_without_mandate: 'ללא מנדט',
    roster_analytics_age_u21: 'מתחת ל-21',
    roster_analytics_age_22_25: '22-25',
    roster_analytics_age_26_29: '26-29',
    roster_analytics_age_30_plus: '30+',
    roster_analytics_value_unknown: 'לא ידוע',
    roster_analytics_value_0_500k: '0-500K',
    roster_analytics_value_500k_1m: '500K-1M',
    roster_analytics_value_1m_5m: '1M-5M',
    roster_analytics_value_5m_plus: '5M+',
    players_filter_free_agents: 'שחקנים חופשיים',
    players_filter_contract_expiring: 'חוזה מסתיים',
    players_filter_with_mandate: 'עם מנדט',
    players_filter_my_players_only: 'השחקנים שלי בלבד',
    players_filter_loan_players_only: 'שחקנים בהשאלה בלבד',
    players_filter_without_registered_agent: 'ללא סוכן רשום',
    players_filter_with_notes: 'עם הערות',
    players_filter_foot_left: 'רגל שמאל',
    players_filter_foot_right: 'רגל ימין',
    players_filter_position_gk: 'שוערים',
    players_filter_position_def: 'הגנה',
    players_filter_position_mid: 'קישור',
    players_filter_position_fwd: 'התקפה',
    players_filter_clear: 'נקה מסננים',
    shadow_teams_title: 'קבוצת צללים',
    shadow_teams_subtitle: 'השחקנים המועדפים שלך לחלון ההעברות הבא',
    shadow_teams_formation: 'מערך',
    shadow_teams_hint: 'החלף טאבים לראות את הקבוצות • הטאב שלך: הוסף, ערוך, הסר • אחרים: צפייה בפרופיל בלבד',
    shadow_teams_bench: 'ספסל',
    shadow_teams_select_player: 'בחר שחקן',
    shadow_teams_search_player: 'חפש שחקן',
    shadow_teams_no_players: 'לא נמצאו שחקנים לעמדה זו',
    shadow_teams_cancel: 'ביטול',
    shadow_teams_view_player: 'צפה בפרופיל',
    shadow_teams_change_player: 'החלף שחקן',
    shadow_teams_remove_player: 'הסר',
    shadow_teams_you: 'אתה',
    // Player Highlights
    highlights_title: 'הדגשות וידאו',
    highlights_loading: 'טוען הדגשות...',
    highlights_empty: 'לא נמצאו סרטוני הדגשות לשחקן זה',
    highlights_recent_matches: 'הדגשות משחקים אחרונים',
    highlights_compilations: 'הדגשות שחקן',
    highlights_powered_by: 'מבוסס על YouTube ו-Scorebat',
    highlights_updated: 'עודכן',
    highlights_views: 'צפיות',
    // FM Intelligence Panel
    fm_tab_intelligence: 'תובנות FM',
    fm_tab_position_fit: 'התאמת עמדה',
    fm_loading: 'טוען תובנות FM...',
    fm_current_ability: 'יכולת נוכחית',
    fm_pa_label: 'יכולת פוטנציאלית',
    fm_potential: 'פוטנציאל',
    fm_at_peak: 'בשיא',
    fm_best_fit: 'התאמה מיטבית:',
    fm_ability_dimensions: 'ממדי יכולת',
    fm_top_attributes: 'תכונות חזקות',
    fm_weaknesses: 'חולשות',
    fm_no_weaknesses: 'אין חולשות משמעותיות',
    fm_position_rankings: 'דירוג עמדות',
    fm_fit: 'התאמה',
    fm_footer: 'נתונים מ-Football Manager דרך FMInside',
    fm_left_foot: 'רגל שמאל',
    fm_right_foot: 'רגל ימין',
    // FM Tiers
    fm_tier_world_class: 'ברמה עולמית',
    fm_tier_elite: 'עילית',
    fm_tier_top_league: 'ליגה עליונה',
    fm_tier_solid_pro: 'מקצוען מוצק',
    fm_tier_lower_league: 'ליגה נמוכה',
    fm_tier_prospect: 'כשרון צעיר',
    // FM Dimensions
    fm_dim_technical: 'טכני',
    fm_dim_mental: 'מנטלי',
    fm_dim_physical: 'פיזי',
    fm_dim_set_pieces: 'כדורים עומדים',
    fm_dim_attacking: 'התקפי',
    fm_dim_defending: 'הגנתי',
    fm_dim_creative: 'יצירתי',
    fm_dim_aerial: 'אווירי',
    fm_dim_pace_power: 'מהירות וכוח',
    fm_dim_work_ethic: 'אתיקת עבודה',
    // FM Positions
    fm_pos_ST: 'חלוץ',
    fm_pos_LW: 'כנף שמאל',
    fm_pos_RW: 'כנף ימין',
    fm_pos_AM: 'קישור התקפי',
    fm_pos_LM: 'קשר שמאל',
    fm_pos_RM: 'קשר ימין',
    fm_pos_CM: 'קשר מרכזי',
    fm_pos_DM: 'קשר הגנתי',
    fm_pos_LB: 'מגן שמאל',
    fm_pos_RB: 'מגן ימין',
    fm_pos_CB: 'בלם',
    fm_pos_GK: 'שוער',
    // FM Legend
    fm_legend_perfect: 'מושלם (85%+)',
    fm_legend_great: 'מעולה (72-84%)',
    fm_legend_decent: 'סביר (58-71%)',
    fm_legend_possible: 'אפשרי (40-57%)',
    fm_legend_poor: 'חלש',
    // FM Attributes
    fm_attr_crossing: 'הרמות',
    fm_attr_dribbling: 'כדרור',
    fm_attr_finishing: 'סיום',
    fm_attr_first_touch: 'נגיעה ראשונה',
    fm_attr_heading: 'נגיחות',
    fm_attr_long_shots: 'בעיטות רחוקות',
    fm_attr_marking: 'סימון',
    fm_attr_passing: 'מסירות',
    fm_attr_tackling: 'תיקולים',
    fm_attr_technique: 'טכניקה',
    fm_attr_aggression: 'תוקפנות',
    fm_attr_anticipation: 'צפייה מראש',
    fm_attr_bravery: 'אומץ',
    fm_attr_composure: 'קור רוח',
    fm_attr_concentration: 'ריכוז',
    fm_attr_decisions: 'קבלת החלטות',
    fm_attr_determination: 'נחישות',
    fm_attr_flair: 'יצירתיות',
    fm_attr_leadership: 'מנהיגות',
    fm_attr_off_the_ball: 'תנועה ללא כדור',
    fm_attr_positioning: 'מיקום',
    fm_attr_teamwork: 'עבודת צוות',
    fm_attr_vision: 'ראייה',
    fm_attr_work_rate: 'קצב עבודה',
    fm_attr_acceleration: 'תאוצה',
    fm_attr_agility: 'זריזות',
    fm_attr_balance: 'שיווי משקל',
    fm_attr_jumping_reach: 'קפיצה',
    fm_attr_natural_fitness: 'כושר טבעי',
    fm_attr_pace: 'מהירות',
    fm_attr_stamina: 'סיבולת',
    fm_attr_strength: 'כוח',
    fm_attr_corners: 'קרנות',
    fm_attr_free_kick_taking: 'בעיטות חופשיות',
    fm_attr_long_throws: 'זריקות רחוקות',
    fm_attr_penalty_taking: 'פנדלים',
  },
};

const TYPE_KEYS: Record<string, string> = {
  MARKET_VALUE_CHANGE: 'market_value_change',
  CLUB_CHANGE: 'club_change',
  CONTRACT_EXPIRING: 'contract_expiring',
  NOTE_ADDED: 'note_added',
  NOTE_DELETED: 'note_deleted',
  PLAYER_ADDED: 'player_added',
  PLAYER_DELETED: 'player_deleted',
  BECAME_FREE_AGENT: 'free_agent',
  NEW_RELEASE_FROM_CLUB: 'new_release_from_club',
  MANDATE_EXPIRED: 'mandate_expired',
  MANDATE_UPLOADED: 'mandate_uploaded',
  MANDATE_SWITCHED_ON: 'mandate_switched_on',
  MANDATE_SWITCHED_OFF: 'mandate_switched_off',
  SHORTLIST_ADDED: 'shortlist_added',
  SHORTLIST_REMOVED: 'shortlist_removed',
  REQUEST_ADDED: 'request_added',
  REQUEST_DELETED: 'request_deleted',
  PLAYER_OFFERED_TO_CLUB: 'player_offered',
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem('mgsr-lang') as Lang | null;
    if (stored === 'he' || stored === 'en') setLangState(stored);
    setMounted(true);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (mounted) localStorage.setItem('mgsr-lang', l);
  };

  const value: LanguageContextValue = {
    lang,
    setLang,
    t: (k) => TRANSLATIONS[lang][k] ?? k,
    isRtl: lang === 'he',
  };

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export function translateType(type: string, t: (k: string) => string): string {
  const key = TYPE_KEYS[type];
  return key ? t(key) : type;
}
