'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'en' | 'he';

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    agent: 'Agent',
    dashboard: 'Dashboard',
    players: 'Players',
    players_women: 'Players',
    player_women: 'Player',
    contacts: 'Contacts',
    requests: 'Requests',
    tasks: 'Tasks',
    shortlist: 'Shortlist',
    releases: 'Releases',
    add_player: 'Add Player',
    activity_this_week: 'Activity this week',
    event_types_this_week: 'Event types this week',
    staff_tasks: 'Staff & tasks',
    top_agents_this_week: 'Top agents this week',
    leading_agencies_title: 'Leading Agencies',
    leading_agencies_in_contact: 'In contact',
    leading_agencies_players: 'players',
    leading_agencies_empty: 'No agencies with players yet. Add agency contacts and link players to their agencies.',
    events: 'events',
    no_agent_activity: 'No agent activity this week',
    recent_activity: 'Recent activity',
    no_recent_activity: 'No recent activity. Add a player to get started.',
    no_recent_activity_women: 'No recent activity. Add an athlete to get started.',
    loading_feed: 'Loading feed...',
    pending: 'pending',
    no_staff_data: 'No staff data',
    no_events_this_week: 'No events this week',
    market_value_change: 'Market value change',
    club_change: 'Club change',
    contract_expiring: 'Contract expiring',
    note_added: 'Note added',
    player_added: 'Player added',
    player_added_women: 'Player added',
    player_added_youth: 'Player added',
    free_agent: 'Free agent',
    free_agent_women: 'Free agent',
    mandate_expired: 'Mandate expired',
    mandate_uploaded: 'Mandate uploaded',
    shortlist_added: 'Shortlist added',
    shortlist_removed: 'Shortlist removed',
    request_added: 'Request added',
    request_deleted: 'Request deleted',
    player_offered: 'Player offered',
    player_offered_women: 'Player offered',
    new_release_from_club: 'New release from club',
    player_deleted: 'Player removed',
    player_deleted_women: 'Player removed',
    note_deleted: 'Note removed',
    mandate_switched_on: 'Mandate enabled',
    mandate_switched_off: 'Mandate disabled',
    unassigned: 'Unassigned',
    just_now: 'Just now',
    minutes_ago: 'm ago',
    hours_ago: 'h ago',
    by: 'by',
    loading: 'Loading...',
    sign_out: 'Sign out',
    notif_enable: 'Enable Notifications',
    notif_enable_desc: 'Get notified when tasks are assigned to you and when player updates happen.',
    notif_enabled: 'Notifications enabled',
    notif_blocked: 'Notifications blocked — enable in browser settings',
    notif_enable_btn: 'Enable',
    notif_cancel_btn: 'Cancel',
    notif_prompt_title: 'Stay in the loop',
    notif_prompt_desc: 'Enable push notifications to get real-time alerts for new tasks, player updates, and important feed events — even when the browser is in the background.',
    notif_prompt_enable: 'Enable Notifications',
    notif_prompt_later: 'Maybe later',
    nav_more: 'More',
    filters: 'Filters',
    apply: 'Apply',
    nav_dashboard: 'Dashboard',
    nav_tasks: 'Tasks',
    nav_players: 'Players',
    nav_players_women: 'Players',
    nav_players_youth: 'Youth Players',
    nav_add_player: 'Add Player',
    nav_shortlist: 'Shortlist',
    nav_ai_scout: 'AI Scout',
    nav_war_room: 'War Room',
    rec_sign: 'Sign',
    rec_monitor: 'Monitor',
    rec_pass: 'Pass',
    nav_find_next: 'Find Next',
    nav_contacts: 'Contacts',
    nav_releases: 'Releases',
    nav_returnee: 'Returnees',
    nav_requests: 'Club Requirements',
    tasks_title: 'Tasks',
    tasks_filter_pending: 'Pending',
    tasks_filter_done: 'Done',
    tasks_filter_all: 'All',
    tasks_loading: 'Loading tasks...',
    tasks_empty: 'No tasks yet',
    tasks_empty_hint: 'Add your first task to get started',
    tasks_add: 'Add Task',
    tasks_new_task: 'New Task',
    tasks_new_task_women: 'New action item',
    tasks_what_needs_done: 'What needs to be done?',
    tasks_assign_to: 'Assign to',
    tasks_priority: 'Priority',
    tasks_priority_low: 'Low',
    tasks_priority_medium: 'Medium',
    tasks_priority_high: 'High',
    tasks_due_date: 'Due date',
    tasks_notes_hint: 'Add notes (optional)',
    tasks_create: 'Create Task',
    tasks_edit: 'Edit',
    tasks_delete: 'Delete',
    tasks_delete_confirm: 'Delete this task?',
    tasks_save: 'Save',
    tasks_cancel: 'Cancel',
    tasks_due_today: 'Today',
    tasks_due_tomorrow: 'Tomorrow',
    tasks_overdue: 'Overdue',
    tasks_no_date: 'No date',
    tasks_completed: 'completed',
    tasks_all_agents: 'All agents',
    tasks_my_tasks: 'My tasks',
    tasks_overdue_count: 'Overdue',
    tasks_agents: 'agents',
    tasks_due_today_count: 'Due today',
    tasks_completed_count: 'completed',
    tasks_section_overdue: 'Overdue',
    tasks_section_today: 'Today',
    tasks_section_tomorrow: 'Tomorrow',
    tasks_section_this_week: 'This week',
    tasks_section_later: 'Later',
    tasks_section_no_date: 'No due date',
    tasks_section_completed: 'Completed',
    tasks_tab_active: 'Active',
    tasks_no_active: 'No active tasks',
    tasks_no_completed: 'No completed tasks',
    tasks_progress: 'progress',
    tasks_title_women: 'Action Items',
    tasks_empty_women: 'No action items yet',
    tasks_empty_hint_women: 'Add your first item to track athlete follow-ups',
    tasks_add_women: 'Add Item',
    tasks_my_tasks_women: 'My to-dos',
    tasks_all_agents_women: 'Team view',
    player_tasks_section: 'Player-related tasks',
    player_tasks_section_women: 'Player-related tasks',
    player_tasks_add: 'Add task',
    player_tasks_add_women: 'Add action item',
    player_tasks_empty: 'No tasks for this player yet',
    player_tasks_empty_women: 'No tasks for this athlete yet',
    player_tasks_choose_template: 'Choose template (recommended)',
    player_tasks_choose_template_women: 'Choose template (recommended)',
    player_tasks_created_by: 'Created by',
    tasks_opened_by: 'Opened by',
    tasks_assigned_to_label: 'Assigned to',
    tasks_created_on: 'Created',
    tasks_due_label: 'Due',
    tasks_contact_agent: 'Contact agent',
    tasks_select_agent_contact: 'Link agent from contacts',
    tasks_linked_agent: 'Agent',
    players_title: 'Our Roster',
    players_title_women: 'Our Squad',
    players_add: 'Add Player',
    players_add_women: 'Add Player',
    players_loading: 'Loading players...',
    players_loading_women: 'Loading players...',
    players_empty: 'No players yet',
    players_empty_women: 'No players yet',
    players_empty_hint: 'Add your first player to build your roster',
    players_empty_hint_women: 'Add your first athlete to build your squad',
    players_total: 'Total',
    players_value: 'Value',
    players_club: 'Club',
    players_age: 'yrs',
    players_age_display: '{age} yrs',
    players_age_display_women: '{age} yrs',
    players_title_youth: 'Youth Players',
    players_subtitle_youth: 'youth players',
    players_add_youth: 'Add Youth Player',
    players_loading_youth: 'Loading youth players...',
    players_empty_youth: 'No youth players yet',
    players_empty_hint_youth: 'Add your first youth player to get started',
    players_search_youth: 'Search youth players...',
    shortlist_empty_hint_youth: 'Search IFA or add youth players to your shortlist',
    youth_add_title: 'Add Youth Player',
    youth_add_shortlist_title: 'Add to Youth Shortlist',
    youth_add_subtitle: 'Search IFA (football.org.il) or enter player details manually.',
    youth_add_shortlist_subtitle: 'Search IFA or enter player details for the youth shortlist.',
    youth_add_back_players: 'Back to Players',
    youth_add_back_shortlist: 'Back to Shortlist',
    youth_add_search_placeholder: 'Search IFA player… (name in Hebrew or English)',
    youth_add_searching: 'Searching IFA...',
    youth_add_no_results: 'No results found on IFA.',
    youth_add_manual: 'Add manually instead',
    youth_add_or_manual: 'add manually',
    youth_add_or_manual_hint: 'with details below.',
    youth_add_paste_url: 'Paste an IFA player page URL to auto-fill details:',
    youth_add_load: 'Load',
    youth_add_loading: 'Loading...',
    youth_add_loading_profile: 'Loading IFA profile...',
    youth_add_identity: 'Player Identity',
    youth_add_name: 'Full Name',
    youth_add_name_en: 'Full Name (English)',
    youth_add_name_he: 'Full Name (Hebrew)',
    youth_add_positions: 'Positions',
    youth_add_club_details: 'Club & Details',
    youth_add_club: 'Current Club',
    youth_add_academy: 'Academy / Division',
    youth_add_dob: 'Date of Birth',
    youth_add_age_group: 'Age Group',
    youth_add_nationality: 'Nationality',
    youth_add_ifa_profile: 'IFA Profile',
    youth_add_ifa_url: 'IFA Profile URL',
    youth_add_ifa_hint: 'Used for duplicate check and future data enrichment.',
    youth_add_photo: 'Photo',
    youth_add_find_photo: 'Find',
    youth_add_searching_photo: 'Searching...',
    youth_add_preview: 'Preview',
    youth_add_contact: 'Contact Information',
    youth_add_player_section: 'Player',
    youth_add_phone: 'Phone',
    youth_add_email: 'Email',
    youth_add_parent: 'Parent / Guardian',
    youth_add_parent_name: 'Parent Name',
    youth_add_relationship: 'Relationship',
    youth_add_parent_phone: 'Parent Phone',
    youth_add_parent_email: 'Parent Email',
    youth_add_relationship_father: 'Father',
    youth_add_relationship_mother: 'Mother',
    youth_add_relationship_guardian: 'Guardian',
    youth_add_relationship_agent: 'Agent',
    youth_add_notes: 'Notes',
    youth_add_saving: 'Saving...',
    youth_add_save_shortlist: 'Add to Youth Shortlist',
    youth_add_save_roster: 'Add to Youth Roster',
    youth_add_select: 'Select...',
    youth_detail_back_link: 'Youth Players',
    youth_detail_task_btn: '+ Task',
    youth_detail_edit: 'Edit',
    youth_detail_delete: 'Delete',
    youth_detail_mandate: 'Mandate',
    youth_detail_expires: 'Expires',
    youth_detail_contact: 'Contact',
    youth_detail_player_section: 'Player',
    youth_detail_ifa_stats: 'IFA Stats',
    youth_detail_matches: 'Matches',
    youth_detail_goals: 'Goals',
    youth_detail_assists: 'Assists',
    youth_detail_documents: 'Documents',
    youth_detail_uploading: 'Uploading...',
    youth_detail_no_documents: 'No documents yet.',
    youth_detail_upload: '+ Upload',
    youth_detail_tasks: 'Tasks',
    youth_detail_add: '+ Add',
    youth_detail_no_tasks: 'No tasks yet.',
    youth_detail_due: 'Due:',
    youth_detail_notes: 'Notes',
    youth_detail_add_note: '+ Add Note',
    youth_detail_no_notes: 'No notes yet.',
    youth_detail_agent_in_charge: 'Agent in Charge',
    youth_detail_add_note_title: 'Add Note',
    youth_detail_edit_note_title: 'Edit Note',
    youth_detail_note_placeholder: 'Write your note...',
    youth_detail_cancel: 'Cancel',
    youth_detail_saving: 'Saving...',
    youth_detail_save: 'Save',
    youth_detail_delete_note_confirm: 'Delete Note?',
    youth_detail_cannot_undo: 'This action cannot be undone.',
    youth_detail_delete_doc_confirm: 'Delete Document?',
    youth_detail_will_be_removed: 'will be removed.',
    youth_detail_delete_player_confirm: 'Delete Player?',
    youth_detail_permanently_removed: 'will be permanently removed.',
    youth_detail_deleting: 'Deleting...',
    youth_detail_edit_title: 'Edit Youth Player',
    youth_detail_profile_image: 'Profile Image URL',
    youth_detail_player_phone: 'Player Phone',
    youth_detail_player_email: 'Player Email',
    youth_detail_save_changes: 'Save Changes',
    youth_detail_expired: 'expired',
    youth_detail_ifa_profile: 'IFA Profile',
    youth_detail_not_found: 'Player not found',
    youth_detail_back_to_players: 'Back to Players',
    youth_detail_parent: 'Parent',
    youth_detail_document: 'Document',
    shortlist_title: 'Shortlist',
    shortlist_title_women: 'Shortlist',
    shortlist_loading: 'Loading shortlist...',
    shortlist_loading_women: 'Loading shortlist...',
    shortlist_empty: 'Your shortlist is empty',
    shortlist_empty_hint: 'Browse releases or add from Transfermarkt',
    shortlist_empty_women: 'Your shortlist is empty',
    shortlist_empty_hint_women: 'Search SoccerDonna to add athletes to your shortlist',
    shortlist_add_from_soccerdonna: 'Add from SoccerDonna',
    shortlist_add_to_shortlist_women: 'Add to shortlist',
    shortlist_add_hint_women: 'Search and select an athlete from SoccerDonna. No contact info needed.',
    shortlist_women_profile_url_required: 'Select a player from search or paste a SoccerDonna/FMInside URL',
    shortlist_already_added: 'Already in shortlist',
    shortlist_browse_releases: 'Browse Releases',
    shortlist_browse_returnees: 'Browse Returnees',
    shortlist_add_from_tm: 'Add from Transfermarkt',
    shortlist_add_youth_player: 'Add Youth Player',
    shortlist_remove: 'Remove',
    shortlist_unknown_player: 'Unknown player',
    shortlist_no_info: '—',
    shortlist_add: 'Add to Shortlist',
    shortlist_adding: 'Adding...',
    shortlist_added_by: 'Added by',
    shortlist_added_by_date: 'Added by {agent} · {date}',
    shortlist_date_today: 'today',
    shortlist_date_yesterday: 'yesterday',
    shortlist_date_days_ago: '{n} days ago',
    shortlist_date_week_ago: '1 week ago',
    shortlist_date_weeks_ago: '{n} weeks ago',
    shortlist_date_months_ago: '{n} months ago',
    shortlist_added_today: 'Added today',
    shortlist_added_yesterday: 'Added yesterday',
    shortlist_added_days_ago: 'Added {n} days ago',
    shortlist_added_week_ago: 'Added 1 week ago',
    shortlist_added_weeks_ago: 'Added {n} weeks ago',
    shortlist_added_months_ago: 'Added {n} months ago',
    shortlist_player_in_roster: 'Player is already in roster',
    shortlist_player_in_roster_women: 'Athlete is already in squad',
    shortlist_notes_count: '{n} notes',
    shortlist_notes_tap_to_add: 'Tap to add a note',
    shortlist_notes_add: 'Add Note',
    shortlist_notes_add_title: 'Add Note',
    shortlist_notes_edit_title: 'Edit Note',
    shortlist_notes_edit: 'Edit',
    shortlist_notes_delete: 'Delete',
    shortlist_notes_save: 'Save',
    shortlist_notes_placeholder: 'Write your note here...',
    shortlist_notes_days_ago: '{n}d ago',
    shortlist_sort_contact_score: 'Priority (high → low)',
    shortlist_sort_added: 'Date added',
    shortlist_sort_market_value: 'Market value',
    shortlist_sort_matches: 'Request matches',
    shortlist_sort_name: 'Name',
    shortlist_sort_age: 'Age',
    shortlist_filter_all: 'All',
    shortlist_filter_action_today: 'Action today (priority ≥7)',
    shortlist_filter_has_matches: 'Has request matches',
    shortlist_filter_contract_expiring: 'Contract expiring',
    shortlist_filter_free_agent: 'Free agent',
    shortlist_filter_my_players: 'My players',
    shortlist_filter_agent: 'Agent',
    shortlist_filter_with_notes: 'With notes',
    shortlist_filter_position_all: 'All',
    shortlist_filter_position_gk: 'GK',
    shortlist_filter_position_def: 'DEF',
    shortlist_filter_position_mid: 'MID',
    shortlist_filter_position_fwd: 'FWD',
    shortlist_contact_score: 'Priority {n}',
    shortlist_contact_score_tooltip: '1–10: higher = more urgent to contact (matches requests, free agent, contract expiring, value drop)',
    shortlist_score_why: 'Why {n}?',
    shortlist_score_base: 'Base score: 3',
    shortlist_score_matches: '+{points}: Matches {n} club requests',
    shortlist_score_matches_one: '+1: Matches 1 club request',
    shortlist_score_free_agent: '+2: Free agent',
    shortlist_score_contract: '+1: Contract expiring in {n} months',
    shortlist_score_value_drop: '+1: Value dropped {n}%',
    shortlist_score_minutes: '+0.5: Regular starter (1500+ min)',
    shortlist_score_productive: '+0.5: Productive (5+ G+A)',
    shortlist_matches_requests: 'Matches {n} requests',
    shortlist_free_agent: 'Free Agent',
    shortlist_contract_expiring: 'Contract in {n} months',
    shortlist_value_dropped: 'Value dropped {n}%',
    shortlist_value_rose: 'Value +{n}%',
    shortlist_data_stale: 'Data from {n} days ago',
    shortlist_refreshed_ago: 'Updated {n} ago',
    shortlist_refresh: 'Refresh',
    shortlist_refresh_tooltip: 'Update player info from Transfermarkt (name, value, club, contract)',
    shortlist_performance: 'Performance {season}',
    shortlist_performance_loading: 'Loading...',
    shortlist_no_matches: 'No matching requests',
    shortlist_dossier: 'Dossier',
    shortlist_appearances: 'Appearances',
    shortlist_goals: 'Goals',
    shortlist_assists: 'Assists',
    shortlist_minutes: 'Minutes',
    shortlist_open_transfermarkt: 'Open in Transfermarkt',
    shortlist_filter_empty: 'No players match this filter',
    shortlist_filter_empty_hint: 'Try a different filter or clear to see all {n} players.',
    shortlist_filter_clear: 'Show all',
    shortlist_showing_filtered: 'Showing {showing} of {total} players',
    common_cancel: 'Cancel',
    contacts_title: 'Contacts',
    contacts_title_women: 'Contacts',
    contacts_all: 'All',
    contacts_clubs: 'Clubs',
    contacts_agencies: 'Agencies',
    contacts_loading: 'Loading contacts...',
    contacts_loading_women: 'Loading contacts...',
    contacts_empty: 'No contacts yet',
    contacts_empty_women: 'No contacts yet',
    contacts_contact: 'Contact',
    contacts_add: 'Add contact',
    contacts_add_title: 'Add Contact',
    contacts_add_name: 'Name',
    contacts_add_name_placeholder: 'Contact name',
    contacts_add_name_required: 'Name is required',
    contacts_add_phone: 'Phone',
    contacts_add_phone_placeholder: '+1234567890',
    contacts_add_type: 'Type',
    contacts_add_club_name: 'Club name',
    contacts_add_club_name_placeholder: 'e.g. Chelsea FC',
    contacts_add_club_country: 'Club country',
    contacts_add_club_country_placeholder: 'e.g. England',
    contacts_add_agency_name: 'Agency name',
    contacts_add_agency_name_placeholder: 'e.g. CAA Stellar',
    contacts_add_agency_country: 'Agency country',
    contacts_add_agency_country_placeholder: 'e.g. USA',
    contacts_add_role: 'Role',
    contacts_add_save: 'Save Contact',
    contacts_edit: 'Edit',
    contacts_edit_title: 'Edit Contact',
    contacts_edit_save: 'Save Changes',
    contacts_delete: 'Delete',
    contacts_delete_confirm: 'Delete {name}? This cannot be undone.',
    transfer_windows_title: 'Open Transfer Windows',
    transfer_windows_days_left: '{n} days left',
    transfer_windows_today: 'Today',
    transfer_windows_open: 'Open',
    transfer_windows_empty: 'No open transfer windows at the moment.',
    transfer_windows_closing_soon: '{n} closing soon',
    transfer_windows_group_priority: 'Priority Markets',
    transfer_windows_group_uefa: 'Europe (UEFA)',
    transfer_windows_group_conmebol: 'South America (CONMEBOL)',
    transfer_windows_group_concacaf: 'North & Central America (CONCACAF)',
    transfer_windows_group_afc: 'Asia (AFC)',
    transfer_windows_group_caf: 'Africa (CAF)',
    transfer_windows_group_ofc: 'Oceania (OFC)',
    releases_title: 'Latest Releases',
    releases_loading: 'Loading releases...',
    releases_empty: 'No releases in this range',
    releases_try_filter: 'Try a different value filter',
    releases_all: 'All',
    releases_add: 'Add',
    releases_free_agent: 'Free agent',
    releases_progress: 'Page {page} • {total} players',
    releases_progress_ranges: 'Range {range}/{totalRanges} • {total} players',
    releases_position: 'Position',
    releases_age: 'Age',
    releases_age_all: 'All ages',
    releases_age_u23: 'Under 23',
    releases_age_23_30: '23-30',
    releases_age_30plus: '30+',
    releases_search: 'Search by name...',
    releases_stats_total: 'Total',
    releases_stats_showing: 'Showing',
    releases_sort: 'Sort by',
    releases_sort_value: 'Market value',
    releases_sort_date: 'Release date',
    releases_sort_age: 'Age',
    releases_value_filter: 'Value range',
    releases_reload: 'Reload',
    releases_roster_teammates: '{count} roster teammate(s)',
    releases_roster_teammates_tap: 'Roster teammates',
    releases_no_roster_teammates: 'No roster players played with this player',
    releases_roster_teammates_loading: 'Loading teammates…',
    releases_games_together: '{n} games together',
    releases_bookmark: 'Bookmark',
    releases_saved: 'Saved',
    releases_view_shortlist: 'View in shortlist',
    releases_stat_shortlisted: 'Shortlisted',
    returnee_title: 'Returnees',
    returnee_subtitle: 'Players returning from loan across European leagues',
    returnee_no_found: 'No returnees found',
    returnee_loading: 'Loading ({loaded}/{total} leagues)…',
    returnee_stat_leagues: 'Leagues',
    returnee_all_count: 'All {count}',
    returnee_badge_loan_return: 'Loan return',
    returnee_badge_returned_on: 'Returned {date}',
    returnee_clear_filters: 'Clear filters',
    returnee_current_club: 'Current club',
    returnee_returned: 'Returned',
    returnee_market_value: 'Market value',
    requests_title: 'Club Requests',
    requests_subtitle: 'Player requests from clubs by position',
    requests_title_women: 'Club Requests',
    requests_subtitle_women: 'Athlete requests from clubs by position',
    ai_scout_title: 'Find your next signing',
    ai_scout_subtitle: 'Describe the player you need in plain language. AI searches thousands of profiles to find the best matches.',
    ai_scout_placeholder: 'e.g. find me 20 strikers up to 26 years old that are very fast and with at least 5 goals last season',
    ai_scout_search: 'Search',
    ai_scout_searching: 'Searching…',
    ai_scout_searching_hint: 'Typically 10–20 seconds',
    ai_scout_local_testing: 'Add GEMINI_API_KEY to .env.local for AI analysis. Without it, mock results are shown.',
    ai_scout_examples: 'Example queries:',
    ai_scout_results_count: '{count} results',
    ai_scout_results_of: '{count} of {total} results',
    ai_scout_no_results: 'No results. Try a different query.',
    ai_scout_interpretation: 'How AI understood your request:',
    requests_loading: 'Loading requests...',
    requests_loading_women: 'Loading requests...',
    requests_loading_youth: 'Loading requests...',
    requests_empty: 'No club requests',
    requests_empty_women: 'No club requests yet',
    requests_empty_youth: 'No youth club requests yet',
    requests_title_youth: 'Youth Club Requests',
    requests_subtitle_youth: 'Youth player requests from clubs & academies by position',
    requests_manual_club_hint_youth: 'Enter club or academy details manually',
    requests_no_match_youth: 'No youth roster players match this request',
    requests_matching_players_one_youth: '{count} matching player',
    requests_matching_players_youth: '{count} matching players',
    requests_contact: 'Contact',
    requests_add: 'Add request',
    requests_delete: 'Delete',
    requests_delete_confirm: 'Delete request for {club} ({position})?',
    requests_stat_total: 'Total',
    requests_stat_positions: 'Positions',
    requests_country_club_one: '1 club',
    requests_country_clubs: '{count} clubs',
    requests_notes_label: 'Notes',
    requests_phone: 'Phone',
    requests_salary: 'Salary',
    requests_fee: 'Fee',
    requests_fee_free_loan: 'Free/Free loan',
    requests_age_range: 'Age',
    requests_foot: 'Foot',
    requests_add_title: 'Add Request',
    requests_edit_title: 'Edit Request',
    requests_edit: 'Edit',
    requests_eu_only: 'EU Only',
    requests_search_club: 'Search club…',
    requests_search_club_ifa: 'Search club in IFA (optional)',
    requests_searching_clubs: 'Searching IFA…',
    requests_no_clubs_found: 'No clubs found. Enter manually below.',
    requests_search_for_club: 'Search for club',
    requests_manual_club_hint: 'Enter club details (MGSR Women does not use Transfermarkt)',
    requests_club_name: 'Club name',
    requests_club_country: 'Country',
    requests_change_club: 'Change',
    requests_label_position: 'Position',
    requests_label_requirements: 'Requirements',
    requests_label_notes: 'Notes',
    requests_age_doesnt_matter: "Doesn't matter",
    requests_min: 'Min',
    requests_max: 'Max',
    requests_label_salary: 'Salary range',
    requests_label_fee: 'Transfer fee',
    requests_label_foot: 'Dominant foot',
    requests_foot_left: 'Left',
    requests_foot_right: 'Right',
    requests_foot_any: "Doesn't matter",
    requests_notes_placeholder: 'Additional notes…',
    requests_save: 'Save Request',
    requests_next: 'Next',
    requests_step_club: 'Club',
    requests_step_position: 'Position',
    requests_step_requirements: 'Requirements',
    requests_step_notes: 'Notes',
    requests_matching_players_one: '{count} matching player',
    requests_matching_players: '{count} matching players',
    requests_matching_players_one_women: '{count} matching player',
    requests_matching_players_women: '{count} matching players',
    requests_no_match: 'No roster players match this request',
    requests_no_match_women: 'No roster athletes match this request',
    requests_find_players_online: 'Find players using AI Scout',
    requests_online_players_loading: 'AI Scout searching…',
    requests_online_players_empty: 'No matching players found online',
    requests_online_match_score: 'Match: {pct}%',
    add_player_title: 'Add Player',
    add_to_shortlist_title: 'Add to Shortlist',
    add_player_back: 'Back to',
    add_player_paste_url: 'Paste Transfermarkt URL',
    add_player_load: 'Load',
    add_player_loading: 'Loading...',
    add_player_search: 'Or search by name',
    add_player_search_btn: 'Search',
    add_player_searching: 'Searching...',
    add_player_confirm: 'Confirm & Add',
    add_player_to_roster: 'Add to Roster',
    add_player_saving: 'Saving...',
    add_player_placeholder_url: 'https://www.transfermarkt.com/...',
    add_player_placeholder_search: 'Player name...',
    add_player_auto_search_hint: 'Results appear as you type',
    add_player_no_results: 'No players found. Try a different name.',
    add_player_from_shortlist_hint: 'Add this shortlisted player to your roster',
    add_player_shortlist_hint: 'Add this player to your shortlist for later',
    add_player_roster_hint: 'Add a new player to your roster',
    add_player_contact_section: 'Contact (optional)',
    add_woman_player_title: 'Add Woman Player',
    add_woman_player_subtitle: 'Search by name (SoccerDonna, Wosostat, FMInside) or add manually.',
    add_woman_player_search_placeholder: 'Search by name (e.g. Lauren James)',
    add_woman_player_searching: 'Searching…',
    add_woman_player_no_results: 'No results. Add manually below.',
    add_woman_player_add_manually: 'Add manually (enter all details)',
    add_woman_player_or_manual: 'Or',
    add_woman_player_add_manually_link: 'add manually',
    add_woman_player_with_details: 'with all details.',
    add_woman_player_paste_url_hint: 'Player not in search? Paste a SoccerDonna profile URL to load details:',
    add_woman_player_url_placeholder: 'https://www.soccerdonna.de/en/.../profil/spieler_12345.html',
    add_woman_player_load: 'Load',
    add_woman_player_loading: 'Loading…',
    add_woman_player_duplicate_error: 'Player with this SoccerDonna URL already in roster',
    add_woman_player_full_name: 'Full name *',
    add_woman_player_full_name_placeholder: 'e.g. Lauren James',
    add_woman_player_positions: 'Position(s)',
    add_woman_player_club: 'Club',
    add_woman_player_club_placeholder: 'e.g. Chelsea FCW',
    add_woman_player_age: 'Age',
    add_woman_player_age_placeholder: 'e.g. 23',
    add_woman_player_nationality: 'Nationality',
    add_woman_player_nationality_placeholder: 'e.g. England',
    add_woman_player_market_value: 'Market value',
    add_woman_player_market_value_placeholder: 'e.g. €500k (SoccerDonna)',
    add_woman_player_soccerdonna_url: 'SoccerDonna profile URL',
    add_woman_player_soccerdonna_hint: 'Optional. Used for duplicate check and future enrichment.',
    add_woman_player_fminside_url: 'FMInside profile URL',
    add_woman_player_fminside_url_hint: 'Paste FMInside player URL for direct FM data (e.g. fminside.net/players/7-fm-26/2000351404-diana-bieliakova)',
    add_woman_player_profile_image: 'Profile image URL',
    add_woman_player_notes: 'Notes',
    add_woman_player_notes_placeholder: 'Scout notes, Wosostat/FMInside IDs...',
    add_woman_player_saving: 'Saving…',
    add_woman_player_to_roster: 'Add to roster',
    add_woman_player_image_preview: 'Profile image preview',
    add_woman_player_search_image: 'Search for image',
    add_woman_player_searching_image: 'Searching…',
    add_woman_player_load_profile: 'Loading profile…',
    add_woman_player_fetch_failed_select: 'Could not load full profile. Basic info filled from search—you can edit below.',
    add_woman_player_fetch_failed_url: 'Could not load profile. Check the URL and try again.',
    woman_player_edit: 'Edit',
    woman_player_delete: 'Delete',
    woman_player_delete_confirm: 'Delete this player from the roster?',
    woman_player_delete_confirm_name: 'Delete {name}?',
    woman_player_save: 'Save',
    woman_player_cancel: 'Cancel',
    player_info_back: 'Back to Players',
    player_info_back_players: 'Back to Players',
    player_info_back_requests: 'Back to Requests',
    player_info_back_releases: 'Back to Releases',
    player_info_back_contract_finisher: 'Back to Contract Finisher',
    player_info_back_shadow_teams: 'Back to Shadow Teams',
    player_info_back_tasks: 'Back to Tasks',
    player_info_back_dashboard: 'Back to Dashboard',
    player_info_notes: 'Notes',
    player_info_no_notes: 'No notes yet',
    player_info_add_note: 'Add note',
    player_info_edit_note: 'Edit note',
    player_info_delete_note: 'Delete note',
    player_info_delete_note_confirm: 'Are you sure you want to delete this note?',
    player_info_note_placeholder: 'Add a new note…',
    player_info_note_save: 'Save',
    player_info_note_cancel: 'Cancel',
    player_info_agent: 'Agent',
    player_info_age: 'Age',
    player_info_height: 'Height',
    player_info_contract: 'Contract',
    player_info_not_found: 'Player not found',
    player_info_overview: 'Overview',
    player_info_stats: 'Key stats',
    player_info_club: 'Current club',
    player_info_contact: 'Contact',
    player_info_mandate: 'Mandate',
    player_info_documents: 'Documents',
    player_info_add_document: 'Add document',
    player_info_no_documents: 'No documents yet',
    player_info_uploading: 'Uploading document…',
    player_info_documents_empty_subtitle: 'Upload passports, mandates, medical docs, or other files.',
    player_info_delete_doc_confirm: 'Are you sure you want to delete',
    player_info_cd_open_link: 'Open link',
    player_info_cd_delete_document: 'Delete document',
    player_info_generate_mandate: 'Generate mandate',
    player_info_share: 'Share',
    player_info_prepare_portfolio: 'Prepare for Portfolio',
    player_info_added_to_portfolio: 'Added to portfolio',
    player_info_portfolio_scout_failed: 'Could not generate scout report. Try again.',
    player_info_portfolio_adding: 'Preparing…',
    mandate_no_passport: 'No passport details. Upload a passport document first.',
    mandate_step_agent: 'Select agent',
    mandate_no_agents_fifa: 'No agents with FIFA license found',
    mandate_fifa_license: 'FIFA License',
    mandate_step_validity: 'Validity & leagues',
    mandate_expiry_date: 'Expiry date',
    mandate_valid_leagues: 'Valid leagues',
    mandate_search_country: 'Search country...',
    mandate_add_country_league: 'Add country / league',
    mandate_entire_country: 'Entire country (all clubs)',
    mandate_sheet_search_clubs: 'Search clubs in %s…',
    mandate_selected_clubs: '%d club(s) selected',
    mandate_sheet_add_button: 'Add to mandate',
    mandate_change_country: 'Change',
    mandate_selected: 'Selected',
    mandate_step_review: 'Review',
    mandate_review_player: 'Player',
    mandate_review_agent: 'Agent',
    mandate_review_fifa_id: 'FIFA License ID',
    mandate_back: 'Back',
    mandate_next: 'Next',
    mandate_generating: 'Generating...',
    mandate_generate_pdf: 'Generate PDF',
    upload_failed: 'Upload failed. Please try again.',
    passport_already_exists: 'This player already has passport details. Delete the existing passport document first.',
    player_info_value_history: 'Value history',
    player_info_value_peak: 'Peak',
    player_info_value_low: 'Low',
    player_info_value_change: 'Change',
    player_info_value_points: 'Data points',
    player_info_foot: 'Preferred foot',
    player_info_on_loan: 'On loan from',
    player_info_salary: 'Salary range',
    player_info_transfer_fee: 'Transfer fee',
    player_info_salary_fee_title: 'Salary & Transfer Fee',
    player_info_salary_fee_save: 'Save',
    player_info_salary_fee_clear: 'Clear',
    player_info_salary_fee_not_set: 'Not set',
    player_info_agency: 'Agency',
    player_info_view_on_tm: 'View on Transfermarkt',
    player_info_refresh: 'Refresh data',
    similar_players_title: 'Similar Players',
    similar_players_find: 'Find Similar Players',
    similar_players_searching: 'Searching for similar players…',
    similar_players_match: 'Match',
    similar_players_style: 'Style',
    similar_players_nationality: 'Nationality',
    similar_players_league: 'League',
    similar_players_height: 'Height',
    similar_players_foot: 'Foot',
    similar_players_contract: 'Contract',
    similar_players_view_profile: 'View on Transfermarkt',
    similar_players_load_more: 'Load more similar players',
    similar_players_retry: 'Try again',
    similar_players_empty: 'No similar players found',
    similar_players_per90: 'Per 90 minutes',
    similar_players_growth: 'growth',
    similar_players_club: 'Club',
    similar_players_sources_hint: 'Analysis combines Transfermarkt, FBref stats & FM data',
    similar_players_women_title: 'Similar Players',
    similar_players_view_soccerdonna: 'View on SoccerDonna',
    similar_players_view_fminside: 'View on FMInside',
    similar_players_resolving: 'Resolving profiles…',
    player_info_mandate_active: 'Active',
    player_info_mandate_inactive: 'Inactive',
    player_info_mandate_expires: 'Mandate expires: %s',
    player_info_doc_expired: 'Expired',
    player_info_nationality: 'Nationality',
    player_info_foot_left: 'Left',
    player_info_foot_right: 'Right',
    player_info_foot_both: 'Both',
    player_info_matching_requests: 'Matching Requests',
    player_info_matching_requests_empty: 'No matching requests',
    player_info_matching_requests_empty_subtitle: 'Club requests that match this player will appear here',
    player_info_matching_requests_mark_offered: 'Mark as offered',
    player_info_matching_requests_offered: 'Offered',
    player_info_matching_requests_offered_date: 'Offered: %s',
    player_info_matching_requests_by_agent: 'By %s',
    player_info_matching_requests_club_feedback: 'Club feedback',
    player_info_matching_requests_add_feedback: 'Add feedback',
    player_info_matching_requests_edit_feedback: 'Edit feedback',
    player_info_matching_requests_add_feedback_title: 'Add club feedback',
    player_info_matching_requests_edit_feedback_title: 'Edit club feedback',
    player_info_matching_requests_offer_date: 'Offer date',
    player_info_matching_requests_feedback_hint: 'Club feedback (optional)',
    player_info_matching_requests_feedback_placeholder: 'Notes from the club…',
    player_info_matching_requests_cancel: 'Cancel',
    proposal_history_title: 'Proposal History',
    proposal_history_status_deleted: 'Request deleted',
    proposal_history_status_fulfilled: 'Fulfilled',
    proposal_history_status_active: 'Active',
    proposal_history_status_legacy: 'Previously offered',
    proposal_history_feedback: 'Club feedback',
    proposal_history_no_feedback: 'No feedback recorded',
    proposal_history_summary: 'Agent summary',
    proposal_history_add_summary: 'Add summary…',
    proposal_history_summary_hint: 'e.g. Deal fell through — player refused terms',
    proposal_history_summary_save: 'Save',
    proposal_history_by_agent: 'by %s',
    proposal_history_show_all: 'Show all (%s)',
    proposal_history_show_less: 'Show less',
    player_info_save_note: 'Save',
    player_info_added_by: 'Added by',
    player_info_agent_phone: 'Agent phone',
    player_info_player_phone: 'Player phone',
    player_info_player_phone_women: 'Player phone',
    contact_add_phone: 'Add phone',
    contact_add_agent_phone: 'Add agent phone',
    contact_add_player_phone: 'Add player phone',
    contact_edit_phone: 'Edit phone',
    contact_delete_phone: 'Delete phone',
    contact_confirm_delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    note_written_by: 'Written by',
    login_title: 'MGSR Team',
    login_subtitle: 'Login to your account',
    login_email: 'Email',
    login_password: 'Password',
    login_sign_in: 'Sign in',
    login_signing_in: 'Signing in...',
    login_hint: 'Use the same credentials as your Android app',
    common_or: 'or',
    common_years: 'yrs',
    search_no_results: 'No results found',
    search_placeholder: 'Search by name, position or club...',
    contact_type_club: 'Club',
    contact_type_agency: 'Agency',
    contact_role_other: 'Other',
    contact_role_coach: 'Coach',
    contact_role_asst_coach: 'Asst Coach',
    contact_role_sport_dir: 'Sport Dir',
    contact_role_board: 'Board',
    contact_role_ceo: 'CEO',
    contact_role_president: 'President',
    contact_role_scout: 'Scout / Analyst',
    contact_role_agent: 'Agent',
    contact_role_intermediary: 'Intermediary',
    contact_role_agency_dir: 'Agency Dir',
    no_club: 'No club',
    without_club: 'Without Club',
    eu_nat_tag: 'EU Nat',
    nav_shadow_teams: 'Shadow Teams',
    nav_contract_finisher: 'Contract Finisher',
    nav_portfolio: 'Portfolio',
    portfolio_title: 'Portfolio',
    portfolio_subtitle: 'Players ready to share with a complete scout report. Share via WhatsApp with one tap.',
    portfolio_subtitle_women: 'Players ready to share with a complete scout report. Share via WhatsApp with one tap.',
    portfolio_empty_title: 'Your portfolio is empty',
    portfolio_empty_hint: 'Add players from their profile page using "Prepare for Portfolio". Each player will have a guaranteed scout report.',
    portfolio_empty_hint_women: 'Add players from their profile page using "Prepare for Portfolio". Each player will have a scout report ready.',
    portfolio_browse_players: 'Browse Players',
    portfolio_browse_players_women: 'Browse Players',
    portfolio_back_to_player: 'Back to player profile',
    portfolio_share: 'Share',
    portfolio_view: 'View',
    portfolio_version_hebrew: 'Hebrew version',
    portfolio_version_english: 'English version',
    portfolio_share_attach_contact: 'Attach the player contact number?',
    portfolio_share_attach_player_contact: 'Add player contact',
    portfolio_share_attach_agency_contact: 'Add player agency contact',
    portfolio_share_no_contact: 'No player contact number available.',
    portfolio_share_cancel: 'Cancel',
    portfolio_share_via_whatsapp: 'Share via WhatsApp',
    contract_finisher_title: 'Contract Finisher',
    contract_finisher_subtitle_summer: 'Contracts expiring towards Summer window',
    contract_finisher_subtitle_winter: 'Contracts expiring towards Winter window',
    contract_finisher_loading: 'Loading…',
    contract_finisher_loading_more: 'Loading more…',
    contract_finisher_retry: 'Retry',
    contract_finisher_badge: 'Release date',
    contract_finisher_no_found: 'No contract finishers found in this range',
    contract_finisher_no_match_filters: 'No players match your filters',
    contract_finisher_clear_filters: 'Clear filters',
    contract_finisher_apply_filters: 'Apply Filters',
    contract_finisher_filter_age_all: 'All',
    contract_finisher_filter_age_18_21: '18-21',
    contract_finisher_filter_age_22_25: '22-25',
    contract_finisher_filter_age_26_29: '26-29',
    contract_finisher_filter_age_30_plus: '30+',
    contract_finisher_filter_value_all: 'All',
    contract_finisher_filter_value_150k_500k: '€150K–500K',
    contract_finisher_filter_value_500k_1m: '€500K–1M',
    contract_finisher_filter_value_1m_2m: '€1M–2M',
    contract_finisher_filter_value_2m_3m: '€2M–3M',
    contract_finisher_filter_label_value: 'Value',
    contract_finisher_filter_label_position: 'Position',
    contract_finisher_filter_label_age: 'Age',
    contract_finisher_filter_label_region: 'Region',
    contract_finisher_stats_total: 'Total',
    contract_finisher_stats_shortlisted: 'Shortlisted',
    contract_finisher_stats_visible: 'Visible',
    contract_finisher_filters: 'Filters',
    roster_analytics_title: 'Roster Analytics',
    roster_analytics_position: 'By Position',
    roster_analytics_age: 'By Age',
    roster_analytics_value: 'By Market Value',
    roster_analytics_contracts: 'Contracts Expiring',
    roster_analytics_mandates: 'Mandate Status',
    roster_analytics_with_mandate: 'With mandate',
    roster_analytics_without_mandate: 'Without mandate',
    roster_analytics_age_u21: 'U21',
    roster_analytics_age_22_25: '22-25',
    roster_analytics_age_26_29: '26-29',
    roster_analytics_age_30_plus: '30+',
    roster_analytics_value_unknown: 'Unknown',
    roster_analytics_value_0_500k: '0-500K',
    roster_analytics_value_500k_1m: '500K-1M',
    roster_analytics_value_1m_5m: '1M-5M',
    roster_analytics_value_5m_plus: '5M+',
    players_filter_free_agents: 'Free Agents',
    players_filter_contract_expiring: 'Contract Expiring',
    players_filter_with_mandate: 'With Mandate',
    players_with_mandate_title: 'Players with Mandate',
    players_mandate_expires_label: 'Expires:',
    players_filter_my_players_only: 'My Players Only',
    players_filter_agent: 'Agent',
    players_filter_loan_players_only: 'Loan Players Only',
    players_filter_without_registered_agent: 'Without Registered Agent',
    players_filter_with_notes: 'With Notes',
    players_filter_foot_left: 'Left foot',
    players_filter_foot_right: 'Right foot',
    players_filter_eu_national: 'EU Nat',
    players_filter_offered_no_feedback: 'Offered · No Feedback',
    players_filter_position_gk: 'GK',
    players_filter_position_gk_women: 'GK',
    players_filter_position_def: 'DEF',
    players_filter_position_mid: 'MID',
    players_filter_position_fwd: 'FWD',
    players_filter_clear: 'Clear filters',
    shadow_teams_title: 'Shadow Teams',
    shadow_teams_subtitle: 'Your preferred players for the next transfer window',
    shadow_teams_formation: 'Formation',
    shadow_teams_hint: "Switch tabs to see each agent's team • Your tab: add, edit, remove • Others: view profile only",
    shadow_teams_bench: 'Bench',
    shadow_teams_select_player: 'Select player',
    shadow_teams_search_player: 'Search player',
    shadow_teams_no_players: 'No players found for this position',
    shadow_teams_cancel: 'Cancel',
    shadow_teams_view_player: 'View profile',
    shadow_teams_change_player: 'Change player',
    shadow_teams_remove_player: 'Remove',
    shadow_teams_you: 'You',
    // Player Highlights
    highlights_title: 'Highlights',
    highlights_loading: 'Loading highlights...',
    highlights_empty: 'No highlight videos found for this player',
    highlights_error: "Couldn't load highlights",
    highlights_recent_matches: 'Recent Match Highlights',
    highlights_compilations: 'Player Highlights',
    highlights_powered_by: 'Powered by YouTube & Scorebat',
    highlights_updated: 'Updated',
    highlights_refresh: 'Refresh',
    highlights_retry: 'Retry',
    highlights_views: 'views',
    highlights_disclaimer: 'The videos you select will be displayed as part of the player profile until you replace them.',
    highlights_select_up_to: 'Select up to 2 videos',
    highlights_saving: 'Saving...',
    highlights_confirm_selection: 'Confirm selection',
    highlights_replace_videos: 'Replace videos',
    highlights_confirm_replacement: 'Confirm replacement',
    highlights_cancel: 'Cancel',
    highlights_pinned_count: '{n} pinned',
    // FM Intelligence Panel
    fm_section_title: 'FM Intelligence',
    fm_empty_title: 'Not in the FM database',
    fm_empty_subtitle: 'This player doesn\'t have Football Manager attributes yet. FM Intelligence becomes available when the player is included in the FM database.',
    fm_tab_intelligence: 'FM Intelligence',
    fm_tab_position_fit: 'Position Fit',
    fm_loading: 'Loading FM Intelligence...',
    fm_current_ability: 'Current Ability',
    fm_pa_label: 'Potential Ability',
    fm_potential: 'potential',
    fm_at_peak: 'At peak',
    fm_best_fit: 'Best fit:',
    fm_ability_dimensions: 'Ability Dimensions',
    fm_top_attributes: 'Top Attributes',
    fm_weaknesses: 'Weaknesses',
    fm_no_weaknesses: 'No major weaknesses',
    fm_position_rankings: 'Position Rankings',
    fm_fit: 'fit',
    fm_footer: 'Data from Football Manager via FMInside',
    fm_loading_women: 'Loading FMInside data...',
    fm_empty_title_women: 'No FM data found',
    fm_no_match_women: 'No matching player found on FMInside (women\'s database). Try checking the name spelling or add more details.',
    fm_no_match_load_failed: 'Found a possible match but could not load details.',
    fm_no_match_error: 'Failed to fetch FMInside data.',
    fm_paste_url_hint: 'Found her on FMInside? Paste her profile URL below to load FM data.',
    fm_paste_url_placeholder: 'https://fminside.net/players/7-fm-26/...',
    fm_paste_apply: 'Load',
    fm_search_on_site: 'Search on FMInside',
    fm_left_foot: 'Left foot',
    fm_right_foot: 'Right foot',
    // FM Tiers
    fm_tier_unknown: 'Unknown',
    fm_tier_world_class: 'World Class',
    fm_tier_elite: 'Elite',
    fm_tier_top_league: 'Top League',
    fm_tier_solid_pro: 'Solid Pro',
    fm_tier_lower_league: 'Lower League',
    fm_tier_prospect: 'Prospect',
    // FM Dimensions
    fm_dim_technical: 'Technical',
    fm_dim_mental: 'Mental',
    fm_dim_physical: 'Physical',
    fm_dim_set_pieces: 'Set Pieces',
    fm_dim_attacking: 'Attacking',
    fm_dim_defending: 'Defending',
    fm_dim_creative: 'Creative',
    fm_dim_aerial: 'Aerial',
    fm_dim_pace_power: 'Pace & Power',
    fm_dim_work_ethic: 'Work Ethic',
    // FM Positions
    fm_pos_ST: 'Striker',
    fm_pos_LW: 'Left Wing',
    fm_pos_RW: 'Right Wing',
    fm_pos_AM: 'Att. Mid',
    fm_pos_LM: 'Left Mid',
    fm_pos_RM: 'Right Mid',
    fm_pos_CM: 'Central Mid',
    fm_pos_DM: 'Def. Mid',
    fm_pos_LB: 'Left Back',
    fm_pos_RB: 'Right Back',
    fm_pos_CB: 'Center Back',
    fm_pos_GK: 'Goalkeeper',
    // FM Legend
    fm_legend_perfect: 'Perfect (85%+)',
    fm_legend_great: 'Great (72-84%)',
    fm_legend_decent: 'Decent (58-71%)',
    fm_legend_possible: 'Possible (40-57%)',
    fm_legend_poor: 'Poor',
    // FM Attributes
    fm_attr_crossing: 'Crossing',
    fm_attr_dribbling: 'Dribbling',
    fm_attr_finishing: 'Finishing',
    fm_attr_first_touch: 'First Touch',
    fm_attr_heading: 'Heading',
    fm_attr_long_shots: 'Long Shots',
    fm_attr_marking: 'Marking',
    fm_attr_passing: 'Passing',
    fm_attr_tackling: 'Tackling',
    fm_attr_technique: 'Technique',
    fm_attr_aggression: 'Aggression',
    fm_attr_anticipation: 'Anticipation',
    fm_attr_bravery: 'Bravery',
    fm_attr_composure: 'Composure',
    fm_attr_concentration: 'Concentration',
    fm_attr_decisions: 'Decisions',
    fm_attr_determination: 'Determination',
    fm_attr_flair: 'Flair',
    fm_attr_leadership: 'Leadership',
    fm_attr_off_the_ball: 'Off the Ball',
    fm_attr_positioning: 'Positioning',
    fm_attr_teamwork: 'Teamwork',
    fm_attr_vision: 'Vision',
    fm_attr_work_rate: 'Work Rate',
    fm_attr_acceleration: 'Acceleration',
    fm_attr_agility: 'Agility',
    fm_attr_balance: 'Balance',
    fm_attr_jumping_reach: 'Jumping',
    fm_attr_natural_fitness: 'Nat. Fitness',
    fm_attr_pace: 'Pace',
    fm_attr_stamina: 'Stamina',
    fm_attr_strength: 'Strength',
    fm_attr_corners: 'Corners',
    fm_attr_free_kick_taking: 'Free Kicks',
    fm_attr_long_throws: 'Long Throws',
    fm_attr_penalty_taking: 'Penalties',

    // News & Rumors
    nav_news: 'News & Rumors',
    news_title: 'News & Rumors',
    news_subtitle: 'Transfer rumours & league news from your working markets',
    news_tab_all: 'All',
    news_tab_rumours: 'Rumours',
    news_tab_news: 'News',
    news_search_placeholder: 'Search players, clubs, headlines...',
    news_from: 'from',
    news_to: 'to',
    news_probability: 'Probability',
    news_view_on_tm: 'View on Transfermarkt',
    news_add_shortlist: 'Add to Shortlist',
    news_no_results: 'No news or rumours found',
    news_loading: 'Fetching latest news...',
    news_stat_rumours: 'Rumours',
    news_stat_news: 'News Articles',
    news_stat_leagues: 'Leagues',
    news_refresh: 'Refresh',
    news_updated_ago: 'Updated',
    news_source_tm: 'Transfermarkt',
    news_source_google: 'Google News',
    news_all_leagues: 'All',
    news_open_article: 'Open Article',
    news_market_value: 'Market Value',
    news_tag_database: 'Database',
    news_tag_shortlist: 'Shortlist',
  },
  he: {
    greeting_morning: 'בוקר טוב',
    greeting_afternoon: 'צהריים טובים',
    greeting_evening: 'ערב טוב',
    agent: 'סוכן',
    dashboard: 'לוח בקרה',
    players: 'שחקנים',
    players_women: 'שחקניות',
    player_women: 'שחקנית',
    contacts: 'אנשי קשר',
    requests: 'בקשות',
    tasks: 'משימות',
    shortlist: 'רשימת מעקב',
    releases: 'שחרורים',
    add_player: 'הוסף שחקן',
    activity_this_week: 'פעילות השבוע',
    event_types_this_week: 'סוגי אירועים השבוע',
    staff_tasks: 'צוות ומשימות',
    top_agents_this_week: 'סוכנים מובילים השבוע',
    leading_agencies_title: 'סוכנויות מובילות',
    leading_agencies_in_contact: 'בקשר',
    leading_agencies_players: 'שחקנים',
    leading_agencies_empty: 'אין עדיין סוכנויות עם שחקנים. הוסף אנשי קשר מסוכנויות וקשר שחקנים לסוכנויות שלהם.',
    events: 'אירועים',
    no_agent_activity: 'אין פעילות סוכנים השבוע',
    recent_activity: 'פעילות אחרונה',
    no_recent_activity: 'אין פעילות. הוסף שחקן כדי להתחיל.',
    no_recent_activity_women: 'אין פעילות. הוסף שחקנית כדי להתחיל.',
    loading_feed: 'טוען...',
    pending: 'ממתין',
    no_staff_data: 'אין נתוני צוות',
    no_events_this_week: 'אין אירועים השבוע',
    market_value_change: 'שינוי שווי שוק',
    club_change: 'חילוף מועדון',
    contract_expiring: 'חוזה מסתיים',
    note_added: 'הערה נוספה',
    player_added: 'שחקן נוסף',
    player_added_women: 'שחקנית נוספה',
    player_added_youth: 'שחקן הוסף',
    free_agent: 'שחקן חופשי',
    free_agent_women: 'שחקנית חופשית',
    mandate_expired: 'מנדט פג תוקף',
    mandate_uploaded: 'מנדט הועלה',
    shortlist_added: 'נוסף לרשימת מעקב',
    shortlist_removed: 'הוסר מרשימת מעקב',
    request_added: 'בקשה נוספה',
    request_deleted: 'בקשה נמחקה',
    player_offered: 'שחקן הוצע',
    player_offered_women: 'שחקנית הוצעה',
    new_release_from_club: 'שחרור חדש ממועדון',
    player_deleted: 'שחקן הוסר',
    player_deleted_women: 'שחקנית הוסרה',
    note_deleted: 'הערה נמחקה',
    mandate_switched_on: 'מנדט הופעל',
    mandate_switched_off: 'מנדט בוטל',
    unassigned: 'ללא שיוך',
    just_now: 'עכשיו',
    minutes_ago: 'דק׳',
    hours_ago: 'ש׳',
    by: 'על ידי',
    loading: 'טוען...',
    sign_out: 'התנתק',
    notif_enable: 'הפעל התראות',
    notif_enable_desc: 'קבל התראות כשמשימות מוקצות אליך וכשיש עדכוני שחקנים.',
    notif_enabled: 'התראות מופעלות',
    notif_blocked: 'התראות חסומות — הפעל בהגדרות הדפדפן',
    notif_enable_btn: 'הפעל',
    notif_cancel_btn: 'ביטול',
    notif_prompt_title: 'הישאר מעודכן',
    notif_prompt_desc: 'הפעל התראות כדי לקבל עדכונים בזמן אמת על משימות חדשות, עדכוני שחקנים ואירועים חשובים — גם כשהדפדפן ברקע.',
    notif_prompt_enable: 'הפעל התראות',
    notif_prompt_later: 'אולי אחר כך',
    nav_more: 'עוד',
    filters: 'סינון',
    apply: 'החל',
    nav_dashboard: 'לוח בקרה',
    nav_tasks: 'משימות',
    nav_players: 'שחקנים',
    nav_players_women: 'שחקניות',
    nav_players_youth: 'שחקני נוער',
    nav_add_player: 'הוסף שחקן',
    nav_shortlist: 'רשימת מעקב',
    nav_ai_scout: 'AI סקאוט',
    nav_war_room: 'חדר מלחמה',
    rec_sign: 'להחתים',
    rec_monitor: 'מעקב',
    rec_pass: 'לוותר',
    nav_find_next: 'מצא את הבא',
    nav_contacts: 'אנשי קשר',
    nav_releases: 'שחרורים',
    nav_returnee: 'חזרו מהשאלה',
    nav_requests: 'דרישות מועדונים',
    tasks_title: 'משימות',
    tasks_filter_pending: 'ממתין',
    tasks_filter_done: 'הושלם',
    tasks_filter_all: 'הכל',
    tasks_loading: 'טוען משימות...',
    tasks_empty: 'אין משימות עדיין',
    tasks_empty_hint: 'הוסף את המשימה הראשונה שלך',
    tasks_add: 'הוסף משימה',
    tasks_new_task: 'משימה חדשה',
    tasks_new_task_women: 'פריט פעולה חדש',
    tasks_what_needs_done: 'מה צריך לעשות?',
    tasks_assign_to: 'הקצה ל',
    tasks_priority: 'עדיפות',
    tasks_priority_low: 'נמוכה',
    tasks_priority_medium: 'בינונית',
    tasks_priority_high: 'גבוהה',
    tasks_due_date: 'תאריך יעד',
    tasks_notes_hint: 'הוסף הערות (אופציונלי)',
    tasks_create: 'צור משימה',
    tasks_edit: 'ערוך',
    tasks_delete: 'מחק',
    tasks_delete_confirm: 'למחוק את המשימה?',
    tasks_save: 'שמור',
    tasks_cancel: 'ביטול',
    tasks_due_today: 'היום',
    tasks_due_tomorrow: 'מחר',
    tasks_overdue: 'באיחור',
    tasks_no_date: 'ללא תאריך',
    tasks_completed: 'הושלם',
    tasks_all_agents: 'כל הסוכנים',
    tasks_my_tasks: 'המשימות שלי',
    tasks_overdue_count: 'באיחור',
    tasks_agents: 'סוכנים',
    tasks_due_today_count: 'להיום',
    tasks_completed_count: 'הושלמו',
    tasks_section_overdue: 'באיחור',
    tasks_section_today: 'היום',
    tasks_section_tomorrow: 'מחר',
    tasks_section_this_week: 'השבוע',
    tasks_section_later: 'מאוחר יותר',
    tasks_section_no_date: 'ללא תאריך',
    tasks_section_completed: 'הושלמו',
    tasks_tab_active: 'פעיל',
    tasks_no_active: 'אין משימות פעילות',
    tasks_no_completed: 'אין משימות שהושלמו',
    tasks_progress: 'התקדמות',
    tasks_title_women: 'משימות',
    tasks_empty_women: 'אין פריטי פעולה עדיין',
    tasks_empty_hint_women: 'הוסף את הפריט הראשון למעקב אחר שחקניות',
    tasks_add_women: 'הוסף משימה',
    tasks_my_tasks_women: 'המשימות שלי',
    tasks_all_agents_women: 'תצוגת צוות',
    player_tasks_section: 'משימות קשורות לשחקן',
    player_tasks_section_women: 'משימות קשורות לשחקנית',
    player_tasks_add: 'הוסף משימה',
    player_tasks_add_women: 'הוסף משימה',
    player_tasks_empty: 'אין עדיין משימות לשחקן זה',
    player_tasks_empty_women: 'אין עדיין משימות לשחקנית זו',
    player_tasks_choose_template: 'בחר טמפלט (מומלץ)',
    player_tasks_choose_template_women: 'בחר טמפלט (מומלץ)',
    player_tasks_created_by: 'נוצר ע״י',
    tasks_opened_by: 'נפתח ע״י',
    tasks_assigned_to_label: 'הוקצה ל',
    tasks_created_on: 'נוצר',
    tasks_due_label: 'יעד',
    tasks_contact_agent: 'ליצור קשר עם הסוכן',
    tasks_select_agent_contact: 'קשר סוכן מאנשי קשר',
    tasks_linked_agent: 'סוכן',
    players_title: 'הסגל שלנו',
    players_title_women: 'הסגל שלנו',
    players_add: 'הוסף שחקן',
    players_add_women: 'הוסף שחקנית',
    players_loading: 'טוען שחקנים...',
    players_loading_women: 'טוען שחקניות...',
    players_empty: 'אין שחקנים עדיין',
    players_empty_women: 'אין שחקניות עדיין',
    players_empty_hint: 'הוסף את השחקן הראשון לבניית הסגל',
    players_empty_hint_women: 'הוסף את השחקנית הראשונה לבניית הסגל',
    players_total: 'סה״כ',
    players_value: 'שווי',
    players_club: 'מועדון',
    players_age: 'שנים',
    players_age_display: 'בן {age}',
    players_age_display_women: 'בת {age}',
    players_title_youth: 'שחקני נוער',
    players_subtitle_youth: 'שחקני נוער',
    players_add_youth: 'הוסף שחקן נוער',
    players_loading_youth: 'טוען שחקני נוער...',
    players_empty_youth: 'אין שחקני נוער עדיין',
    players_empty_hint_youth: 'הוסף את שחקן הנוער הראשון שלך',
    players_search_youth: 'חפש שחקני נוער...',
    shortlist_empty_hint_youth: 'חפש ב-IFA או הוסף שחקני נוער לרשימת המעקב',
    youth_add_title: 'הוסף שחקן נוער',
    youth_add_shortlist_title: 'הוסף לרשימת מעקב נוער',
    youth_add_subtitle: 'חפש ב-IFA (football.org.il) או הזן פרטי שחקן ידנית.',
    youth_add_shortlist_subtitle: 'חפש ב-IFA או הזן פרטי שחקן לרשימת מעקב נוער.',
    youth_add_back_players: 'חזרה לשחקנים',
    youth_add_back_shortlist: 'חזרה לרשימת מעקב',
    youth_add_search_placeholder: 'חפש שחקן ב-IFA… (שם בעברית או אנגלית)',
    youth_add_searching: 'מחפש ב-IFA...',
    youth_add_no_results: 'לא נמצאו תוצאות ב-IFA.',
    youth_add_manual: 'הוסף ידנית',
    youth_add_or_manual: 'הוסף ידנית',
    youth_add_or_manual_hint: 'עם הפרטים למטה.',
    youth_add_paste_url: 'הדבק קישור לדף שחקן ב-IFA למילוי אוטומטי:',
    youth_add_load: 'טען',
    youth_add_loading: 'טוען...',
    youth_add_loading_profile: 'טוען פרופיל IFA...',
    youth_add_identity: 'זהות השחקן',
    youth_add_name: 'שם מלא',
    youth_add_name_en: 'שם מלא (אנגלית)',
    youth_add_name_he: 'שם מלא (עברית)',
    youth_add_positions: 'עמדות',
    youth_add_club_details: 'מועדון ופרטים',
    youth_add_club: 'מועדון נוכחי',
    youth_add_academy: 'אקדמיה / מחלקה',
    youth_add_dob: 'תאריך לידה',
    youth_add_age_group: 'קבוצת גיל',
    youth_add_nationality: 'לאום',
    youth_add_ifa_profile: 'פרופיל IFA',
    youth_add_ifa_url: 'קישור פרופיל IFA',
    youth_add_ifa_hint: 'משמש לבדיקת כפילויות והעשרת נתונים.',
    youth_add_photo: 'תמונה',
    youth_add_find_photo: 'חפש',
    youth_add_searching_photo: 'מחפש...',
    youth_add_preview: 'תצוגה מקדימה',
    youth_add_contact: 'פרטי קשר',
    youth_add_player_section: 'שחקן',
    youth_add_phone: 'טלפון',
    youth_add_email: 'אימייל',
    youth_add_parent: 'הורה / אפוטרופוס',
    youth_add_parent_name: 'שם ההורה',
    youth_add_relationship: 'קשר',
    youth_add_parent_phone: 'טלפון הורה',
    youth_add_parent_email: 'אימייל הורה',
    youth_add_relationship_father: 'אב',
    youth_add_relationship_mother: 'אם',
    youth_add_relationship_guardian: 'אפוטרופוס',
    youth_add_relationship_agent: 'סוכן',
    youth_add_notes: 'הערות',
    youth_add_saving: 'שומר...',
    youth_add_save_shortlist: 'הוסף לרשימת מעקב נוער',
    youth_add_save_roster: 'הוסף לסגל נוער',
    youth_add_select: 'בחר...',
    youth_detail_back_link: 'שחקני נוער',
    youth_detail_task_btn: '+ משימה',
    youth_detail_edit: 'עריכה',
    youth_detail_delete: 'מחיקה',
    youth_detail_mandate: 'מנדט',
    youth_detail_expires: 'תוקף',
    youth_detail_contact: 'פרטי קשר',
    youth_detail_player_section: 'שחקן',
    youth_detail_ifa_stats: 'סטטיסטיקות IFA',
    youth_detail_matches: 'משחקים',
    youth_detail_goals: 'שערים',
    youth_detail_assists: 'בישולים',
    youth_detail_documents: 'מסמכים',
    youth_detail_uploading: 'מעלה...',
    youth_detail_no_documents: 'אין מסמכים עדיין.',
    youth_detail_upload: '+ העלאה',
    youth_detail_tasks: 'משימות',
    youth_detail_add: '+ הוספה',
    youth_detail_no_tasks: 'אין משימות עדיין.',
    youth_detail_due: 'תאריך יעד:',
    youth_detail_notes: 'הערות',
    youth_detail_add_note: '+ הוסף הערה',
    youth_detail_no_notes: 'אין הערות עדיין.',
    youth_detail_agent_in_charge: 'סוכן אחראי',
    youth_detail_add_note_title: 'הוסף הערה',
    youth_detail_edit_note_title: 'ערוך הערה',
    youth_detail_note_placeholder: 'כתוב את ההערה שלך...',
    youth_detail_cancel: 'ביטול',
    youth_detail_saving: 'שומר...',
    youth_detail_save: 'שמור',
    youth_detail_delete_note_confirm: 'למחוק הערה?',
    youth_detail_cannot_undo: 'לא ניתן לבטל פעולה זו.',
    youth_detail_delete_doc_confirm: 'למחוק מסמך?',
    youth_detail_will_be_removed: 'יוסר.',
    youth_detail_delete_player_confirm: 'למחוק שחקן?',
    youth_detail_permanently_removed: 'יוסר לצמיתות.',
    youth_detail_deleting: '...מוחק',
    youth_detail_edit_title: 'עריכת שחקן נוער',
    youth_detail_profile_image: 'קישור תמונת פרופיל',
    youth_detail_player_phone: 'טלפון שחקן',
    youth_detail_player_email: 'אימייל שחקן',
    youth_detail_save_changes: 'שמור שינויים',
    youth_detail_expired: 'פג תוקף',
    youth_detail_ifa_profile: 'פרופיל IFA',
    youth_detail_not_found: 'שחקן לא נמצא',
    youth_detail_back_to_players: 'חזרה לשחקנים',
    youth_detail_parent: 'הורה',
    youth_detail_document: 'מסמך',
    shortlist_title: 'רשימת מעקב',
    shortlist_title_women: 'רשימת מעקב',
    shortlist_loading: 'טוען רשימת מעקב...',
    shortlist_loading_women: 'טוען רשימת מעקב...',
    shortlist_empty: 'רשימת המעקב ריקה',
    shortlist_empty_hint: 'עיין בשחרורים או הוסף מ-Transfermarkt',
    shortlist_empty_women: 'רשימת המעקב ריקה',
    shortlist_empty_hint_women: 'חפש ב-SoccerDonna כדי להוסיף שחקניות לרשימת המעקב',
    shortlist_add_from_soccerdonna: 'הוסף מ-SoccerDonna',
    shortlist_add_to_shortlist_women: 'הוסף לרשימת מעקב',
    shortlist_add_hint_women: 'חפש ובחר שחקנית מ-SoccerDonna. אין צורך בפרטי קשר.',
    shortlist_women_profile_url_required: 'בחר שחקנית מהחיפוש או הדבק קישור SoccerDonna/FMInside',
    shortlist_already_added: 'כבר ברשימת המעקב',
    shortlist_browse_releases: 'עיין בשחרורים',
    shortlist_browse_returnees: 'עיין בחזר מהשאלה',
    shortlist_add_from_tm: 'הוסף מ-Transfermarkt',
    shortlist_add_youth_player: 'הוסף שחקן נוער',
    shortlist_remove: 'הסר',
    shortlist_unknown_player: 'שחקנית לא ידועה',
    shortlist_no_info: '—',
    shortlist_add: 'הוסף לרשימת מעקב',
    shortlist_adding: 'מוסיף...',
    shortlist_added_by: 'נוסף על ידי',
    shortlist_added_by_date: 'נוסף על ידי {agent} · {date}',
    shortlist_date_today: 'היום',
    shortlist_date_yesterday: 'אתמול',
    shortlist_date_days_ago: 'לפני {n} ימים',
    shortlist_date_week_ago: 'לפני שבוע',
    shortlist_date_weeks_ago: 'לפני {n} שבועות',
    shortlist_date_months_ago: 'לפני {n} חודשים',
    shortlist_added_today: 'נוסף היום',
    shortlist_added_yesterday: 'נוסף אתמול',
    shortlist_added_days_ago: 'נוסף לפני {n} ימים',
    shortlist_added_week_ago: 'נוסף לפני שבוע',
    shortlist_added_weeks_ago: 'נוסף לפני {n} שבועות',
    shortlist_added_months_ago: 'נוסף לפני {n} חודשים',
    shortlist_player_in_roster: 'השחקן כבר בסגל',
    shortlist_player_in_roster_women: 'השחקנית כבר בסגל',
    shortlist_notes_count: '{n} הערות',
    shortlist_notes_tap_to_add: 'לחץ להוספת הערה',
    shortlist_notes_add: 'הוסף הערה',
    shortlist_notes_add_title: 'הוסף הערה',
    shortlist_notes_edit_title: 'ערוך הערה',
    shortlist_notes_edit: 'ערוך',
    shortlist_notes_delete: 'מחק',
    shortlist_notes_save: 'שמור',
    shortlist_notes_placeholder: 'כתוב את ההערה שלך כאן...',
    shortlist_notes_days_ago: 'לפני {n} ימים',
    shortlist_sort_contact_score: 'עדיפות (גבוה → נמוך)',
    shortlist_sort_added: 'תאריך הוספה',
    shortlist_sort_market_value: 'ערך שוק',
    shortlist_sort_matches: 'התאמות לבקשות',
    shortlist_sort_name: 'שם',
    shortlist_sort_age: 'גיל',
    shortlist_filter_all: 'הכל',
    shortlist_filter_action_today: 'לטפל היום (עדיפות ≥7)',
    shortlist_filter_has_matches: 'מתאים לבקשות',
    shortlist_filter_contract_expiring: 'חוזה מסתיים',
    shortlist_filter_free_agent: 'Free Agent',
    shortlist_filter_my_players: 'השחקנים שלי',
    shortlist_filter_agent: 'סוכן',
    shortlist_filter_with_notes: 'עם הערות',
    shortlist_filter_position_all: 'הכל',
    shortlist_filter_position_gk: 'שוערים',
    shortlist_filter_position_def: 'הגנה',
    shortlist_filter_position_mid: 'קישור',
    shortlist_filter_position_fwd: 'התקפה',
    shortlist_contact_score: 'עדיפות {n}',
    shortlist_contact_score_tooltip: '1–10: גבוה יותר = דחוף יותר ליצירת קשר (התאמות לבקשות, שחקן חופשי, חוזה מסתיים, ירידת ערך)',
    shortlist_score_why: 'למה {n}?',
    shortlist_score_base: 'ציון בסיס: 3',
    shortlist_score_matches: '+{points}: מתאים ל-{n} בקשות מועדונים',
    shortlist_score_matches_one: '+1: מתאים לבקשה אחת',
    shortlist_score_free_agent: '+2: שחקן חופשי',
    shortlist_score_contract: '+1: חוזה מסתיים בעוד {n} חודשים',
    shortlist_score_value_drop: '+1: ערך ירד {n}%',
    shortlist_score_minutes: '+0.5: שחקן קבוע (1500+ דקות)',
    shortlist_score_productive: '+0.5: פרודוקטיבי (5+ שערים+אסיסטים)',
    shortlist_matches_requests: 'מתאים ל-{n} בקשות',
    shortlist_free_agent: 'Free Agent',
    shortlist_contract_expiring: 'חוזה בעוד {n} חודשים',
    shortlist_value_dropped: 'ערך ירד {n}%',
    shortlist_value_rose: 'ערך +{n}%',
    shortlist_data_stale: 'נתונים מלפני {n} ימים',
    shortlist_refreshed_ago: 'עודכן לפני {n}',
    shortlist_refresh: 'רענן',
    shortlist_refresh_tooltip: 'עדכן מידע על השחקן מ-Transfermarkt (שם, ערך, מועדון, חוזה)',
    shortlist_performance: 'ביצועים {season}',
    shortlist_performance_loading: 'טוען...',
    shortlist_no_matches: 'אין התאמות לבקשות',
    shortlist_dossier: 'דוסייה',
    shortlist_appearances: 'הופעות',
    shortlist_goals: 'שערים',
    shortlist_assists: 'אסיסטים',
    shortlist_minutes: 'דקות',
    shortlist_open_transfermarkt: 'פתח ב-Transfermarkt',
    shortlist_filter_empty: 'אין שחקנים שמתאימים לסינון',
    shortlist_filter_empty_hint: 'נסה סינון אחר או הצג את כל {n} השחקנים.',
    shortlist_filter_clear: 'הצג הכל',
    shortlist_showing_filtered: 'מציג {showing} מתוך {total} שחקנים',
    common_cancel: 'ביטול',
    contacts_title: 'אנשי קשר',
    contacts_title_women: 'אנשי קשר',
    contacts_all: 'הכל',
    contacts_clubs: 'מועדונים',
    contacts_agencies: 'סוכנויות',
    contacts_loading: 'טוען אנשי קשר...',
    contacts_loading_women: 'טוען אנשי קשר...',
    contacts_empty: 'אין אנשי קשר עדיין',
    contacts_empty_women: 'אין אנשי קשר עדיין',
    contacts_contact: 'איש קשר',
    contacts_add: 'הוסף איש קשר',
    contacts_add_title: 'הוסף איש קשר',
    contacts_add_name: 'שם',
    contacts_add_name_placeholder: 'שם איש הקשר',
    contacts_add_name_required: 'שם נדרש',
    contacts_add_phone: 'טלפון',
    contacts_add_phone_placeholder: '+1234567890',
    contacts_add_type: 'סוג',
    contacts_add_club_name: 'שם מועדון',
    contacts_add_club_name_placeholder: 'למשל צ\'לסי',
    contacts_add_club_country: 'מדינת מועדון',
    contacts_add_club_country_placeholder: 'למשל אנגליה',
    contacts_add_agency_name: 'שם סוכנות',
    contacts_add_agency_name_placeholder: 'למשל CAA Stellar',
    contacts_add_agency_country: 'מדינת סוכנות',
    contacts_add_agency_country_placeholder: 'למשל ארה"ב',
    contacts_add_role: 'תפקיד',
    contacts_add_save: 'שמור איש קשר',
    contacts_edit: 'ערוך',
    contacts_edit_title: 'ערוך איש קשר',
    contacts_edit_save: 'שמור שינויים',
    contacts_delete: 'מחק',
    contacts_delete_confirm: 'למחוק את {name}? לא ניתן לבטל.',
    transfer_windows_title: 'חלונות העברה פתוחים',
    transfer_windows_days_left: '{n} ימים נותרו',
    transfer_windows_today: 'היום',
    transfer_windows_open: 'פתוח',
    transfer_windows_empty: 'אין חלונות העברה פתוחים כרגע.',
    transfer_windows_closing_soon: '{n} נסגרים בקרוב',
    transfer_windows_group_priority: 'שווקים עיקריים',
    transfer_windows_group_uefa: 'אירופה (UEFA)',
    transfer_windows_group_conmebol: 'דרום אמריקה (CONMEBOL)',
    transfer_windows_group_concacaf: 'צפון ומרכז אמריקה (CONCACAF)',
    transfer_windows_group_afc: 'אסיה (AFC)',
    transfer_windows_group_caf: 'אפריקה (CAF)',
    transfer_windows_group_ofc: 'אוקיאניה (OFC)',
    releases_title: 'שחרורים אחרונים',
    releases_loading: 'טוען שחרורים...',
    releases_empty: 'אין שחרורים בטווח זה',
    releases_try_filter: 'נסה טווח שווי אחר',
    releases_all: 'הכל',
    releases_add: 'הוסף',
    releases_free_agent: 'שחקן חופשי',
    releases_progress: 'עמוד {page} • {total} שחקנים',
    releases_progress_ranges: 'טווח {range}/{totalRanges} • {total} שחקנים',
    releases_position: 'עמדה',
    releases_age: 'גיל',
    releases_age_all: 'כל הגילאים',
    releases_age_u23: 'מתחת ל-23',
    releases_age_23_30: '23-30',
    releases_age_30plus: '30+',
    releases_search: 'חפש לפי שם...',
    releases_stats_total: 'סה״כ',
    releases_stats_showing: 'מוצג',
    releases_sort: 'מיון לפי',
    releases_sort_value: 'שווי שוק',
    releases_sort_date: 'תאריך שחרור',
    releases_sort_age: 'גיל',
    releases_value_filter: 'טווח שווי',
    releases_reload: 'טען מחדש',
    releases_roster_teammates: '{count} שחקן מהמאגר שיחק איתו',
    releases_roster_teammates_tap: 'שחקנים מהמאגר ששיחקו איתו',
    releases_no_roster_teammates: 'אין שחקנים מהמאגר ששיחקו עם שחקן זה',
    releases_roster_teammates_loading: 'טוען שחקנים…',
    releases_games_together: '{n} משחקים ביחד',
    releases_bookmark: 'שמור',
    releases_saved: 'נשמר',
    releases_view_shortlist: 'צפה ברשימה',
    releases_stat_shortlisted: 'נשמרו',
    returnee_title: 'חזרו מהשאלה',
    returnee_subtitle: 'שחקנים שחוזרים מהשאלה בליגות אירופאיות',
    returnee_no_found: 'לא נמצאו שחקנים שחזרו',
    returnee_loading: 'טוען ({loaded}/{total} ליגות)…',
    returnee_stat_leagues: 'ליגות',
    returnee_all_count: 'הכל {count}',
    returnee_badge_loan_return: 'חזר מהשאלה',
    returnee_badge_returned_on: 'חזר ב-{date}',
    returnee_clear_filters: 'נקה סינון',
    returnee_current_club: 'מועדון נוכחי',
    returnee_returned: 'חזר',
    returnee_market_value: 'שווי שוק',
    requests_title: 'בקשות מועדונים',
    requests_subtitle: 'בקשות שחקנים ממועדונים לפי עמדה',
    requests_title_women: 'בקשות מועדונים',
    requests_subtitle_women: 'בקשות שחקניות ממועדונים לפי עמדה',
    ai_scout_title: 'מצא את ההחתמה הבאה שלך',
    ai_scout_subtitle: 'תאר את השחקן שאתה צריך בשפה חופשית. ה-AI מחפש באלפי פרופילים כדי למצוא את ההתאמות הטובות ביותר.',
    ai_scout_placeholder: 'למשל: מצא לי 20 חלוצים עד גיל 26 שהם מהירים מאוד עם לפחות 5 שערים בעונה שעברה',
    ai_scout_search: 'חפש',
    ai_scout_searching: 'מחפש…',
    ai_scout_searching_hint: 'בדרך כלל 10–20 שניות',
    ai_scout_local_testing: 'הוסף GEMINI_API_KEY ל-.env.local לניתוח AI. בלעדיו מוצגות תוצאות מדומות.',
    ai_scout_examples: 'דוגמאות לחיפוש:',
    ai_scout_results_count: '{count} תוצאות',
    ai_scout_results_of: '{count} מתוך {total} תוצאות',
    ai_scout_no_results: 'אין תוצאות. נסה חיפוש אחר.',
    ai_scout_interpretation: 'איך ה-AI הבין את הבקשה:',
    requests_loading: 'טוען בקשות...',
    requests_loading_women: 'טוען בקשות...',
    requests_loading_youth: 'טוען בקשות...',
    requests_empty: 'אין בקשות מועדונים',
    requests_empty_women: 'אין עדיין בקשות מועדונים',
    requests_empty_youth: 'אין עדיין בקשות מועדוני נוער',
    requests_title_youth: 'בקשות מועדוני נוער',
    requests_subtitle_youth: 'בקשות שחקני נוער ממועדונים ואקדמיות לפי עמדה',
    requests_manual_club_hint_youth: 'הזן פרטי מועדון או אקדמיה באופן ידני',
    requests_no_match_youth: 'אין שחקני נוער במאגר התואמים לבקשה זו',
    requests_matching_players_one_youth: '{count} שחקן תואם במאגר',
    requests_matching_players_youth: '{count} שחקנים תואמים במאגר',
    requests_contact: 'איש קשר',
    requests_add: 'הוסף בקשה',
    requests_delete: 'מחק',
    requests_delete_confirm: 'למחוק בקשה עבור {club} ({position})?',
    requests_stat_total: 'סה״כ',
    requests_stat_positions: 'עמדות',
    requests_country_club_one: 'מועדון 1',
    requests_country_clubs: '{count} מועדונים',
    requests_notes_label: 'הערות',
    requests_phone: 'טלפון',
    requests_salary: 'שכר',
    requests_fee: 'דמי העברה',
    requests_fee_free_loan: 'חופשי / השאלה בחינם',
    requests_age_range: 'גיל',
    requests_foot: 'רגל',
    requests_add_title: 'הוסף בקשה',
    requests_edit_title: 'ערוך בקשה',
    requests_edit: 'ערוך',
    requests_eu_only: 'EU בלבד',
    requests_search_club: 'חפש מועדון…',
    requests_search_club_ifa: 'חפש מועדון בהתאחדות (אופציונלי)',
    requests_searching_clubs: 'מחפש בהתאחדות…',
    requests_no_clubs_found: 'לא נמצאו מועדונים. הזן ידנית למטה.',
    requests_search_for_club: 'חפש מועדון',
    requests_manual_club_hint: 'הזן פרטי מועדון (MGSR Women לא משתמש ב-Transfermarkt)',
    requests_club_name: 'שם המועדון',
    requests_club_country: 'מדינה',
    requests_change_club: 'שנה',
    requests_label_position: 'עמדה',
    requests_label_requirements: 'דרישות',
    requests_label_notes: 'הערות',
    requests_age_doesnt_matter: 'לא משנה',
    requests_min: 'מינ',
    requests_max: 'מקס',
    requests_label_salary: 'טווח משכורת',
    requests_label_fee: 'דמי העברה',
    requests_label_foot: 'רגל דומיננטית',
    requests_foot_left: 'שמאל',
    requests_foot_right: 'ימין',
    requests_foot_any: 'לא משנה',
    requests_notes_placeholder: 'הערות נוספות…',
    requests_save: 'שמור בקשה',
    requests_next: 'הבא',
    requests_step_club: 'מועדון',
    requests_step_position: 'עמדה',
    requests_step_requirements: 'דרישות',
    requests_step_notes: 'הערות',
    requests_matching_players_one: '{count} שחקן תואם במאגר',
    requests_matching_players: '{count} שחקנים תואמים במאגר',
    requests_matching_players_one_women: '{count} שחקנית תואמת במאגר',
    requests_matching_players_women: '{count} שחקניות תואמות במאגר',
    requests_no_match: 'אין שחקנים במאגר התואמים לבקשה זו',
    requests_no_match_women: 'אין שחקניות במאגר התואמות לבקשה זו',
    requests_find_players_online: 'מצא שחקנים באמצעות AI Scout',
    requests_online_players_loading: 'AI Scout מחפש…',
    requests_online_players_empty: 'לא נמצאו שחקנים תואמים ברשת',
    requests_online_match_score: 'התאמה: {pct}%',
    add_player_title: 'הוסף שחקן',
    add_to_shortlist_title: 'הוסף לרשימת מעקב',
    add_player_back: 'חזרה ל',
    add_player_paste_url: 'הדבק קישור Transfermarkt',
    add_player_load: 'טען',
    add_player_loading: 'טוען...',
    add_player_search: 'או חפש לפי שם',
    add_player_search_btn: 'חפש',
    add_player_searching: 'מחפש...',
    add_player_confirm: 'אישור והוספה',
    add_player_to_roster: 'הוסף לסגל',
    add_player_saving: 'שומר...',
    add_player_placeholder_url: 'https://www.transfermarkt.com/...',
    add_player_placeholder_search: 'שם שחקן...',
    add_player_auto_search_hint: 'תוצאות מופיעות בזמן הקלדה',
    add_player_no_results: 'לא נמצאו שחקנים. נסה שם אחר.',
    add_player_from_shortlist_hint: 'הוסף שחקן זה מרשימת המעקב לסגל שלך',
    add_player_shortlist_hint: 'הוסף שחקן זה לרשימת המעקב להמשך',
    add_player_roster_hint: 'הוסף שחקן חדש לסגל שלך',
    add_player_contact_section: 'איש קשר (אופציונלי)',
    add_woman_player_title: 'הוסף שחקנית',
    add_woman_player_subtitle: 'חפש לפי שם (SoccerDonna, Wosostat, FMInside) או הוסף ידנית.',
    add_woman_player_search_placeholder: 'חפש לפי שם (למשל לורן ג\'יימס)',
    add_woman_player_searching: 'מחפש…',
    add_woman_player_no_results: 'לא נמצאו תוצאות. הוסף ידנית למטה.',
    add_woman_player_add_manually: 'הוסף ידנית (הזן את כל הפרטים)',
    add_woman_player_or_manual: 'או',
    add_woman_player_add_manually_link: 'הוסף ידנית',
    add_woman_player_with_details: 'עם כל הפרטים.',
    add_woman_player_paste_url_hint: 'השחקנית לא בתוצאות? הדבק קישור פרופיל SoccerDonna לטעינת פרטים:',
    add_woman_player_url_placeholder: 'https://www.soccerdonna.de/en/.../profil/spieler_12345.html',
    add_woman_player_load: 'טען',
    add_woman_player_loading: 'טוען…',
    add_woman_player_duplicate_error: 'שחקנית עם קישור SoccerDonna זה כבר בסגל',
    add_woman_player_full_name: 'שם מלא *',
    add_woman_player_full_name_placeholder: 'למשל לורן ג\'יימס',
    add_woman_player_positions: 'עמדה/ות',
    add_woman_player_club: 'מועדון',
    add_woman_player_club_placeholder: 'למשל צ\'לסי',
    add_woman_player_age: 'גיל',
    add_woman_player_age_placeholder: 'למשל 23',
    add_woman_player_nationality: 'לאום',
    add_woman_player_nationality_placeholder: 'למשל אנגליה',
    add_woman_player_market_value: 'שווי שוק',
    add_woman_player_market_value_placeholder: 'למשל €500k (SoccerDonna)',
    add_woman_player_soccerdonna_url: 'קישור פרופיל SoccerDonna',
    add_woman_player_soccerdonna_hint: 'אופציונלי. משמש לבדיקת כפילויות והעשרה עתידית.',
    add_woman_player_fminside_url: 'קישור פרופיל FMInside',
    add_woman_player_fminside_url_hint: 'הדבק קישור שחקנית FMInside לנתוני FM ישירים',
    add_woman_player_profile_image: 'קישור תמונת פרופיל',
    add_woman_player_notes: 'הערות',
    add_woman_player_notes_placeholder: 'הערות סקאוט, מזהה Wosostat/FMInside...',
    add_woman_player_saving: 'שומר…',
    add_woman_player_to_roster: 'הוסף לסגל',
    add_woman_player_image_preview: 'תצוגה מקדימה לתמונה',
    add_woman_player_search_image: 'חפש תמונה',
    add_woman_player_searching_image: 'מחפש…',
    add_woman_player_load_profile: 'טוען פרופיל…',
    add_woman_player_fetch_failed_select: 'לא ניתן לטעון את הפרופיל המלא. פרטים בסיסיים מולאו מהחיפוש—ניתן לערוך למטה.',
    add_woman_player_fetch_failed_url: 'לא ניתן לטעון את הפרופיל. בדוק את הקישור ונסה שוב.',
    woman_player_edit: 'ערוך',
    woman_player_delete: 'מחק',
    woman_player_delete_confirm: 'למחוק שחקנית זו מהסגל?',
    woman_player_delete_confirm_name: 'למחוק את {name}?',
    woman_player_save: 'שמור',
    woman_player_cancel: 'ביטול',
    player_info_back: 'חזרה לשחקנים',
    player_info_back_players: 'חזרה לשחקנים',
    player_info_back_requests: 'חזרה לבקשות',
    player_info_back_releases: 'חזרה לשחרורים',
    player_info_back_contract_finisher: 'חזרה למסיימי חוזה',
    player_info_back_shadow_teams: 'חזרה לקבוצת צללים',
    player_info_back_tasks: 'חזרה למשימות',
    player_info_back_dashboard: 'חזרה ללוח בקרה',
    player_info_notes: 'הערות',
    player_info_no_notes: 'אין הערות עדיין',
    player_info_add_note: 'הוסף הערה',
    player_info_edit_note: 'ערוך הערה',
    player_info_delete_note: 'מחק הערה',
    player_info_delete_note_confirm: 'האם אתה בטוח שברצונך למחוק את ההערה?',
    player_info_note_placeholder: 'הוסף הערה חדשה…',
    player_info_note_save: 'שמור',
    player_info_note_cancel: 'ביטול',
    player_info_agent: 'סוכן',
    player_info_age: 'גיל',
    player_info_height: 'גובה',
    player_info_contract: 'חוזה',
    player_info_not_found: 'שחקן לא נמצא',
    player_info_overview: 'סקירה',
    player_info_stats: 'סטטיסטיקות',
    player_info_club: 'מועדון נוכחי',
    player_info_contact: 'איש קשר',
    player_info_mandate: 'מנדט',
    player_info_documents: 'מסמכים',
    player_info_add_document: 'הוסף מסמך',
    player_info_no_documents: 'אין מסמכים עדיין',
    player_info_uploading: 'מעלה מסמך…',
    player_info_documents_empty_subtitle: 'העלה דרכונים, מנדטים, מסמכים רפואיים או קבצים אחרים.',
    player_info_delete_doc_confirm: 'האם אתה בטוח שברצונך למחוק',
    player_info_cd_open_link: 'פתח קישור',
    player_info_cd_delete_document: 'מחק מסמך',
    player_info_generate_mandate: 'יצירת מנדט',
    player_info_share: 'שתף',
    player_info_prepare_portfolio: 'הכן לפורטפוליו',
    player_info_added_to_portfolio: 'נוסף לפורטפוליו',
    player_info_portfolio_scout_failed: 'לא ניתן להכין דוח סקאוט. נסה שוב.',
    player_info_portfolio_adding: 'מכין…',
    mandate_no_passport: 'אין פרטי דרכון. העלה מסמך דרכון תחילה.',
    mandate_step_agent: 'בחר סוכן',
    mandate_no_agents_fifa: 'לא נמצאו סוכנים עם רישיון פיפ״א',
    mandate_fifa_license: 'רישיון פיפ״א',
    mandate_step_validity: 'תוקף וליגות',
    mandate_expiry_date: 'תאריך תפוגה',
    mandate_valid_leagues: 'ליגות תקפות',
    mandate_search_country: 'חפש מדינה...',
    mandate_add_country_league: 'הוסף מדינה / ליגה',
    mandate_entire_country: 'כל המדינה (כל המועדונים)',
    mandate_sheet_search_clubs: 'חפש מועדונים ב-%s…',
    mandate_selected_clubs: '%d מועדון(ים) נבחרו',
    mandate_sheet_add_button: 'הוסף למנדט',
    mandate_change_country: 'שנה',
    mandate_selected: 'נבחרו',
    mandate_step_review: 'סיכום',
    mandate_review_player: 'שחקן',
    mandate_review_agent: 'סוכן',
    mandate_review_fifa_id: 'מספר רישיון פיפ״א',
    mandate_back: 'חזרה',
    mandate_next: 'הבא',
    mandate_generating: 'מייצר...',
    mandate_generate_pdf: 'יצירת PDF',
    upload_failed: 'ההעלאה נכשלה. נסה שוב.',
    passport_already_exists: 'לשחקן זה כבר יש פרטי דרכון. מחק תחילה את מסמך הדרכון הקיים.',
    player_info_value_history: 'היסטוריית שווי',
    player_info_value_peak: 'שיא',
    player_info_value_low: 'נמוך',
    player_info_value_change: 'שינוי',
    player_info_value_points: 'נקודות נתונים',
    player_info_foot: 'רגל מועדפת',
    player_info_on_loan: 'בהשאלה מ',
    player_info_salary: 'טווח משכורת',
    player_info_transfer_fee: 'דמי העברה',
    player_info_salary_fee_title: 'שכר ודמי העברה',
    player_info_salary_fee_save: 'שמור',
    player_info_salary_fee_clear: 'נקה',
    player_info_salary_fee_not_set: 'לא הוגדר',
    player_info_agency: 'סוכנות',
    player_info_view_on_tm: 'צפה ב-Transfermarkt',
    player_info_refresh: 'רענן נתונים',
    similar_players_title: 'שחקנים דומים',
    similar_players_find: 'מצא שחקנים דומים',
    similar_players_searching: 'מחפש שחקנים דומים…',
    similar_players_match: 'התאמה',
    similar_players_style: 'סגנון',
    similar_players_nationality: 'לאום',
    similar_players_league: 'ליגה',
    similar_players_height: 'גובה',
    similar_players_foot: 'רגל',
    similar_players_contract: 'חוזה',
    similar_players_view_profile: 'צפה ב-Transfermarkt',
    similar_players_load_more: 'טען עוד שחקנים דומים',
    similar_players_retry: 'נסה שוב',
    similar_players_empty: 'לא נמצאו שחקנים דומים',
    similar_players_per90: 'ל-90 דקות',
    similar_players_growth: 'צמיחה',
    similar_players_club: 'מועדון',
    similar_players_sources_hint: 'הניתוח משלב נתוני Transfermarkt, סטטיסטיקות FBref ונתוני FM',
    similar_players_women_title: 'שחקניות דומות',
    similar_players_view_soccerdonna: 'צפה ב-SoccerDonna',
    similar_players_view_fminside: 'צפה ב-FMInside',
    similar_players_resolving: 'מאתר פרופילים…',
    player_info_mandate_active: 'פעיל',
    player_info_mandate_inactive: 'לא פעיל',
    player_info_mandate_expires: 'תוקף מנדט: %s',
    player_info_doc_expired: 'פג תוקף',
    player_info_nationality: 'לאום',
    player_info_foot_left: 'שמאל',
    player_info_foot_right: 'ימין',
    player_info_foot_both: 'שתיהן',
    player_info_matching_requests: 'בקשות תואמות',
    player_info_matching_requests_empty: 'אין בקשות תואמות',
    player_info_matching_requests_empty_subtitle: 'מועדונים עם בקשות התואמות לשחקן זה יופיעו כאן',
    player_info_matching_requests_mark_offered: 'סמן כהוצע',
    player_info_matching_requests_offered: 'הוצע',
    player_info_matching_requests_offered_date: 'הוצע: %s',
    player_info_matching_requests_by_agent: 'על ידי %s',
    player_info_matching_requests_club_feedback: 'משוב מועדון',
    player_info_matching_requests_add_feedback: 'הוסף משוב',
    player_info_matching_requests_edit_feedback: 'ערוך משוב',
    player_info_matching_requests_add_feedback_title: 'הוסף משוב מועדון',
    player_info_matching_requests_edit_feedback_title: 'עריכת משוב מועדון',
    player_info_matching_requests_offer_date: 'תאריך הצעה',
    player_info_matching_requests_feedback_hint: 'משוב מועדון (אופציונלי)',
    player_info_matching_requests_feedback_placeholder: 'הערות מהמועדון…',
    player_info_matching_requests_cancel: 'ביטול',
    proposal_history_title: 'היסטוריית הצעות',
    proposal_history_status_deleted: 'הבקשה נמחקה',
    proposal_history_status_fulfilled: 'הושלם',
    proposal_history_status_active: 'פעיל',
    proposal_history_status_legacy: 'הוצע בעבר',
    proposal_history_feedback: 'פידבק מהמועדון',
    proposal_history_no_feedback: 'לא נרשם פידבק',
    proposal_history_summary: 'סיכום סוכן',
    proposal_history_add_summary: 'הוסף סיכום…',
    proposal_history_summary_hint: 'לדוגמה: העסקה נפלה — השחקן סירב לתנאים',
    proposal_history_summary_save: 'שמור',
    proposal_history_by_agent: 'ע״י %s',
    proposal_history_show_all: 'הצג הכל (%s)',
    proposal_history_show_less: 'הצג פחות',
    player_info_save_note: 'שמור',
    player_info_added_by: 'נוסף על ידי',
    player_info_agent_phone: 'טלפון סוכן',
    player_info_player_phone: 'טלפון שחקן',
    player_info_player_phone_women: 'טלפון שחקנית',
    contact_add_phone: 'הוסף טלפון',
    contact_add_agent_phone: 'הוסף טלפון סוכן',
    contact_add_player_phone: 'הוסף טלפון שחקן',
    contact_edit_phone: 'ערוך טלפון',
    contact_delete_phone: 'מחק טלפון',
    contact_confirm_delete: 'מחק',
    save: 'שמור',
    cancel: 'ביטול',
    note_written_by: 'נכתב על ידי',
    login_title: 'MGSR Team',
    login_subtitle: 'התחבר לחשבון שלך',
    login_email: 'אימייל',
    login_password: 'סיסמה',
    login_sign_in: 'התחבר',
    login_signing_in: 'מתחבר...',
    login_hint: 'השתמש באותם פרטי התחברות כמו באפליקציית האנדרואיד',
    common_or: 'או',
    common_years: 'שנים',
    search_no_results: 'לא נמצאו תוצאות',
    search_placeholder: 'חפש לפי שם, עמדה או מועדון...',
    contact_type_club: 'מועדון',
    contact_type_agency: 'סוכנות',
    contact_role_other: 'אחר',
    contact_role_coach: 'מאמן',
    contact_role_asst_coach: 'מאמן משנה',
    contact_role_sport_dir: 'מנהל ספורט',
    contact_role_board: 'דירקטוריון',
    contact_role_ceo: 'מנכ"ל',
    contact_role_president: 'נשיא',
    contact_role_scout: 'סקאוט / אנליסט',
    contact_role_agent: 'סוכן',
    contact_role_intermediary: 'מתווך',
    contact_role_agency_dir: 'מנהל סוכנות',
    no_club: 'ללא מועדון',
    without_club: 'ללא מועדון',
    eu_nat_tag: 'אזרח EU',
    nav_shadow_teams: 'קבוצת צללים',
    nav_contract_finisher: 'מסיימי חוזה',
    nav_portfolio: 'פורטפוליו',
    portfolio_title: 'פורטפוליו',
    portfolio_subtitle: 'שחקנים מוכנים לשיתוף עם דוח סקאוט מלא. שתף בוואטסאפ בלחיצה אחת.',
    portfolio_subtitle_women: 'שחקניות מוכנות לשיתוף עם דוח סקאוט מלא. שתף בוואטסאפ בלחיצה אחת.',
    portfolio_empty_title: 'הפורטפוליו ריק',
    portfolio_empty_hint: 'הוסף שחקנים מעמוד הפרופיל שלהם באמצעות "הכן לפורטפוליו". לכל שחקן יהיה דוח סקאוט מוכן.',
    portfolio_empty_hint_women: 'הוסף שחקניות מעמוד הפרופיל שלהן באמצעות "הכן לפורטפוליו". לכל שחקנית יהיה דוח סקאוט מוכן.',
    portfolio_browse_players: 'עיין בשחקנים',
    portfolio_browse_players_women: 'עיין בשחקניות',
    portfolio_back_to_player: 'חזרה לפרופיל השחקן',
    portfolio_share: 'שתף',
    portfolio_view: 'צפה',
    portfolio_version_hebrew: 'גרסה עברית',
    portfolio_version_english: 'גרסה אנגלית',
    portfolio_share_attach_contact: 'לצרף את מספר הטלפון של השחקן?',
    portfolio_share_attach_player_contact: 'הוסף איש קשר שחקן',
    portfolio_share_attach_agency_contact: 'הוסף איש קשר סוכנות',
    portfolio_share_no_contact: 'אין מספר טלפון של השחקן.',
    portfolio_share_cancel: 'ביטול',
    portfolio_share_via_whatsapp: 'שתף ב-WhatsApp',
    contract_finisher_title: 'מסיימי חוזה',
    contract_finisher_subtitle_summer: 'חוזים שמסתיימים לקראת חלון קיץ',
    contract_finisher_subtitle_winter: 'חוזים שמסתיימים לקראת חלון חורף',
    contract_finisher_loading: 'טוען…',
    contract_finisher_loading_more: 'טוען עוד…',
    contract_finisher_retry: 'נסה שוב',
    contract_finisher_badge: 'תאריך סיום חוזה',
    contract_finisher_no_found: 'לא נמצאו מסיימי חוזה בטווח זה',
    contract_finisher_no_match_filters: 'אין שחקנים התואמים את הסינון',
    contract_finisher_clear_filters: 'נקה סינון',
    contract_finisher_apply_filters: 'החל סינון',
    contract_finisher_filter_age_all: 'הכל',
    contract_finisher_filter_age_18_21: '18-21',
    contract_finisher_filter_age_22_25: '22-25',
    contract_finisher_filter_age_26_29: '26-29',
    contract_finisher_filter_age_30_plus: '30+',
    contract_finisher_filter_value_all: 'הכל',
    contract_finisher_filter_value_150k_500k: '€150K–500K',
    contract_finisher_filter_value_500k_1m: '€500K–1M',
    contract_finisher_filter_value_1m_2m: '€1M–2M',
    contract_finisher_filter_value_2m_3m: '€2M–3M',
    contract_finisher_filter_label_value: 'שווי',
    contract_finisher_filter_label_position: 'עמדה',
    contract_finisher_filter_label_age: 'גיל',
    contract_finisher_filter_label_region: 'אזור',
    contract_finisher_stats_total: 'סה״כ',
    contract_finisher_stats_shortlisted: 'ברשימה',
    contract_finisher_stats_visible: 'מוצג',
    contract_finisher_filters: 'סינון',
    roster_analytics_title: 'ניתוח סגל',
    roster_analytics_position: 'לפי עמדה',
    roster_analytics_age: 'לפי גיל',
    roster_analytics_value: 'לפי שווי שוק',
    roster_analytics_contracts: 'חוזים מסתיימים',
    roster_analytics_mandates: 'סטטוס מנדט',
    roster_analytics_with_mandate: 'עם מנדט',
    roster_analytics_without_mandate: 'ללא מנדט',
    roster_analytics_age_u21: 'מתחת ל-21',
    roster_analytics_age_22_25: '22-25',
    roster_analytics_age_26_29: '26-29',
    roster_analytics_age_30_plus: '30+',
    roster_analytics_value_unknown: 'לא ידוע',
    roster_analytics_value_0_500k: '0-500K',
    roster_analytics_value_500k_1m: '500K-1M',
    roster_analytics_value_1m_5m: '1M-5M',
    roster_analytics_value_5m_plus: '5M+',
    players_filter_free_agents: 'שחקנים חופשיים',
    players_filter_contract_expiring: 'חוזה מסתיים',
    players_filter_with_mandate: 'עם מנדט',
    players_with_mandate_title: 'שחקנים עם מנדט',
    players_mandate_expires_label: 'בתוקף עד:',
    players_filter_my_players_only: 'השחקנים שלי בלבד',
    players_filter_agent: 'סוכן',
    players_filter_loan_players_only: 'שחקנים בהשאלה בלבד',
    players_filter_without_registered_agent: 'ללא סוכן רשום',
    players_filter_with_notes: 'עם הערות',
    players_filter_foot_left: 'רגל שמאל',
    players_filter_foot_right: 'רגל ימין',
    players_filter_eu_national: 'אזרחות EU',
    players_filter_offered_no_feedback: 'הוצע · ללא משוב',
    players_filter_position_gk: 'שוערים',
    players_filter_position_gk_women: 'שוערות',
    players_filter_position_def: 'הגנה',
    players_filter_position_mid: 'קישור',
    players_filter_position_fwd: 'התקפה',
    players_filter_clear: 'נקה מסננים',
    shadow_teams_title: 'קבוצת צללים',
    shadow_teams_subtitle: 'השחקנים המועדפים שלך לחלון ההעברות הבא',
    shadow_teams_formation: 'מערך',
    shadow_teams_hint: 'החלף טאבים לראות את הקבוצות • הטאב שלך: הוסף, ערוך, הסר • אחרים: צפייה בפרופיל בלבד',
    shadow_teams_bench: 'ספסל',
    shadow_teams_select_player: 'בחר שחקן',
    shadow_teams_search_player: 'חפש שחקן',
    shadow_teams_no_players: 'לא נמצאו שחקנים לעמדה זו',
    shadow_teams_cancel: 'ביטול',
    shadow_teams_view_player: 'צפה בפרופיל',
    shadow_teams_change_player: 'החלף שחקן',
    shadow_teams_remove_player: 'הסר',
    shadow_teams_you: 'אתה',
    // Player Highlights
    highlights_title: 'היילייטס',
    highlights_loading: 'טוען הדגשות...',
    highlights_empty: 'לא נמצאו סרטוני הדגשות לשחקן זה',
    highlights_error: 'לא ניתן לטעון הדגשות',
    highlights_recent_matches: 'הדגשות משחקים אחרונים',
    highlights_compilations: 'הדגשות שחקן',
    highlights_powered_by: 'מבוסס על YouTube ו-Scorebat',
    highlights_updated: 'עודכן',
    highlights_refresh: 'רענן',
    highlights_retry: 'נסה שוב',
    highlights_views: 'צפיות',
    highlights_disclaimer: 'הסרטונים שבחרת יוצגו כחלק מפרופיל השחקן עד להחלפה.',
    highlights_select_up_to: 'בחר עד 2 סרטונים',
    highlights_saving: 'שומר...',
    highlights_confirm_selection: 'אישור בחירה',
    highlights_replace_videos: 'החלף סרטונים',
    highlights_confirm_replacement: 'אישור החלפה',
    highlights_cancel: 'ביטול',
    highlights_pinned_count: '{n} קבועים',
    // FM Intelligence Panel
    fm_section_title: 'תובנות FM',
    fm_empty_title: 'לא במסד הנתונים של FM',
    fm_empty_subtitle: 'לשחקן הזה אין נתוני Football Manager עדיין. תובנות FM יהפכו לזמינות ברגע שהשחקן יופיע במסד הנתונים של FM.',
    fm_tab_intelligence: 'תובנות FM',
    fm_tab_position_fit: 'התאמת עמדה',
    fm_loading: 'טוען תובנות FM...',
    fm_current_ability: 'יכולת נוכחית',
    fm_pa_label: 'יכולת פוטנציאלית',
    fm_potential: 'פוטנציאל',
    fm_at_peak: 'בשיא',
    fm_best_fit: 'התאמה מיטבית:',
    fm_ability_dimensions: 'ממדי יכולת',
    fm_top_attributes: 'תכונות חזקות',
    fm_weaknesses: 'חולשות',
    fm_no_weaknesses: 'אין חולשות משמעותיות',
    fm_position_rankings: 'דירוג עמדות',
    fm_fit: 'התאמה',
    fm_footer: 'נתונים מ-Football Manager דרך FMInside',
    fm_loading_women: 'טוען נתוני FMInside...',
    fm_empty_title_women: 'לא נמצאו נתוני FM',
    fm_no_match_women: 'לא נמצאה שחקנית תואמת ב-FMInside (מאגר נשים). נסה לבדוק את איות השם או להוסיף פרטים.',
    fm_no_match_load_failed: 'נמצאה התאמה אפשרית אך לא ניתן היה לטעון את הפרטים.',
    fm_no_match_error: 'שגיאה בטעינת נתוני FMInside.',
    fm_paste_url_hint: 'מצאת אותה ב-FMInside? הדבק את קישור הפרופיל שלה להלן.',
    fm_paste_url_placeholder: 'https://fminside.net/players/7-fm-26/...',
    fm_paste_apply: 'טען',
    fm_search_on_site: 'חפש באתר FMInside',
    fm_left_foot: 'רגל שמאל',
    fm_right_foot: 'רגל ימין',
    // FM Tiers
    fm_tier_unknown: 'לא ידוע',
    fm_tier_world_class: 'ברמה עולמית',
    fm_tier_elite: 'עילית',
    fm_tier_top_league: 'ליגה עליונה',
    fm_tier_solid_pro: 'מקצוען מוצק',
    fm_tier_lower_league: 'ליגה נמוכה',
    fm_tier_prospect: 'כשרון צעיר',
    // FM Dimensions
    fm_dim_technical: 'טכני',
    fm_dim_mental: 'מנטלי',
    fm_dim_physical: 'פיזי',
    fm_dim_set_pieces: 'כדורים עומדים',
    fm_dim_attacking: 'התקפי',
    fm_dim_defending: 'הגנתי',
    fm_dim_creative: 'יצירתי',
    fm_dim_aerial: 'אווירי',
    fm_dim_pace_power: 'מהירות וכוח',
    fm_dim_work_ethic: 'אתיקת עבודה',
    // FM Positions
    fm_pos_ST: 'חלוץ',
    fm_pos_LW: 'כנף שמאל',
    fm_pos_RW: 'כנף ימין',
    fm_pos_AM: 'קישור התקפי',
    fm_pos_LM: 'קשר שמאל',
    fm_pos_RM: 'קשר ימין',
    fm_pos_CM: 'קשר מרכזי',
    fm_pos_DM: 'קשר הגנתי',
    fm_pos_LB: 'מגן שמאל',
    fm_pos_RB: 'מגן ימין',
    fm_pos_CB: 'בלם',
    fm_pos_GK: 'שוער',
    // FM Legend
    fm_legend_perfect: 'מושלם (85%+)',
    fm_legend_great: 'מעולה (72-84%)',
    fm_legend_decent: 'סביר (58-71%)',
    fm_legend_possible: 'אפשרי (40-57%)',
    fm_legend_poor: 'חלש',
    // FM Attributes
    fm_attr_crossing: 'הרמות',
    fm_attr_dribbling: 'כדרור',
    fm_attr_finishing: 'סיום',
    fm_attr_first_touch: 'נגיעה ראשונה',
    fm_attr_heading: 'נגיחות',
    fm_attr_long_shots: 'בעיטות רחוקות',
    fm_attr_marking: 'סימון',
    fm_attr_passing: 'מסירות',
    fm_attr_tackling: 'תיקולים',
    fm_attr_technique: 'טכניקה',
    fm_attr_aggression: 'תוקפנות',
    fm_attr_anticipation: 'צפייה מראש',
    fm_attr_bravery: 'אומץ',
    fm_attr_composure: 'קור רוח',
    fm_attr_concentration: 'ריכוז',
    fm_attr_decisions: 'קבלת החלטות',
    fm_attr_determination: 'נחישות',
    fm_attr_flair: 'יצירתיות',
    fm_attr_leadership: 'מנהיגות',
    fm_attr_off_the_ball: 'תנועה ללא כדור',
    fm_attr_positioning: 'מיקום',
    fm_attr_teamwork: 'עבודת צוות',
    fm_attr_vision: 'ראייה',
    fm_attr_work_rate: 'קצב עבודה',
    fm_attr_acceleration: 'תאוצה',
    fm_attr_agility: 'זריזות',
    fm_attr_balance: 'שיווי משקל',
    fm_attr_jumping_reach: 'קפיצה',
    fm_attr_natural_fitness: 'כושר טבעי',
    fm_attr_pace: 'מהירות',
    fm_attr_stamina: 'סיבולת',
    fm_attr_strength: 'כוח',
    fm_attr_corners: 'קרנות',
    fm_attr_free_kick_taking: 'בעיטות חופשיות',
    fm_attr_long_throws: 'זריקות רחוקות',
    fm_attr_penalty_taking: 'פנדלים',

    // News & Rumors
    nav_news: 'חדשות ושמועות',
    news_title: 'חדשות ושמועות',
    news_subtitle: 'שמועות העברות וחדשות ליגות מהשווקים שלך',
    news_tab_all: 'הכל',
    news_tab_rumours: 'שמועות',
    news_tab_news: 'חדשות',
    news_search_placeholder: 'חיפוש שחקנים, מועדונים, כותרות...',
    news_from: 'מ',
    news_to: 'אל',
    news_probability: 'סיכוי',
    news_view_on_tm: 'צפה בטרנספרמרקט',
    news_add_shortlist: 'הוסף לשורטליסט',
    news_no_results: 'לא נמצאו חדשות או שמועות',
    news_loading: 'טוען חדשות אחרונות...',
    news_stat_rumours: 'שמועות',
    news_stat_news: 'כתבות חדשות',
    news_stat_leagues: 'ליגות',
    news_refresh: 'רענון',
    news_updated_ago: 'עודכן',
    news_source_tm: 'טרנספרמרקט',
    news_source_google: 'גוגל חדשות',
    news_all_leagues: 'הכל',
    news_open_article: 'פתח כתבה',
    news_market_value: 'שווי שוק',
    news_tag_database: 'במאגר',
    news_tag_shortlist: 'שורטליסט',
  },
};

const TYPE_KEYS: Record<string, string> = {
  MARKET_VALUE_CHANGE: 'market_value_change',
  CLUB_CHANGE: 'club_change',
  CONTRACT_EXPIRING: 'contract_expiring',
  NOTE_ADDED: 'note_added',
  NOTE_DELETED: 'note_deleted',
  PLAYER_ADDED: 'player_added',
  PLAYER_DELETED: 'player_deleted',
  BECAME_FREE_AGENT: 'free_agent',
  NEW_RELEASE_FROM_CLUB: 'new_release_from_club',
  MANDATE_EXPIRED: 'mandate_expired',
  MANDATE_UPLOADED: 'mandate_uploaded',
  MANDATE_SWITCHED_ON: 'mandate_switched_on',
  MANDATE_SWITCHED_OFF: 'mandate_switched_off',
  SHORTLIST_ADDED: 'shortlist_added',
  SHORTLIST_REMOVED: 'shortlist_removed',
  REQUEST_ADDED: 'request_added',
  REQUEST_DELETED: 'request_deleted',
  PLAYER_OFFERED_TO_CLUB: 'player_offered',
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem('mgsr-lang') as Lang | null;
    if (stored === 'he' || stored === 'en') setLangState(stored);
    setMounted(true);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (mounted) localStorage.setItem('mgsr-lang', l);
  };

  const value: LanguageContextValue = {
    lang,
    setLang,
    t: (k) => TRANSLATIONS[lang][k] ?? k,
    isRtl: lang === 'he',
  };

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

const TYPE_KEYS_WOMEN: Record<string, string> = {
  ...TYPE_KEYS,
  PLAYER_ADDED: 'player_added_women',
  PLAYER_DELETED: 'player_deleted_women',
  BECAME_FREE_AGENT: 'free_agent_women',
  PLAYER_OFFERED_TO_CLUB: 'player_offered_women',
};

const TYPE_KEYS_YOUTH: Record<string, string> = {
  ...TYPE_KEYS,
  PLAYER_ADDED: 'player_added_youth',
};

export function translateType(
  type: string,
  t: (k: string) => string,
  platform?: 'men' | 'women' | 'youth'
): string {
  const keys = platform === 'youth' ? TYPE_KEYS_YOUTH : platform === 'women' ? TYPE_KEYS_WOMEN : TYPE_KEYS;
  const key = keys[type];
  return key ? t(key) : type;
}
