'use client';

/**
 * MATCHDAY generator modal.
 *
 * Opened from the player card dialog. The player's likeness is always a
 * photograph someone here chose and uploaded — so this screen's first job is to
 * make sure one exists, and to refuse to generate until it does. Everything
 * else (teams, date, competition, crests) is sourced, and the poster itself is
 * rendered deterministically. Nothing is generated by a model.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { db } from '@/lib/firebase';
import type { MatchdayGenerateInput, MatchdayGenerateResult } from '@/lib/matchday/types';

/**
 * A fixture already resolved by the dossier's "next match" section. When this
 * is present the generator uses it verbatim (correct teams + the exact logos
 * the operator sees in the UI) instead of re-scraping — which is what produced
 * wrong crests (e.g. an unrelated "LASK" badge).
 */
export interface MatchdaySeedFixture {
  homeTeam: string;
  awayTeam: string;
  playerSide: 'home' | 'away';
  homeLogo: string | null;
  awayLogo: string | null;
  date: string;
  time: string | null;
  competition: string | null;
  round: string | null;
  venue: string | null;
}

export interface MatchdaySeed {
  playerId?: string;
  playerName: string;
  playerImage?: string | null;
  tmProfile?: string | null;
  club: string;
  clubCountry?: string | null;
  clubLogo?: string | null;
  instagramHandle?: string | null;
  /** Pre-resolved fixture from the dossier's next-match section (preferred). */
  fixture?: MatchdaySeedFixture | null;
}

interface Props {
  seed: MatchdaySeed;
  onClose: () => void;
}

const PROGRESS_STEPS = [
  'matchday_step_fixture',
  'matchday_step_photos',
  'matchday_step_logos',
  'matchday_step_render',
  'matchday_step_quality',
] as const;

const MAX_UPLOAD_BYTES = 15 * 1024 * 1024;

function clubKey(club: string): string {
  return club.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 120);
}

type Phase = 'idle' | 'running' | 'ready' | 'error';

export default function MatchdayGeneratorModal({ seed, onClose }: Props) {
  const { t } = useLanguage();
  const [phase, setPhase] = useState<Phase>('idle');
  const [activeStep, setActiveStep] = useState(0);
  const [result, setResult] = useState<MatchdayGenerateResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const stepTimer = useRef<ReturnType<typeof setInterval> | null>(null);

  // Curated photographs, loaded from the player and club records.
  const [playerPhotoUrl, setPlayerPhotoUrl] = useState<string | null>(null);
  const [stadiumPhotoUrl, setStadiumPhotoUrl] = useState<string | null>(null);
  const [assetsLoading, setAssetsLoading] = useState(true);
  const [uploading, setUploading] = useState<'player' | 'stadium' | null>(null);
  const [uploadError, setUploadError] = useState<string | null>(null);

  const clearTimer = () => {
    if (stepTimer.current) {
      clearInterval(stepTimer.current);
      stepTimer.current = null;
    }
  };

  useEffect(() => () => clearTimer(), []);

  useEffect(() => {
    let active = true;
    void (async () => {
      try {
        const { doc, getDoc } = await import('firebase/firestore');
        const [player, club] = await Promise.all([
          seed.playerId ? getDoc(doc(db, 'Players', seed.playerId)) : Promise.resolve(null),
          seed.club ? getDoc(doc(db, 'ClubAssets', clubKey(seed.club))) : Promise.resolve(null),
        ]);
        if (!active) return;
        setPlayerPhotoUrl((player?.data()?.matchdayPhotoUrl as string | undefined) ?? null);
        setStadiumPhotoUrl((club?.data()?.stadiumPhotoUrl as string | undefined) ?? null);
      } catch {
        /* absent records simply mean nothing has been curated yet */
      } finally {
        if (active) setAssetsLoading(false);
      }
    })();
    return () => {
      active = false;
    };
  }, [seed.playerId, seed.club]);

  const handleUpload = async (kind: 'player' | 'stadium', file: File) => {
    setUploadError(null);
    if (file.size > MAX_UPLOAD_BYTES) {
      setUploadError(t('matchday_upload_too_large'));
      return;
    }
    setUploading(kind);
    try {
      const imageDataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result));
        reader.onerror = () => reject(new Error('read failed'));
        reader.readAsDataURL(file);
      });
      const res = await fetch('/api/matchday/upload', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          kind,
          playerId: seed.playerId ?? null,
          club: seed.club,
          imageDataUrl,
        }),
      });
      const data = (await res.json()) as { url?: string; error?: string };
      if (!res.ok || !data.url) {
        setUploadError(data.error || t('matchday_upload_failed'));
        return;
      }
      if (kind === 'player') setPlayerPhotoUrl(data.url);
      else setStadiumPhotoUrl(data.url);
    } catch (err) {
      setUploadError(err instanceof Error ? err.message : t('matchday_upload_failed'));
    } finally {
      setUploading(null);
    }
  };

  const run = useCallback(async () => {
    clearTimer();
    setPhase('running');
    setError(null);
    setResult(null);
    setSaved(false);
    setActiveStep(0);

    // Advance the visible progress steps on a timer for UX; the real work runs
    // in one request. We stop advancing once the response lands.
    stepTimer.current = setInterval(() => {
      setActiveStep((s) => Math.min(s + 1, PROGRESS_STEPS.length - 1));
    }, 1400);

    const payload: MatchdayGenerateInput = {
      playerId: seed.playerId ?? null,
      playerName: seed.playerName,
      tmProfile: seed.tmProfile ?? null,
      club: seed.club,
      clubCountry: seed.clubCountry ?? null,
      clubLogo: seed.clubLogo ?? null,
      playerPhotoUrl,
      stadiumPhotoUrl,
    };

    try {
      const res = await fetch('/api/matchday/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = (await res.json()) as MatchdayGenerateResult & { error?: string };
      clearTimer();
      if (!res.ok) {
        setError(data.error || t('matchday_error_generic'));
        setPhase('error');
        return;
      }
      setActiveStep(PROGRESS_STEPS.length - 1);
      setResult(data);
      setPhase('ready');
    } catch (err) {
      clearTimer();
      setError(err instanceof Error ? err.message : t('matchday_error_generic'));
      setPhase('error');
    }
  }, [seed, playerPhotoUrl, stadiumPhotoUrl, t]);

  const handleDownload = () => {
    if (!result?.imageDataUrl) return;
    const a = document.createElement('a');
    a.href = result.imageDataUrl;
    a.download = `matchday-${seed.playerName.replace(/\s+/g, '-').toLowerCase()}.png`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  const handleSave = async () => {
    if (!result) return;
    setSaving(true);
    try {
      const res = await fetch('/api/matchday/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          generationId: result.generationId,
          playerId: seed.playerId ?? null,
          imageDataUrl: result.imageDataUrl,
        }),
      });
      if (res.ok) setSaved(true);
    } catch {
      /* non-fatal */
    } finally {
      setSaving(false);
    }
  };

  const facts = result?.facts;

  return (
    <div
      className="brit-modal-overlay matchday-overlay"
      role="dialog"
      aria-modal="true"
      aria-label={t('matchday_title')}
      onClick={(e) => {
        if (e.target === e.currentTarget && phase !== 'running') onClose();
      }}
    >
      <div className="brit-modal matchday-modal">
        <button className="brit-close" onClick={onClose} aria-label={t('room_close')} disabled={phase === 'running'}>
          ×
        </button>

        <div className="matchday-head">
          <h2>{t('matchday_title')}</h2>
          <div className="matchday-seed">
            <span className="matchday-seed-player">{seed.playerName}</span>
            <span className="matchday-seed-club">{seed.club}</span>
          </div>
        </div>

        {/* ── Idle: curated photographs, then generate ── */}
        {phase === 'idle' && (
          <div className="matchday-setup">
            <p className="matchday-hint">{t('matchday_intro')}</p>

            <div className="matchday-config">
              <AssetRow
                label={t('matchday_player_photo')}
                url={playerPhotoUrl}
                required
                loading={assetsLoading}
                busy={uploading === 'player'}
                hint={t('matchday_player_photo_hint')}
                replaceLabel={t('matchday_replace')}
                uploadLabel={t('matchday_upload')}
                missingLabel={t('matchday_photo_missing')}
                onPick={(file) => void handleUpload('player', file)}
              />
              <AssetRow
                label={t('matchday_stadium_photo')}
                url={stadiumPhotoUrl}
                required={false}
                loading={assetsLoading}
                busy={uploading === 'stadium'}
                hint={t('matchday_stadium_photo_hint')}
                replaceLabel={t('matchday_replace')}
                uploadLabel={t('matchday_upload')}
                missingLabel={t('matchday_optional')}
                onPick={(file) => void handleUpload('stadium', file)}
              />
            </div>

            {uploadError && <p className="matchday-upload-error">{uploadError}</p>}

            {!assetsLoading && !playerPhotoUrl ? (
              <p className="matchday-blocked">{t('matchday_blocked_no_photo')}</p>
            ) : null}

            <button
              className="brit-modal-action matchday-generate"
              onClick={run}
              disabled={assetsLoading || !playerPhotoUrl || uploading !== null}
            >
              {t('matchday_generate')}
            </button>
          </div>
        )}

        {/* ── Running: progress log ── */}
        {phase === 'running' && (
          <ul className="matchday-progress" aria-live="polite">
            {PROGRESS_STEPS.map((step, i) => (
              <li
                key={step}
                className={
                  i < activeStep ? 'done' : i === activeStep ? 'active' : 'pending'
                }
              >
                <span className="matchday-progress-dot" />
                {t(step)}
              </li>
            ))}
          </ul>
        )}

        {/* ── Error ── */}
        {phase === 'error' && (
          <div className="matchday-error">
            <p>{error}</p>
            <button className="brit-modal-action" onClick={run}>
              {t('matchday_regenerate')}
            </button>
          </div>
        )}

        {/* ── Ready: artwork + facts + actions ── */}
        {phase === 'ready' && result && facts && (
          <div className="matchday-result">
            <div className="matchday-canvas">
              {isRealImage(result.imageDataUrl) ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={result.imageDataUrl} alt={`MATCHDAY ${facts.playerName}`} />
              ) : (
                <div className="matchday-canvas-pending">
                  <strong>MATCHDAY</strong>
                  <span>{facts.playerName}</span>
                  <em>{t('matchday_render_pending')}</em>
                </div>
              )}
            </div>

            <div className="matchday-facts">
              <div className="matchday-facts-teams">
                {facts.homeTeam} <b>VS</b> {facts.awayTeam}
              </div>
              <div className="matchday-facts-line">
                {facts.date}
                {facts.time ? ` • ${facts.time}` : ''}
              </div>
              {(facts.competition || facts.round) && (
                <div className="matchday-facts-line muted">
                  {[facts.competition, facts.round].filter(Boolean).join(' • ')}
                </div>
              )}
              {facts.venue && <div className="matchday-facts-line muted">{facts.venue}</div>}
            </div>

            <ul className="matchday-checks">
              {result.qualityChecks.map((c) => (
                <li key={c.id} className={`qc-${c.status}`}>
                  <span className="qc-mark" />
                  <span className="qc-label">{c.label}</span>
                  {c.detail && <span className="qc-detail">{c.detail}</span>}
                </li>
              ))}
            </ul>

            <div className="matchday-actions">
              <button className="brit-modal-action brit-modal-action-secondary" onClick={run}>
                {t('matchday_regenerate')}
              </button>
              <button className="brit-modal-action" onClick={handleSave} disabled={saving || saved}>
                {saved ? t('matchday_saved') : saving ? t('matchday_saving') : t('matchday_save')}
              </button>
              <button
                className="brit-modal-action"
                onClick={handleDownload}
                disabled={!isRealImage(result.imageDataUrl)}
              >
                {t('matchday_download')}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

/** A 1x1 placeholder PNG means the visual pipeline hasn't produced art yet. */
function isRealImage(dataUrl: string): boolean {
  return Boolean(dataUrl) && dataUrl.length > 200;
}

interface AssetRowProps {
  label: string;
  url: string | null;
  required: boolean;
  loading: boolean;
  busy: boolean;
  hint: string;
  uploadLabel: string;
  replaceLabel: string;
  missingLabel: string;
  onPick: (file: File) => void;
}

/** One curated photograph: its current state, and a way to replace it. */
function AssetRow({
  label,
  url,
  required,
  loading,
  busy,
  hint,
  uploadLabel,
  replaceLabel,
  missingLabel,
  onPick,
}: AssetRowProps) {
  const inputId = `matchday-upload-${label.replace(/\s+/g, '-').toLowerCase()}`;
  return (
    <div className={`matchday-asset-row${required && !url && !loading ? ' missing' : ''}`}>
      <div className="matchday-asset-thumb">
        {url ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={url} alt="" />
        ) : (
          <span className="matchday-asset-empty" aria-hidden />
        )}
      </div>
      <div className="matchday-asset-copy">
        <label htmlFor={inputId}>{label}</label>
        <p>{loading ? '…' : url ? hint : missingLabel}</p>
      </div>
      <label className="matchday-asset-action" htmlFor={inputId}>
        {busy ? '…' : url ? replaceLabel : uploadLabel}
      </label>
      <input
        id={inputId}
        type="file"
        accept="image/png,image/jpeg,image/webp"
        disabled={busy}
        onChange={(e) => {
          const file = e.target.files?.[0];
          if (file) onPick(file);
          e.target.value = '';
        }}
      />
    </div>
  );
}
